import { t } from '../i18n';
import { useEffect, useState } from 'react';
import type { AgentProfile, Bootstrap, Fact, FactKind, FactStatus, PreferenceDomain, Source } from '../../shared/contracts';
import { Button } from '@openai/apps-sdk-ui/components/Button';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Textarea } from '@openai/apps-sdk-ui/components/Textarea';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Badge } from '@openai/apps-sdk-ui/components/Badge';
import { Alert } from '@openai/apps-sdk-ui/components/Alert';
import { ArrowRight, Document, Group, ChevronDown } from '@openai/apps-sdk-ui/components/Icon';
import { Dialog, Empty, ErrorNotice, Field, PageHeading, when } from '../components';
import { messageOf, write } from '../api';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import { decodeCard, encodeCard, type AgentCard } from './qr';
import './cognition.css';
import { SourcePill } from '../design-system/SourcePill';
import { ConversationInbox } from './ConversationInbox';
import { RelationshipGraph } from './RelationshipGraph';
import { LifeTimeline } from './LifeTimeline';
import './reading.css';
import { PersonalOverview } from './PersonalOverview';
import { TodoWorkspace } from './TodoWorkspace';

interface Props { view: string; data: Bootstrap; onRefresh: () => Promise<void>; onCreateTask: (prompt: string, contextFactIds?: string[], agentIds?: string[]) => void | Promise<void> }
const statusLabels = (): Record<FactStatus, string> => ({ confirmed: t("已确认", "Confirmed"), inferred: t("推断", "Inferred"), candidate: t("待确认", "To confirm"), superseded: t("已替代", "Superseded") });
const kindLabels = (): Record<FactKind, string> => ({ preference: t("偏好", "Preferences"), value: t("价值取向", "Values"), capability: t("能力", "Capabilities"), constraint: t("约束", "Constraints"), identity: t("身份", "Identity"), decision: t("决定", "Decisions") });
const factOptions = () => Object.entries(kindLabels()).map(([value, label]) => ({ value, label }));
const preferenceDomainLabels = (): Record<PreferenceDomain, string> => ({ work: t('做事方式', 'Working preferences'), taste: t('审美与生活', 'Taste and lifestyle'), general: t('其他偏好', 'General preferences') });
const preferenceDomainOptions = () => Object.entries(preferenceDomainLabels()).map(([value,label])=>({value,label}));
const statusOptions = () => Object.entries(statusLabels()).map(([value, label]) => ({ value, label }));

export function CognitionWorkspace({ view, data, onRefresh, onCreateTask }: Props) {
  const [taskError, setTaskError] = useState('');
  const [sourceId, setSourceId] = useState<string>();
  const createTask: Props['onCreateTask'] = async (...args) => { setTaskError(''); try { await onCreateTask(...args); } catch (error) { setTaskError(messageOf(error)); } };
  const source = data.sources.find(s => s.id === sourceId);
  const refs = (ids: string[], compact = false) => ids.length ? <div className={`cog-refs ${compact ? 'is-compact' : ''}`} aria-label={t("资料来源", "Sources")}>{ids.map(id => {
    const title = data.sources.find(s => s.id === id)?.title || t("来源已不可用", "Source unavailable");
    return <SourcePill key={id} title={title} compact={compact} onOpen={() => setSourceId(id)} />;
  })}</div> : null;
  return <div className={`cognition-workspace ${view === 'conversations' || view === 'relationships' ? 'is-immersive' : ''}`}><ErrorNotice error={taskError} />
    {view === 'conversations' ? <ConversationInbox data={data} refs={refs} onRefresh={onRefresh} /> :
      view === 'timeline' ? <LifeTimeline data={data} refs={refs} onRefresh={onRefresh} onAsk={prompt=>createTask(prompt,[])} /> :
      view === 'relationships' ? <RelationshipGraph data={data} refs={refs} onRefresh={onRefresh} /> :
      view === 'life' ? <Life data={data} refs={refs} onRefresh={onRefresh} onCreateTask={createTask} /> :
      view === 'sources' ? <Sources data={data} onRefresh={onRefresh} onSelect={setSourceId} /> :
      view === 'agents' ? <Agents data={data} onRefresh={onRefresh} onCreateTask={createTask} /> :
      <Self data={data} refs={refs} onRefresh={onRefresh} onCreateTask={createTask} />}
    {source && <Dialog title={t("查看来源", "View source")} onClose={() => setSourceId(undefined)}><div className="cog-stack"><div><h3>{source.title}</h3><p className="cog-muted"><span>{when(source.createdAt)}</span><span>{source.demo ? t("虚构示例资料", "Fictional sample") : t("本机导入资料", "Imported locally")}</span></p></div><pre className="source-text">{source.text}</pre><p className="cog-muted">{t("来源保留原始表述。引用它的推断需要分别确认。", "Original wording is preserved. Interpretations need separate confirmation.")}</p></div></Dialog>}
  </div>;
}
type Refs = { refs: (ids: string[], compact?: boolean) => React.ReactNode };

function Self({ data, refs, onRefresh, onCreateTask }: Pick<Props, 'data'|'onRefresh'|'onCreateTask'> & Refs) {
  const [filter, setFilter] = useState('all'); const [editing, setEditing] = useState<Fact>(); const [history, setHistory] = useState<Fact>();
  const [preferenceDomain, setPreferenceDomain] = useState<PreferenceDomain>('general');
  const [statement, setStatement] = useState(''); const [reason, setReason] = useState(''); const [status, setStatus] = useState<FactStatus>('confirmed'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const facts = data.facts.filter(f => filter === 'all' ? f.status !== 'superseded' : f.status === filter);
  const groups = (['confirmed', 'candidate', 'inferred', 'superseded'] as FactStatus[]).map(value => ({ status: value, facts: facts.filter(f => f.status === value) })).filter(group => group.facts.length);
  const descriptions: Record<FactStatus, string> = { confirmed: t("用于助理判断的个人背景", "Confirmed personal context"), candidate: t("等待你确认后，再作为事实使用", "Confirm before using as a fact"), inferred: t("已有依据，仍需要你的核实", "Supported by evidence; still needs your review"), superseded: t("保留过去的表述与修订过程", "Earlier statements and revisions are retained") };
  return <section className="cog-reading-page">
    <PersonalOverview data={data} refs={refs} onEdit={fact=>{setEditing(fact);setStatement(fact.statement);setStatus(fact.status);setPreferenceDomain(fact.preferenceDomain||'general');setReason('');setError('');}} onHistory={setHistory} onCreateTask={onCreateTask}/>
    <details className="twin-management"><summary><span>{t('管理全部理解','Manage all personal context')}</span><span>{data.facts.length}</span><ChevronDown/></summary><div className="twin-management-content">
    <div className="cog-reading-filters" aria-label={t('认知状态', 'Insight status')}>{[{value:'all',label:t('当前理解','Current')},...statusOptions()].map(option=><Button key={option.value} color="secondary" variant="ghost" size="sm" selected={filter===option.value} onClick={()=>setFilter(option.value)}>{option.label}</Button>)}</div>
    <div className="cog-reading-groups">{groups.map(group=><section key={group.status} className="cog-reading-group"><h2>{statusLabels()[group.status]}<span>{group.facts.length}</span></h2>{group.status!=='confirmed'&&<p className="cog-reading-group-note">{descriptions[group.status]}</p>}
      {group.facts.map(fact=><details key={fact.id} className="cog-reading-row cog-insight-row"><summary><span className="cog-reading-kind">{kindLabels()[fact.kind]}</span><span className="cog-reading-statement">{fact.statement}</span><ChevronDown className="cog-reading-chevron" aria-hidden="true" /></summary><div className="cog-reading-detail"><div className="cog-reading-meta"><span>{t(`第 ${fact.version} 版`, `Version ${fact.version}`)}</span><time>{when(fact.updatedAt)}</time></div>{refs(fact.sourceIds)}<div className="cog-reading-actions"><Button color="secondary" variant="ghost" size="sm" onClick={()=>{setEditing(fact);setStatement(fact.statement);setStatus(fact.status);setPreferenceDomain(fact.preferenceDomain||'general');setReason('');setError('');}}>{t('纠正理解','Correct')}</Button><Button color="secondary" variant="ghost" size="sm" onClick={()=>setHistory(fact)}>{t('修订记录','History')}</Button><Button color="secondary" variant="ghost" size="sm" onClick={()=>onCreateTask(t(`请根据这条个人背景，帮我安排今天能做的一步：${fact.statement}`,`Use this personal context to plan one step I can take today: ${fact.statement}`),[fact.id])}>{t('用于任务','Use in a task')}<ArrowRight aria-hidden="true"/></Button></div></div></details>)}
    </section>)}</div>{!facts.length&&<Empty title={t('这个分类还没有记录','No entries in this category')}/>}
    </div></details>
    {editing && <Dialog className="record-dialog" title={t("纠正助理对你的理解", "Correct personal context")} onClose={() => setEditing(undefined)}><form className="cog-stack record-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await write(`/facts/${editing.id}`, { statement, status, reason, ...(editing.kind==='preference'?{preferenceDomain}:{}), baseVersion: editing.version }, 'PUT'); await onRefresh(); setEditing(undefined); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}><Field label={t("现在应当怎样理解", "Updated understanding")}><Textarea aria-label={t("现在的理解", "Current understanding")} rows={4} required value={statement} onChange={e => setStatement(e.target.value)} /></Field><Field label={t("确认状态", "Status")}><Select align="start" listMinWidth={180} listMaxWidth={260} value={status} options={statusOptions()} onChange={o => setStatus(o.value as FactStatus)} /></Field><>{editing.kind==='preference'&&<Field label={t('偏好分类','Preference category')}><Select align="start" listMinWidth={180} listMaxWidth={260} value={preferenceDomain} options={preferenceDomainOptions()} onChange={option=>setPreferenceDomain(option.value as PreferenceDomain)}/></Field>}</><Field label={t("修正原因", "Reason for change")}><Input aria-label={t("修正原因", "Reason for change")} required placeholder={t("例如：我的时间安排已经改变", "For example: my availability has changed")} value={reason} onChange={e => setReason(e.target.value)} /></Field><p className="cog-muted">{t("原始来源和历次修订会保留。之后的新任务采用本次修正。", "Sources and revisions are preserved. New tasks use this correction.")}</p><ErrorNotice error={error} /><Button color="primary" type="submit" loading={busy}>{t("保存修正", "Save correction")}</Button></form></Dialog>}
    {history && <Dialog title={t("理解的修订记录", "Revision history")} onClose={() => setHistory(undefined)}><div className="cog-stack">{[...history.history].reverse().map(h => <article key={h.version} className="cog-revision"><Badge color="secondary">{t(`第 ${h.version} 版，${statusLabels()[h.status]}`, `Version ${h.version}, ${statusLabels()[h.status]}`)}</Badge><p>{h.statement}</p>{h.kind==='preference'&&<p className="cog-muted">{preferenceDomainLabels()[h.preferenceDomain||'general']}</p>}<small><span>{h.reason}</span><time>{when(h.recordedAt)}</time></small></article>)}</div></Dialog>}
  </section>;
}

function Life(props: Pick<Props, 'data'|'onRefresh'|'onCreateTask'> & Refs) {
  return <TodoWorkspace {...props}/>;
}

function Sources({ data, onRefresh, onSelect }: { data: Bootstrap; onRefresh: () => Promise<void>; onSelect: (id: string) => void }) {
  const [adding, setAdding] = useState(false); const [candidate, setCandidate] = useState<Source>(); const [title, setTitle] = useState(''); const [text, setText] = useState(''); const [kind, setKind] = useState<Source['kind']>('note'); const [factKind, setFactKind] = useState<FactKind>('preference'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <section className="cog-reading-page">
    <PageHeading title={t('资料来源','Sources')} description={t('管理导入资料，核对内容与原始来源。','Manage imported records and inspect their sources.')} compactDescription={t('管理资料并核对原始来源。','Manage records and sources.')} illustration="/art/page-sources-v1.png" action={<Button color="secondary" variant="outline" size="sm" onClick={()=>{setAdding(true);setTitle('');setText('');setError('');}}>{t('导入文字','Import text')}</Button>}/>
    <div className="cog-reading-source-list">{data.sources.map(source=><details key={source.id} className="cog-reading-row cog-reading-source"><summary><Document aria-hidden="true"/><span className="cog-reading-statement">{source.title}</span>{source.demo&&<span className="cog-reading-source-kind">{t('示例','Sample')}</span>}<ChevronDown className="cog-reading-chevron" aria-hidden="true"/></summary><div className="cog-reading-detail"><p>{source.text.length>200?t('这条资料较长，可打开原文查看完整内容。','Open the source to read the full text.'):source.text}</p><div className="cog-reading-meta"><time>{when(source.createdAt)}</time><span>{t(`${data.facts.filter(f=>f.sourceIds.includes(source.id)).length} 条相关理解`,`${data.facts.filter(f=>f.sourceIds.includes(source.id)).length} related insights`)}</span><span>{source.demo?t('虚构示例资料','Fictional sample'):t('本机资料','Local source')}</span></div><div className="cog-reading-actions"><Button color="secondary" variant="ghost" size="sm" onClick={()=>onSelect(source.id)}>{t('查看原文','View original')}</Button><Button color="secondary" variant="ghost" size="sm" onClick={()=>{setCandidate(source);setText('');setError('');}}>{t('补充一条理解','Add an insight')}</Button></div></div></details>)}</div>{!data.sources.length&&<Empty title={t('还没有资料','No sources yet')}/>}
    {adding && <Dialog className="record-dialog" title={t("导入文字资料", "Import text")} onClose={() => setAdding(false)}><form className="cog-stack record-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await write('/sources', { title, text, kind }); await onRefresh(); setAdding(false); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}><Field label={t("资料标题", "Source title")}><Input aria-label={t("资料标题", "Source title")} required value={title} onChange={e => setTitle(e.target.value)} /></Field><Field label={t("资料类型", "Source type")}><Select align="start" listMinWidth={180} listMaxWidth={260} value={kind} options={[{ value: 'note', label: t("笔记", "Note") }, { value: 'conversation', label: t("对话记录", "Conversation records") }, { value: 'document', label: t("文档", "Document") }, { value: 'feedback', label: t("我的反馈", "My feedback") }]} onChange={o => setKind(o.value as Source['kind'])} /></Field><Field label={t("原始文字", "Original text")}><Textarea aria-label={t("原始文字", "Original text")} required rows={9} value={text} onChange={e => setText(e.target.value)} /></Field><p className="cog-muted">{t("资料保存在这台电脑。导入不会自动生成已确认的事实。", "Saved on this computer. Importing does not confirm facts automatically.")}</p><ErrorNotice error={error} /><Button color="primary" type="submit" loading={busy}>{t("保存资料", "Save source")}</Button></form></Dialog>}
    {candidate && <Dialog className="record-dialog" title={t("补充一条待确认的理解", "Add an insight to review")} onClose={() => setCandidate(undefined)}><form className="cog-stack record-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await write('/facts', { kind: factKind, statement: text, sourceIds: [candidate.id], status: 'candidate' }); await onRefresh(); setCandidate(undefined); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}><p className="cog-muted">{t("来源：", "Source: ")}{candidate.title}</p><Select align="start" listMinWidth={180} listMaxWidth={260} value={factKind} options={factOptions()} onChange={o => setFactKind(o.value as FactKind)} /><Textarea aria-label={t("新的理解", "New insight")} required rows={4} placeholder={t("这份资料说明了什么？", "What does this source suggest?")} value={text} onChange={e => setText(e.target.value)} /><ErrorNotice error={error} /><Button color="primary" type="submit" loading={busy}>{t("保存为待确认", "Save for review")}</Button></form></Dialog>}
  </section>;
}

function Agents({ data, onRefresh, onCreateTask }: Pick<Props, 'data'|'onRefresh'|'onCreateTask'>) {
  const [editing, setEditing] = useState<Partial<AgentProfile>>(); const [name, setName] = useState(''); const [role, setRole] = useState(''); const [instructions, setInstructions] = useState('');
  const [sharing, setSharing] = useState<AgentProfile>(); const [qr, setQR] = useState(''); const [importing, setImporting] = useState(false); const [pasted, setPasted] = useState(''); const [preview, setPreview] = useState<AgentCard>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; setQR(''); if (sharing) QRCode.toDataURL(encodeCard({ name: sharing.name, role: sharing.role, instructions: sharing.instructions }), { width: 320, margin: 2 }).then(url => { if (active) setQR(url); }).catch(e => { if (active) setError(messageOf(e)); }); return () => { active = false; }; }, [sharing]);
  const edit = (agent: Partial<AgentProfile>) => { setEditing(agent); setName(agent.name || ''); setRole(agent.role || ''); setInstructions(agent.instructions || ''); setError(''); };
  async function scan(file?: File) { if (!file) return; setError(''); setBusy(true); try { if (!file.type.startsWith('image/') || file.size > 10 * 1024 * 1024) throw new Error(t("请选择 10 MB 以内的二维码图片。", "Choose a QR image smaller than 10 MB.")); const bitmap = await createImageBitmap(file); const scale = Math.min(1, 1600 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale); const context = canvas.getContext('2d')!; context.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close(); const pixels = context.getImageData(0, 0, canvas.width, canvas.height); const decoded = jsQR(pixels.data, pixels.width, pixels.height); if (!decoded) throw new Error(t("没有识别出二维码，请选择更清晰的图片或粘贴名片。", "No QR code found. Choose a clearer image or paste the card.")); setPasted(decoded.data); setPreview(decodeCard(decoded.data)); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }
  return <>
    <PageHeading title={t("我的助理", "Agents")} action={<div className="cog-actions"><Button color="secondary" variant="outline" onClick={() => { setImporting(true); setPasted(''); setPreview(undefined); setError(''); }}>{t("扫码创建", "Import card")}</Button><Button color="primary" onClick={() => edit({})}>{t("创建助理", "Create agent")}</Button></div>} />
    <div className="cog-agent-heading"><span>{data.agents.length} {t("位助理", " agents")}</span><span>{t("由你设定职责和工作方式", "Roles and instructions are yours to set")}</span></div>
    <div className="cog-agents">{data.agents.map(a => <article key={a.id}>
      <div className="cog-avatar large">{a.name[0]}</div><div className="cog-agent-body"><div className="cog-agent-title"><div><h2>{a.name}</h2><p>{a.role}</p></div><Button color="primary" variant="soft" onClick={() => onCreateTask(t(`请作为${a.name}，帮我推进当前最重要的目标。`, `As ${a.name}, help me work toward my most important goal.`), undefined, [a.id])}>{t("开始合作", "Start a task")}<ArrowRight aria-hidden="true" /></Button></div><p className="cog-agent-instructions">{a.instructions}</p><div className="cog-actions"><Button color="secondary" variant="ghost" size="sm" onClick={() => edit(a)}>{t("编辑", "Edit")}</Button><Button color="secondary" variant="ghost" size="sm" onClick={() => { setSharing(a); setError(''); }}>{t("分享名片", "Share card")}</Button></div></div>
    </article>)}</div>{!data.agents.length && <Empty title={t("还没有助理", "No agents yet")} description={t("为一项常做的工作，创建第一个角色。", "Create a role for work you do often.")} />}
    {data.agents.length > 1 && <section className="cog-collaboration"><div className="cog-collaboration-copy"><Group aria-hidden="true" /><div><h3>{t("让助理一起工作", "Work together")}</h3><p>{t("各角色按顺序工作，共享同一任务中的背景、过程与成果。", "Agents work in sequence with shared task context and results.")}</p></div></div><Button color="secondary" variant="outline" onClick={() => onCreateTask(t("请一起为 Agent 工作台内测制定一份符合我的时间和预算的计划，并复核遗漏。", "Work together on an Agent workbench beta plan within my time and budget, then review any gaps."), undefined, data.agents.map(a => a.id))}>{t("创建协作任务", "Create shared task")}<ArrowRight aria-hidden="true" /></Button></section>}
    {editing && <Dialog className="record-dialog" title={editing.id ? t("编辑助理", "Edit agent") : t("创建助理", "Create agent")} onClose={() => setEditing(undefined)}><form className="cog-stack record-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await write(editing.id ? `/agents/${editing.id}` : '/agents', { name, role, instructions }, editing.id ? 'PUT' : 'POST'); await onRefresh(); setEditing(undefined); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}><Field label={t("名字", "Name")}><Input aria-label={t("助理名字", "Agent name")} required maxLength={80} value={name} onChange={e => setName(e.target.value)} /></Field><Field label={t("职责", "Role")}><Input aria-label={t("助理职责", "Agent role")} required maxLength={200} value={role} onChange={e => setRole(e.target.value)} /></Field><Field label={t("工作说明", "Instructions")}><Textarea aria-label={t("助理工作说明", "Agent instructions")} required rows={6} maxLength={3000} value={instructions} onChange={e => setInstructions(e.target.value)} /></Field><ErrorNotice error={error} /><Button color="primary" type="submit" loading={busy}>{t("保存助理", "Save agent")}</Button></form></Dialog>}
    {sharing && <Dialog title={t("助理名片", "Agent card")} onClose={() => setSharing(undefined)}><div className="cog-stack"><h3>{sharing.name}</h3>{qr && <img className="agent-qr" src={qr} alt={t(`${sharing.name}的导入二维码`, `QR code to import ${sharing.name}`)} />}<p>{t("包含角色和工作说明，不包含你的资料、任务或模型密钥。", "Includes the role and instructions, without your sources, tasks or API keys.")}</p><Textarea aria-label={t("助理名片内容", "Agent card content")} rows={3} readOnly value={encodeCard({ name: sharing.name, role: sharing.role, instructions: sharing.instructions })} />{qr && <a className="cog-download" href={qr} download={`${sharing.name}-agent.png`}>{t("下载二维码", "Download QR code")}</a>}<ErrorNotice error={error} /></div></Dialog>}
    {importing && <Dialog title={t("扫码创建助理", "Import agent card")} onClose={() => setImporting(false)}><div className="cog-stack"><p>{t("桌面端可读取二维码图片，或粘贴助理名片。识别后先查看内容，再创建。", "Choose a QR image or paste an agent card. Review its contents before creating the agent.")}</p><label className="qr-upload">{t("选择二维码图片", "Choose QR image")}<input aria-label={t("二维码图片", "QR image")} type="file" accept="image/*" disabled={busy} onChange={e => void scan(e.target.files?.[0])} /></label><Textarea aria-label={t("粘贴助理名片", "Paste agent card")} rows={3} placeholder={t("粘贴完整的 SecondU 名片链接", "Paste a complete SecondU card link")} value={pasted} onChange={e => { setPasted(e.target.value); setPreview(undefined); }} /><Button color="secondary" variant="outline" disabled={!pasted.trim()} onClick={() => { setError(''); try { setPreview(decodeCard(pasted)); } catch (err) { setError(messageOf(err)); } }}>{t("读取名片", "Read card")}</Button>{preview && <div className="cog-import-preview"><Badge color="secondary">{t("待确认的外部角色", "External role to review")}</Badge><h3>{preview.name}</h3><p>{preview.role}</p><pre className="source-text">{preview.instructions}</pre><Alert color="info" variant="soft" title={t("创建后才能参与工作", "Review before creating")} description={t("读取名片不会运行指令、访问链接或授予电脑权限。", "Reading a card does not run instructions, open links or grant computer access.")} /><Button color="primary" loading={busy} onClick={async () => { setBusy(true); setError(''); try { await write('/agents', preview); await onRefresh(); setImporting(false); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}>{t("确认创建助理", "Create this agent")}</Button></div>}<ErrorNotice error={error} /></div></Dialog>}
  </>;
}
