import {useState} from 'react';
import type {PortraitEntry,PortraitKind,Source,FactStatus} from '../../shared/contracts';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {Input} from '@openai/apps-sdk-ui/components/Input';
import {Textarea} from '@openai/apps-sdk-ui/components/Textarea';
import {Select} from '@openai/apps-sdk-ui/components/Select';
import {Plus,CloseBold} from '@openai/apps-sdk-ui/components/Icon';
import {Field,ErrorNotice} from '../components';
import {t} from '../i18n';
import {portraitKinds,portraitKindLabel,portraitStatusLabel,portraitDraft,parsePortraitDraft} from './portrait';
import {SourceSelectField} from './SourceSelectField';
import './portrait.css';
export function PortraitEditor({entries,onChange,sources,disabled,onJsonEditing}:{entries:PortraitEntry[];onChange:(value:PortraitEntry[])=>void;sources:Source[];disabled:boolean;onJsonEditing:(value:boolean)=>void}){
 const [mode,setMode]=useState<'form'|'json'>('form'),[raw,setRaw]=useState(''),[error,setError]=useState(''),[kind,setKind]=useState<PortraitKind>('preference');
 const update=(id:string,patch:Partial<PortraitEntry>)=>onChange(entries.map(entry=>entry.id===id?{...entry,...patch}:entry));
 function applyJson(){try{onChange(parsePortraitDraft(raw,sources));setMode('form');onJsonEditing(false);setError('');}catch(err){setError(err instanceof Error?err.message:String(err));}}
 return <section className="portrait-editor"><div className="portrait-editor-heading"><div><h3>{t('结构化画像','Structured profile')}</h3><p>{t('保留具体判断和依据；不确定的内容先记为待确认。','Keep specific observations and evidence. Leave uncertain information unconfirmed.')}</p></div></div><div className="portrait-editor-tabs"><Button type="button" size="sm" color="secondary" variant="ghost" selected={mode==='form'} disabled={disabled} onClick={()=>{setMode('form');onJsonEditing(false);setError('');}}>{mode==='json'?t('放弃 JSON 改动','Discard JSON changes'):t('分项编辑','Fields')}</Button><Button type="button" size="sm" color="secondary" variant="ghost" selected={mode==='json'} disabled={disabled} onClick={()=>{if(mode==='json')return;setRaw(JSON.stringify(portraitDraft(entries),null,2));setMode('json');onJsonEditing(true);setError('');}}>{t('编辑 JSON','Edit JSON')}</Button></div>
 {mode==='json'?<div className="portrait-editor-json"><Textarea variant="soft" aria-label={t('画像 JSON','Profile JSON')} rows={12} value={raw} disabled={disabled} onChange={event=>setRaw(event.target.value)}/><p className="portrait-editor-note">{t('JSON 只编辑画像条目。先应用到表单，再保存人物；版本与历史由本机自动保留。','JSON edits profile entries only. Apply it to the form before saving. Versions and history are preserved locally.')}</p><Button type="button" color="secondary" variant="outline" disabled={disabled} onClick={applyJson}>{t('应用到表单','Apply to form')}</Button><ErrorNotice error={error}/></div>:<>
 {entries.map((entry,index)=><article key={entry.id} className="portrait-editor-row"><div className="portrait-editor-row-head"><Select disabled={disabled} size="md" value={entry.kind} options={portraitKinds.map(value=>({value,label:portraitKindLabel(value)}))} onChange={option=>update(entry.id,{kind:option.value as PortraitKind})}/><Select disabled={disabled} size="md" value={entry.status} options={(['candidate','inferred','confirmed','superseded'] as FactStatus[]).map(value=>({value,label:portraitStatusLabel(value)}))} onChange={option=>update(entry.id,{status:option.value as FactStatus})}/><Button type="button" color="secondary" variant="ghost" size="sm" uniform aria-label={t(`移除第 ${index+1} 条画像`,`Remove profile entry ${index+1}`)} onClick={()=>onChange(entries.filter(value=>value.id!==entry.id))}><CloseBold/></Button></div><Textarea variant="soft" rows={2} aria-label={t(`第 ${index+1} 条画像内容`,`Profile entry ${index+1}`)} value={entry.statement} onChange={event=>update(entry.id,{statement:event.target.value})} placeholder={t('写下具体内容，避免笼统的人物标签','Write a specific observation, not a broad label')}/><details><summary>{t('依据、时效与隐私','Evidence, dates and privacy')}</summary><SourceSelectField label={t('来源依据','Evidence')} disabled={disabled} value={entry.sourceIds} sources={sources} onChange={sourceIds=>update(entry.id,{sourceIds})} placeholder={t('关联已有来源','Link existing sources')}/><div className="portrait-editor-pair"><Field label={t('起始时间（可选）','Valid from (optional)')}><Input size="md" aria-label={t('画像起始时间','Profile valid from')} placeholder="YYYY-MM-DD" value={entry.validFrom||''} onChange={event=>update(entry.id,{validFrom:event.target.value})}/></Field><Field label={t('结束时间（可选）','Valid until (optional)')}><Input size="md" aria-label={t('画像结束时间','Profile valid until')} placeholder="YYYY-MM-DD" value={entry.validTo||''} onChange={event=>update(entry.id,{validTo:event.target.value})}/></Field></div><Field label={t('隐私标记','Privacy')}><Select disabled={disabled} size="md" value={entry.privacy} options={[{value:'private',label:t('本地私密','Local and private')},{value:'sensitive',label:t('敏感资料','Sensitive information')}]} onChange={option=>update(entry.id,{privacy:option.value as PortraitEntry['privacy']})}/></Field><Field label={t('补充说明（可选）','Additional note (optional)')}><Textarea variant="soft" rows={2} aria-label={t('画像补充说明','Profile note')} value={entry.note||''} onChange={event=>update(entry.id,{note:event.target.value})}/></Field></details></article>)}
 <div className="portrait-add"><Select disabled={disabled} size="md" value={kind} options={portraitKinds.map(value=>({value,label:portraitKindLabel(value)}))} onChange={option=>setKind(option.value as PortraitKind)}/><Button type="button" color="secondary" variant="outline" size="sm" disabled={disabled||entries.length>=100} onClick={()=>onChange([...entries,{id:crypto.randomUUID(),kind,statement:'',status:'candidate',sourceIds:[],privacy:'private',recordedAt:new Date().toISOString()}])}><Plus/>{t('添加条目','Add entry')}</Button></div></>}
 </section>;
}
