import {useState, type ReactNode} from 'react';
import type {Person,Relationship} from '../../shared/contracts';
import {Badge} from '@openai/apps-sdk-ui/components/Badge';
import {t,getLocale} from '../i18n';
import {portraitKinds,portraitKindLabel,portraitStatusLabel} from './portrait';
import './portrait.css';
export function PortraitView({person,refs,relationships=[],compact=false}:{person:Person;relationships?:Relationship[];compact?:boolean;refs:(ids:string[],compact?:boolean)=>ReactNode}){
  const portrait=person.portrait;
  return <div className="portrait-view">
    {!portrait?.entries.length?<p className="portrait-empty">{t('尚未整理结构化画像。可从已知资料添加偏好、经历、目标与边界。','No structured profile yet. Add preferences, experiences, goals and boundaries from known sources.')}</p>:portraitKinds.map(kind=>{const entries=portrait.entries.filter(entry=>entry.kind===kind);return entries.length>0&&<section key={kind} className="portrait-section"><h3>{portraitKindLabel(kind)}</h3>{entries.map(entry=><article className="portrait-entry" key={entry.id}><div className="portrait-entry-status"><Badge color={entry.status==='confirmed'?'success':'secondary'} variant="soft" size="sm">{portraitStatusLabel(entry.status)}</Badge>{entry.privacy==='sensitive'&&<small>{t('敏感资料','Sensitive')}</small>}</div><PortraitStatement text={entry.statement} compact={compact}/>{(entry.validFrom||entry.validTo)&&<small>{t('适用时间：','Valid: ')}{entry.validFrom||t('未注明起点','Unspecified start')}{t(' 至 ',' to ')}{entry.validTo||t('未注明终点','Unspecified end')}</small>}{entry.note&&(compact?<details className="portrait-entry-note-fold"><summary>{t('补充说明','Additional notes')}</summary><p className="portrait-entry-note">{entry.note}</p></details>:<p className="portrait-entry-note">{entry.note}</p>)}{entry.sourceIds.length?refs(entry.sourceIds,true):<small>{t('手动记录，尚未关联来源','Manually recorded without linked evidence')}</small>}</article>)}</section>;})}
    {!compact&&<details className="portrait-json-view"><summary>{t('查看结构化 JSON','View structured JSON')}</summary><pre>{JSON.stringify({id:person.id,name:person.name,role:person.role,description:person.description,sourceIds:person.sourceIds,relationships,portrait:portrait??{schema:'hither.person.v1',version:0,entries:[]}},null,2)}</pre></details>}
    {portrait&&<details className="portrait-history"><summary>{t(`修订记录（${portrait.history.length}）`,`Revision history (${portrait.history.length})`)}</summary>{[...portrait.history].reverse().map(revision=><details key={revision.version}><summary>{t(`版本 ${revision.version}`,`Version ${revision.version}`)}<time>{new Date(revision.recordedAt).toLocaleDateString(getLocale())}</time></summary><ul>{revision.entries.map(entry=><li key={entry.id}>{entry.statement}<small>{portraitStatusLabel(entry.status)}</small>{entry.sourceIds.length?refs(entry.sourceIds,true):null}</li>)}</ul>{!revision.entries.length&&<p>{t('此版本没有画像条目。','This revision has no profile entries.')}</p>}</details>)}</details>}
    {!compact&&<p className="portrait-local-note">{t('画像留在当前本地空间。确认状态或去掉敏感标记都不代表授权公开。','This profile stays in the current local space. Confirmation or removing a sensitivity label does not authorize publication.')}</p>}
  </div>;
}

function PortraitStatement({text,compact}:{text:string;compact:boolean}){const [expanded,setExpanded]=useState(false);return <><p className={compact&&!expanded?'portrait-statement-compact':undefined}>{text}</p>{compact&&text.length>180&&<button className="person-text-toggle" type="button" onClick={()=>setExpanded(!expanded)}>{expanded?t('收起','Show less'):t('展开全文','Read more')}</button>}</>;}
