import { useState } from 'react';
import { Button } from '@openai/apps-sdk-ui/components/Button';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Textarea } from '@openai/apps-sdk-ui/components/Textarea';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Dialog, ErrorNotice, Field } from '../components';
import { write, messageOf } from '../api';
import type { Bootstrap, Person, Relationship, Source } from '../../shared/contracts';

export function PersonForm({ person, data, onClose, onSaved }: { person?: Person; data: Bootstrap; onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(person?.name || ''); const [role, setRole] = useState(person?.role || ''); const [description, setDescription] = useState(person?.description || ''); const [sources, setSources] = useState(person?.sourceIds || []); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <Dialog title={person ? '编辑人物资料' : '添加人物'} onClose={onClose}><form className="cog-stack" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await write(person ? `/people/${person.id}` : '/people', { name, role, description, sourceIds: sources }, person ? 'PUT' : 'POST'); await onSaved(); onClose(); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}><Field label="姓名"><Input aria-label="人物姓名" required value={name} onChange={e => setName(e.target.value)} /></Field><Field label="与你的关系或角色"><Input aria-label="人物角色" value={role} onChange={e => setRole(e.target.value)} /></Field><Field label="已知背景"><Textarea aria-label="人物背景" rows={4} value={description} onChange={e => setDescription(e.target.value)} /></Field><Field label="来源依据"><Select multiple value={sources} options={data.sources.map(s => ({ value: s.id, label: s.title }))} onChange={options => setSources(options.map(o => o.value))} placeholder="选择已有资料（可选）" /></Field><ErrorNotice error={error} /><Button type="submit" color="primary" loading={busy}>保存人物</Button></form></Dialog>;
}

export function RelationshipForm({ relationship, data, onClose, onSaved }: { relationship?: Relationship; data: Bootstrap; onClose: () => void; onSaved: () => Promise<void> }) {
  const [from, setFrom] = useState(relationship?.from || data.people[0]?.id || ''); const [to, setTo] = useState(relationship?.to || data.people[1]?.id || ''); const [label, setLabel] = useState(relationship?.label || ''); const [description, setDescription] = useState(relationship?.description || ''); const [sources, setSources] = useState(relationship?.sourceIds || []); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const peopleOptions = data.people.map(p => ({ value: p.id, label: `${p.name} · ${p.role}` }));
  return <Dialog title={relationship ? '修正关系背景' : '添加人物关系'} onClose={onClose}><form className="cog-stack" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { if (from === to) throw new Error('请选择两个不同的人物。'); await write(relationship ? `/relationships/${relationship.id}` : '/relationships', { from, to, label, description, sourceIds: sources }, relationship ? 'PUT' : 'POST'); await onSaved(); onClose(); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}><Field label="人物一"><Select value={from} options={peopleOptions} onChange={o => setFrom(o.value)} /></Field><Field label="人物二"><Select value={to} options={peopleOptions} onChange={o => setTo(o.value)} /></Field><Field label="关系描述"><Input aria-label="关系名称" required value={label} onChange={e => setLabel(e.target.value)} /></Field><Field label="具体背景"><Textarea aria-label="关系背景" value={description} onChange={e => setDescription(e.target.value)} /></Field><Field label="来源依据"><Select multiple value={sources} options={data.sources.map(s => ({ value: s.id, label: s.title }))} onChange={o => setSources(o.map(i => i.value))} placeholder="选择已有资料（可选）" /></Field><ErrorNotice error={error} /><Button type="submit" color="primary" loading={busy}>保存关系</Button></form></Dialog>;
}

export function ConversationImport({ data, onClose, onSaved }: { data: Bootstrap; onClose: () => void; onSaved: () => Promise<void> }) {
  const [title, setTitle] = useState(''); const [date, setDate] = useState(() => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0,16); }); const [text, setText] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  // If the second write fails, retry against the preserved source instead of creating duplicates.
  const [savedSource, setSavedSource] = useState<Source>();
  return <Dialog title="导入对话记录" onClose={onClose}><form className="cog-stack" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try {
    const lines = text.split('\n').filter(line => line.trim()); if (!lines.length) throw new Error('请填写原始对话。');
    const messages = lines.map((line, index) => { const match = line.match(/^([^：:]+)[：:](.+)$/); if (!match) throw new Error(`第 ${index + 1} 行请使用“姓名：原话”。`); const people = data.people.filter(p => p.name === match[1].trim()); if (people.length !== 1) throw new Error(`“${match[1].trim()}”需要先在人物关系中建立唯一人物记录。`); return { senderId: people[0].id, content: match[2].trim(), time: new Date(date).toISOString() }; });
    const source = savedSource || await write<Source>('/sources', { title, kind: 'conversation', text }); setSavedSource(source);
    const personIds = [...new Set(messages.map(m => m.senderId))];
    await write('/conversations', { title, kind: personIds.length > 2 ? 'group' : 'direct', personIds, messages: messages.map(m => ({ ...m, sourceId: source.id })) }); await onSaved(); onClose();
  } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } }}><Field label="对话标题"><Input aria-label="对话标题" required value={title} disabled={!!savedSource} onChange={e => setTitle(e.target.value)} /></Field><Field label="对话发生时间" hint="用于这次导入的记录，不推断未提供的单条时间。"><Input aria-label="对话发生时间" type="datetime-local" required value={date} onChange={e => setDate(e.target.value)} /></Field><Field label="原始对话" hint={`每行“姓名：原话”。已有人物：${data.people.map(p => p.name).join('、')}。`}><Textarea aria-label="导入对话原文" required rows={8} value={text} disabled={!!savedSource} onChange={e => setText(e.target.value)} /></Field><p className="cog-muted">原文同时保存在资料中，不自动转为已确认的个人认知。</p><ErrorNotice error={error} /><Button type="submit" color="primary" loading={busy}>{savedSource ? '重试保存对话' : '保存对话记录'}</Button></form></Dialog>;
}
