import { useState } from 'react';
import Hero from './Hero';
import EmbeddedProduct from './EmbeddedProduct';
import FuturePlayground from './FuturePlayground';
import Capabilities from './Capabilities';
import ExpertShowcase from './ExpertShowcase';
import { LanguageSwitcher, useSiteLanguage } from './site-language';
import { ThemeSwitcher } from './site-theme';
function Development() {
    const { t } = useSiteLanguage();
    const commits = [
        { time: '09.29 12:50', title: t("建立任务工作流", "Establish the task workflow"), hash: '50d5e1f', body: t("搭建桌面基础、个人上下文与任务工作流。从提出要求开始，保留可继续使用的结果。", "Build the desktop foundation, personal context and task workflow. Start with a request and keep a result you can continue working with.") },
        { time: '09.29 15:03', title: t("建立统一的视觉语言", "Establish a shared visual language"), hash: '7d8bc54', body: t("整理界面、组件与数据呈现，向可理解、可操作的个人工作空间推进。", "Bring interfaces, components and information together into a personal workspace that is clear and usable.") },
        { time: '09.30 13:16', title: t("整合核心产品能力", "Integrate core capabilities"), hash: '659d10e', body: t("将个人认知、Agent 协作、项目和成果组织在同一产品里，补齐可检查的工作状态。", "Bring personal understanding, Agent collaboration, projects and results into one product, with work states you can inspect.") },
        { time: '09.30 13:28', title: t("接入原生桌面环境", "Add the native desktop runtime"), hash: 'fa7baf4', body: t("修正桌面运行与原生窗口衔接。随后继续迭代成果预览、引导、权限与实际页面验收。", "Connect the desktop runtime to a native window. Then continue improving previews, onboarding, permissions and acceptance on real screens.") },
        { time: '10.01 03:11', title: t("发布开源项目与官网", "Publish the open-source project and website"), hash: '697fb71', body: t("公开源码、产品说明与可交互官网。首版 GitHub Pages 部署，以及 Linux 和 macOS 持续集成检查已通过。后续修改继续按实际验证范围记录。", "Publish the source, product documentation and interactive website. The first GitHub Pages deployment and Linux and macOS CI checks passed. Later changes retain their own verification scope.") },
        { time: '10.01 03:28', title: t("交付 macOS 桌面原型", "Deliver the macOS desktop prototype"), hash: 'c6eb301', body: t("修复原生窗口生命周期，完成示例空间的对应验收，并发布 v0.1.0 macOS 桌面原型。官网后续新增内容仍按各自的测试和实屏范围记录。", "Fix the native window lifecycle, complete the corresponding example-space acceptance and release the v0.1.0 macOS desktop prototype. Later website additions retain their own test and visual acceptance scope.") },
    ];
    const [selected, setSelected] = useState(5);
    return <section className="site-section site-development" id="build"><div className="site-section-head"><h2>{t("开发进展", "Development progress")}</h2><p>{t("从任务原型到原生桌面，查看每次提交的实现与验证记录。", "From the first task prototype to the native desktop app, explore the implementation and validation recorded with each commit.")}</p></div><p className="site-commit-span">{t("首四次提交相隔 24 小时 38 分钟。这是提交时间跨度，不代表开发工时或验收完成。", "The first four commits span 24 hours 38 minutes. This is elapsed time, not recorded working hours or completed acceptance.")}</p><div className="site-commit-line" role="group" aria-label={t("开发时间线", "Development timeline")}>{commits.map((item, index) => <button key={item.hash} type="button" aria-pressed={index === selected} onClick={() => setSelected(index)}><time>{item.time}</time><i aria-hidden="true"/><strong>{item.title}</strong><code>{item.hash}</code></button>)}</div><div className="site-commit-detail" aria-live="polite"><div><h3>{commits[selected].title}</h3><p>{commits[selected].body}</p></div><a className="site-pill" href={`https://github.com/YunyueLi/SecondU/commit/${commits[selected].hash}`} target="_blank" rel="noreferrer">{t("查看提交 ↗", "View commit ↗")}</a></div><div className="site-record-links"><a href="https://github.com/YunyueLi/SecondU/blob/main/docs/DEVELOPMENT.md" target="_blank" rel="noreferrer">{t("完整构建记录 ↗", "Complete build record ↗")}</a><a href="https://github.com/YunyueLi/SecondU/blob/main/docs/ITERATION.md" target="_blank" rel="noreferrer">{t("设计反馈与逐项迭代 ↗", "Design feedback and iterations ↗")}</a></div></section>;
}
function OpenSource() { const { t } = useSiteLanguage(); const [copyState, setCopyState] = useState<'idle'|'copied'|'failed'>('idle'); const command = 'git clone https://github.com/YunyueLi/SecondU.git\ncd SecondU\nnpm ci\nnpm run build\nnpm start'; return <section className="site-section site-open" id="open"><div><h2>{t("开始使用 SecondU", "Get started with SecondU")}</h2><p>{t("下载桌面原型，或在本机从源码运行。内置中英文示例，可在连接模型前体验。", "Download the desktop prototype or run it locally from source. Explore the included Chinese and English examples before connecting a model.")}</p><div className="site-open-actions"><a className="site-pill is-primary" href="https://github.com/YunyueLi/SecondU/releases/latest" target="_blank" rel="noreferrer">{t("下载桌面版 ↓", "Download for desktop ↓")}</a><a className="site-pill" href="https://github.com/YunyueLi/SecondU" target="_blank" rel="noreferrer">{t("查看源码 ↗", "View source ↗")}</a></div><small>{t("适用于 Apple Silicon Mac，需 macOS 13 或更高版本。原型尚未通过 Apple 公证。", "For Apple Silicon Macs running macOS 13 or later. This prototype is not Apple-notarized.")}<br />{t("源码可用于本机运行，真实任务需要配置自己的模型。", "The source runs locally. Configure your own model to run real tasks.")}</small></div><div className="site-install"><div><span>{t("从源码开始", "Run from source")}</span><button type="button" onClick={async () => { try {
    await navigator.clipboard.writeText(command);
    setCopyState('copied');
    setTimeout(() => setCopyState('idle'), 2000);
}
catch {
    setCopyState('failed');
} }}>{copyState==='copied' ? t("已复制", "Copied") : t("复制命令", "Copy commands")}</button></div>{copyState==='failed'&&<p role="status">{t("无法访问剪贴板，请选择下方命令复制。","Clipboard access is unavailable. Select and copy the commands below.")}</p>}<pre><code>{command}</code></pre><p>{t("需要 Node.js 22.18 或更高版本。运行后打开 http://127.0.0.1:58645", "Requires Node.js 22.18 or later. Then open http://127.0.0.1:58645")}</p><a href="https://github.com/YunyueLi/SecondU/blob/main/QUICKSTART.md" target="_blank" rel="noreferrer">{t("完整安装与排错说明 ↗", "Installation and troubleshooting ↗")}</a></div></section>; }
function SiteFooter() {
  const { t } = useSiteLanguage();
  const repository = 'https://github.com/YunyueLi/SecondU';
  return <footer className="site-ending site-footer" data-theme="dark"><div className="site-footer-in">
    <nav className="site-footer-cols" aria-label={t('资料与项目链接', 'Documentation and project links')}>
      <div><h3>{t('SecondU', 'SecondU')}</h3><a href="#experience">{t('体验产品', 'Try SecondU')}</a><a href="#capabilities">{t('现有能力', 'Current capabilities')}</a><a href="#future">{t('未来方向', 'Future directions')}</a></div>
      <div><h3>{t('开始使用', 'Get started')}</h3><a href={`${repository}/releases/latest`}>{t('下载桌面版', 'Download for desktop')}</a><a href={`${repository}/blob/main/QUICKSTART.md`}>{t('安装与运行', 'Installation and setup')}</a><a href={repository}>GitHub ↗</a></div>
      <div><h3>{t('设计与开发', 'Design and development')}</h3><a href={`${repository}/blob/main/docs/PRODUCT.md`}>{t('完整产品定位', 'Product vision')}</a><a href={`${repository}/blob/main/docs/ROADMAP.md`}>{t('路线与验收范围', 'Roadmap and verified scope')}</a><a href="#build">{t('构建记录', 'Build record')}</a></div>
      <div><h3>{t('开放与边界', 'Openness and boundaries')}</h3><a href={`${repository}/blob/main/SECURITY.md`}>{t('安全与隐私', 'Security and privacy')}</a><a href={`${repository}/blob/main/LICENSE`}>MIT License</a><a href={`${repository}/blob/main/THIRD_PARTY_NOTICES.md`}>{t('开源致谢', 'Open-source acknowledgments')}</a></div>
    </nav>
    <div className="site-footer-bar"><p>{t('SecondU，另一个你。独立开源项目。', 'SecondU, another you. An independent open-source project.')}<br/>{t('Dev 表示开发中的方向或模拟体验。', 'Dev marks directions in development or simulated experiences.')}</p><div className="site-footer-preferences"><LanguageSwitcher side="top"/><ThemeSwitcher side="top"/></div></div>
  </div></footer>;
}
export default function App() { const { t } = useSiteLanguage(); return <><a className="site-skip" href="#experience">{t("跳到交互体验", "Skip to the interactive experience")}</a><header className="site-header"><a className="site-brand" href="#" aria-label={t("SecondU 首页", "SecondU home")}><img src="./assets/secondu-mark.svg" alt=""/><img src="./assets/secondu-wordmark.svg" alt="SecondU"/></a><nav aria-label={t("网站导航", "Website navigation")}><a href="#experience">{t("体验", "Experience")}</a><a href="#future">{t("未来方向", "Future directions")}</a><a href="#build">{t("开发进展", "Development")}</a><a className="site-header-github" href="https://github.com/YunyueLi/SecondU" target="_blank" rel="noreferrer">GitHub ↗</a><LanguageSwitcher /><ThemeSwitcher /></nav></header><main><Hero /><div id="experience"><EmbeddedProduct /></div><div className="site-value-strip"><div><h2>{t("少重复解释", "Explain less, carry more forward")}</h2><p>{t("你的经历、选择和判断，成为可以延续的背景。", "Your experiences, choices and judgments become context you can keep using.")}</p></div><div><h2>{t("上下文一起流转", "Keep context connected")}</h2><p>{t("多模态资料、任务和成果，跨设备与场景接续。", "Multimodal materials, tasks and results continue across devices and situations.")}</p></div><div><h2>{t("让专业能力走出去", "Share your professional capabilities")}</h2><p>{t("在授权范围内，参与协作、社交和服务交易。", "Take part in collaboration, social connections and service transactions within the scope you authorize.")}</p></div></div><Capabilities /><ExpertShowcase /><FuturePlayground /><section className="site-section site-privacy"><div><h2>{t("属于你的分身，", "Your digital twin.")}<br />{t("由你决定边界。", "Your boundaries.")}</h2><p>{t("个人认知、专业服务和对外分享分别设定范围。完整地理解你，不意味着向每一项任务、每个模型或其他人开放全部资料。", "Set separate scopes for personal understanding, professional services and sharing. Understanding you fully does not open every record to every task, model or other person.")}</p></div><dl><div><dt>{t("自己的资料", "Your own information")}</dt><dd>{t("个人空间与示例空间独立。本页所有交互使用虚构资料，不读取你的设备、个人空间或账户。", "Personal and example spaces are separate. Every interaction here uses fictional materials and does not read your devices, personal workspace or accounts.")}</dd></div><div><dt>{t("具体的授权", "Specific authorization")}</dt><dd>{t("真实任务按相关性使用获准的背景。云模型会收到为当前任务选择的内容，由你决定模型和范围。", "Real tasks use relevant, authorized context. Cloud models receive the material selected for that task; you choose the model and scope.")}</dd></div><div><dt>{t("保留选择权", "Keep control")}</dt><dd>{t("理解能够纠正，任务能够接手，分享能够撤回。电话、付款和真实撮合按各自条件接入与验收。", "Correct an understanding, take over a task or revoke sharing. Calls, payments and real introductions each require their own integration and verification.")}</dd></div></dl></section><Development /><div className="site-ending" data-theme="dark"><OpenSource /></div></main><SiteFooter /></>; }
