import {useState} from 'react';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {Checkbox} from '@openai/apps-sdk-ui/components/Checkbox';
import {TaskActivity} from '../../src/design-system/TaskActivity';
import {TaskApproval} from '../../src/design-system/TaskApproval';
import {ArtifactCard} from '../../src/design-system/ArtifactCard';
import {SourcePill} from '../../src/design-system/SourcePill';
import type {Approval, Task, TaskEvent} from '../../shared/contracts';
import {useSiteLanguage} from './site-language';

export default function TaskPlayground(){
 const {t}=useSiteLanguage();
 const [stage,setStage]=useState(0),[decision,setDecision]=useState<'pending'|'approved'|'rejected'>('pending'),[context,setContext]=useState(['time','style']),[source,setSource]=useState(false),[result,setResult]=useState(false);
 const choices=[{id:'time',title:t('周末只有半天空闲','Half a day free this weekend')},{id:'style',title:t('喜欢步行，行程不要太赶','Enjoys walking at an unhurried pace')},{id:'unrelated',title:t('工作中的代码风格','Coding style at work')}];
 const approval:Approval={id:'website-approval',title:t('读取你选定的行程文件','Read the itinerary file you selected'),description:t('查看读取范围，再决定是否允许这一步。','Review which file would be read, then allow or decline this step.'),details:t('示例操作：读取「周末安排.md」\n范围：本次项目中的这一个虚构文件\n不包含：其他文件、消息发送或付款\n本页不会实际访问电脑。','Sample action: read “Weekend notes.md”\nScope: this one fictional project file\nExcludes: other files, messages and payments\nThis page does not access your computer.'),status:decision};
 const event=(id:string,type:string,label:string,detail:string):TaskEvent=>({id,type,label,detail,createdAt:`2026-10-01T09:0${id}:00Z`});
 const events:TaskEvent[]=[event('1','runtime.plan',t('整理本次需求与选定背景','Review the request and selected context'),t('安排半天阅读与散步，参考已选择的时间和出行偏好。本页展示流程，不调用模型。','Plan half a day of reading and walking using the selected availability and outing preferences. This page shows the workflow without calling a model.'))];
 if(stage>0)events.push(event('2','runtime.approval',t('等待文件读取确认','File access awaits approval'),approval.details!));
 if(decision!=='pending')events.push(event('3',decision==='approved'?'approval.approved':'approval.rejected',decision==='approved'?t('已允许本次读取','Read allowed once'):t('已拒绝本次读取','Read declined'),t('仅更新本页状态，未访问任何真实文件。','Only this page state changed. No real files were accessed.')));
 const task:Task={id:'website-task',title:t('安排周末半天','Plan a weekend afternoon'),prompt:'',agentIds:[],contextFactIds:context,mode:'demo',status:stage===0?'queued':decision==='pending'?'awaiting_approval':decision==='approved'?'completed':'cancelled',createdAt:'2026-10-01T09:00:00Z',updatedAt:'2026-10-01T09:03:00Z',messages:[],events,artifactIds:[],approvals:stage?[approval]:[]};
 return <div className="spg-task"><aside><span className="site-tag">{t('不调用模型的交互演示','Interactive demo without model calls')}</span><h3>{t('先选择背景，再确认文件访问。','Choose the context and review file access.')}</h3><p className="spg-muted">{t('为周末安排选择可用时间和出行偏好。需要读取文件时，先查看具体范围；确认后查看计划示例。','Choose the availability and preferences for a weekend plan. Review the requested file access, then open the example itinerary after approval.')}</p><fieldset><legend>{t('本次允许参考的背景','Context available to this task')}</legend>{choices.map(item=><Checkbox key={item.id} label={item.title} checked={context.includes(item.id)} onCheckedChange={checked=>setContext(previous=>checked?[...previous,item.id]:previous.filter(id=>id!==item.id))}/>)}</fieldset><SourcePill title={t('查看背景依据','Inspect the context source')} onOpen={()=>setSource(!source)}/>{source&&<blockquote>{t('“我周末有半天时间，希望能安静读一会儿书，再在附近散散步。”','“I have half a day free this weekend. I would like to read quietly, then take a walk nearby.”')}<cite>{t('虚构原始记录','Fictional source note')}</cite></blockquote>}</aside><section className="spg-task-process"><div className="spg-task-request">{t('帮我安排周末半天，别排得太满。','Plan half a day for my weekend. Leave some room to breathe.')}</div><TaskActivity task={task}/>{stage===0?<Button color="primary" onClick={()=>setStage(1)}>{t('查看文件访问','Review file access')}</Button>:<TaskApproval approval={approval} onDecision={value=>{setDecision(value==='approve'?'approved':'rejected');setResult(false);}}/>}{decision==='approved'&&<div className="spg-task-outcome"><p>{t('计划示例，未调用模型','Example itinerary without a model call')}</p><ArtifactCard artifact={{name:t('周末半日安排.md','Weekend afternoon.md'),version:1,content:t('阅读一小时，再去附近散步。途中留一段自由时间。','Read for an hour, then walk nearby. Keep some unplanned time in between.')}} onOpen={()=>setResult(!result)}/>{result&&<p>{t('14:00 阅读与笔记 → 15:00 自由安排 → 15:30 附近散步。地点与预算仍需本人确认。','14:00 Reading and notes → 15:00 Unplanned time → 15:30 A walk nearby. Location and budget still need your decision.')}</p>}</div>}{decision==='rejected'&&<p className="spg-demo-note">{t('已拒绝读取，流程停止在这一步。可以重新查看并调整选择。','File access was declined, so this step stopped. Start again to change your selection.')}</p>}{stage>0&&<button className="spg-text-link" onClick={()=>{setStage(0);setDecision('pending');setResult(false);}}>{t('重新开始','Start again')}</button>}</section></div>;
}
