import {useEffect,useState} from 'react';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {Input} from '@openai/apps-sdk-ui/components/Input';
import {Select} from '@openai/apps-sdk-ui/components/Select';
import {Textarea} from '@openai/apps-sdk-ui/components/Textarea';
import {ArrowLeft,ArrowRight,CheckCircle,Reload,ChevronDown,ExternalLink} from '@openai/apps-sdk-ui/components/Icon';
import {Field,ErrorNotice} from '../components';
import {PlatformIcon} from '../cognition/PlatformIcon';
import {api,write,messageOf} from '../api';
import {t} from '../i18n';
import type {ImConnection} from '../../shared/im';
import './im-setup.css';

type Operation={id:string;kind:'install'|'login';status:'running'|'completed'|'failed'|'cancelled';stage:string;code?:string;qr?:string;qrExpiresAt?:string};
type SetupField={key:string;label:string;labelEn?:string;type:'password'|'text'|'url'|'select'|'textarea';required?:boolean;placeholder?:string;defaultValue?:string;options?:{value:string;label:string}[];help?:string;helpEn?:string};
type SupportedChannel={channel:string;label:string;canRead:boolean;canSend:boolean;auth:'qr'|'token';authorizationMode?:'qr'|'credentials'|'external';docsUrl:string;fields?:SetupField[];help?:string;helpEn?:string;requirement?:string;requirementEn?:string;requirements?:{zh:string;en:string}[];singleAccount?:boolean;platform?:string};
type SetupStatus={release:{version:string;node:string};selected:'managed'|'existing';showcase:boolean;managed:{installed:boolean;channels?:string[];gateway:'stopped'|'starting'|'running'|'failed'};existing:{detected:true;version:string}|null;operations?:Operation[];supported:SupportedChannel[];unavailable?:{channel:string;label:string;reason:{zh:string;en:string};docsUrl:string}[]};
type Channel={channel:string;label:string;installed:boolean;accounts:string[];supported:boolean;canRead:boolean};
const channelLabel=(channel:string,label:string)=>channel==='feishu'?t('飞书 / Lark','Feishu / Lark'):channel==='wecom'?t('企业微信','WeCom'):channel==='wechat'?t('微信','WeChat'):channel==='dingtalk'?t('钉钉','DingTalk'):label;
const fieldLabel=(field:SetupField)=>t(({Platform:'平台','Phone number':'电话号码','Local signal-cli service':'本机 signal-cli 服务','imsg executable':'imsg 程序路径','Messages database':'信息数据库路径',Homeserver:'服务器地址','User ID':'用户 ID','Server URL':'服务器地址','Service account JSON':'服务账号 JSON','App URL or project number':'应用网址或项目编号','Audience type':'验证方式'} as Record<string,string>)[field.label]??field.label,field.labelEn??field.label);
function ChannelIcon({channel}:{channel:string}){return <span className={`im-channel-icon is-${channel}`} aria-hidden="true"><PlatformIcon platform={channel}/></span>;}
const stageLabel=(stage:string)=>({install:t('准备安装','Preparing installation'),downloading:t('正在下载连接组件','Downloading connection components'),verifying:t('正在检查安装','Checking the installation'),login:t('等待账号授权','Waiting for account authorization'),scan:t('等待本人扫码','Waiting for you to scan'),checking:t('正在检查连接','Checking the connection'),completed:t('操作已完成','Operation completed')}[stage]??t('正在处理','Working'));
function setupError(error:unknown){const code=(error as {code?:string})?.code;return ({im_setup_node_required:t('需要先安装 Node.js 24.16+（24 系列）或 26.1+，再继续连接。','Install Node.js 24.16+ within v24, or 26.1+, to continue.'),im_setup_integrity:t('安装文件校验未通过，请重试。','The installation could not be verified. Please try again.'),im_setup_command_failed:t('连接未完成。请检查账号权限与网络后重试。','The connection did not complete. Check account permissions and your network, then retry.'),im_setup_unavailable:t('无法启动连接组件。请在安装详情中检查运行要求。','Unable to start connection components. Check the requirements in installation details.'),im_setup_timeout:t('操作超时，请检查状态后重试。','The operation timed out. Check its status before retrying.'),im_setup_operation_missing:t('连接操作已结束，请重新检查账号。','The connection operation ended. Check the account again.')} as Record<string,string>)[code??'']??messageOf(error);}

export function ImSetupWizard({onConnected,onAdvanced,onBack,onBackLabel,onBusyChange}:{onConnected:(connection:ImConnection)=>void;onAdvanced:()=>void;onBack?:()=>void;onBackLabel?:string;onBusyChange?:(busy:boolean)=>void}){
 const [status,setStatus]=useState<SetupStatus>(),[step,setStep]=useState<'channel'|'runtime'|'account'|'scope'>('channel'),[channel,setChannel]=useState('slack'),[accountId,setAccountId]=useState('default'),[channels,setChannels]=useState<Channel[]>([]),[operation,setOperation]=useState<Operation>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[connected,setConnected]=useState(false);
 const [credentials,setCredentials]=useState<Record<string,string>>({}),[name,setName]=useState(''),[target,setTarget]=useState(''),[selfId,setSelfId]=useState('');
 const current=status?.supported.find(item=>item.channel===channel);const pending=busy||operation?.status==='running';const managed=(status?.selected??'managed')==='managed';
 useEffect(()=>{onBusyChange?.(pending);},[pending,onBusyChange]);
 useEffect(()=>()=>{onBusyChange?.(false);},[onBusyChange]);
 const refresh=async()=>{const value=await api<SetupStatus>('/im-setup');setStatus(value);return value;};
 useEffect(()=>{let active=true;api<SetupStatus>('/im-setup').then(value=>{if(active){setStatus(value);setOperation(value.operations?.find(op=>op.status==='running'));}}).catch(err=>{if(active)setError(setupError(err));});return()=>{active=false;};},[]);
 useEffect(()=>{if(operation?.status!=='running')return;let active=true;const timer=window.setInterval(()=>{api<Operation>(`/im-setup/operations/${operation.id}`).then(value=>{if(!active)return;setOperation(value);if(value.status==='completed'){void refresh().catch(err=>setError(setupError(err)));if(value.kind==='install'){setStep('account');setNotice(t('连接组件已准备好，请完成账号授权。','Connection components are ready. Authorize your account to continue.'));}else setNotice(t('登录操作已结束。启动服务后检查账号连接。','Sign-in has finished. Start the service, then check the account connection.'));}else if(value.status==='failed')setError(setupError({code:value.code,message:t('连接未完成。','The connection did not complete.')}));}).catch(err=>{if(active){setError(setupError(err));setOperation(undefined);}});},1000);return()=>{active=false;clearInterval(timer);};},[operation?.id,operation?.status]);
 useEffect(()=>{if(!managed||!['starting','running'].includes(status?.managed.gateway??''))return;let active=true;const timer=window.setInterval(()=>{api<SetupStatus>('/im-setup').then(value=>{if(active)setStatus(value);}).catch(err=>{if(active)setError(setupError(err));});},status?.managed.gateway==='starting'?1500:10000);return()=>{active=false;window.clearInterval(timer);};},[managed,status?.managed.gateway]);
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await action();}catch(err){setError(setupError(err));}finally{setBusy(false);}}
 const selectRuntime=(runtimeId:'managed'|'existing')=>perform(async()=>{setStatus(await write<SetupStatus>('/im-setup/select',{runtimeId}));setChannels([]);setConnected(false);});
 const listChannels=()=>perform(async()=>{const result=await write<{channels:Channel[]}>('/im-setup/channels');setChannels(result.channels);setStep('account');});
 const channelInstalled=!!status?.managed.installed&&(status.managed.channels?.includes(channel)??true);
 const install=()=>perform(async()=>{setOperation(await write<Operation>('/im-setup/install',{channel,confirmed:true}));});
 const fields:SetupField[]=current?.fields??(channel==='whatsapp'?[]:channel==='slack'?[{key:'botToken',label:'Bot Token',type:'password',required:true,placeholder:'xoxb-…'},{key:'appToken',label:'App Token',type:'password',required:true,placeholder:'xapp-…'}]:[{key:'token',label:'Bot Token',type:'password',required:true}]);
 const fieldValue=(field:SetupField)=>credentials[field.key]??field.defaultValue??'';
 const configure=()=>perform(async()=>{await write('/im-setup/configure',{channel,accountId,...Object.fromEntries(fields.map(field=>[field.key,fieldValue(field)])),confirmed:true});setCredentials({});setConnected(false);setNotice(t('授权配置已保存。启动服务后检查账号连接。','Authorization settings are saved. Start the service, then check the account connection.'));});
 const probe=()=>perform(async()=>{const result=await write<{connected:boolean}>('/im-setup/probe',{channel,accountId});setConnected(result.connected);if(result.connected){setStep('scope');if(!name)setName(current?.label??channel);}else setNotice(t('账号尚未连接。请检查授权、服务状态和平台权限。','The account is not connected yet. Check authorization, service status and platform permissions.'));});
 const accounts=channels.find(item=>item.channel===channel)?.accounts??[];
 function choose(value:string){setChannel(value);setAccountId('default');setName('');setTarget('');setSelfId('');setConnected(false);setCredentials({});setNotice('');setError('');setStep('runtime');}
 const progress=step==='channel'?0:step==='scope'?2:1;
 return <section className="im-setup" aria-label={t('连接通信工具','Connect messaging')}>
  {(step!=='channel'||onBack)&&<div className="im-back-nav"><Button color="secondary" variant="ghost" size="sm" disabled={pending} onClick={()=>{if(step==='channel')onBack?.();else setStep(step==='scope'?'account':step==='account'?'runtime':'channel');}}><ArrowLeft/>{step==='channel'?(onBackLabel??t('返回已有连接','Back to connections')):step==='scope'?t('返回账号设置','Back to account'):step==='account'?t('返回连接准备','Back to connection setup'):t('返回选择平台','Back to platforms')}</Button></div>}
  <ol className="im-setup-steps" aria-label={t('连接步骤','Connection steps')}>{[t('选择平台','Choose a platform'),t('连接账号','Connect an account'),t('指定会话','Choose a conversation')].map((label,index)=><li key={index} aria-current={index===progress?'step':undefined} className={index<progress?'is-complete':''}><span>{index<progress?<CheckCircle/>:index+1}</span>{label}</li>)}</ol>
  {step==='channel'?<>
   <div className="im-setup-introduction"><h3>{t('连接你常用的通信平台','Connect the platforms you use')}</h3><p>{t('选择平台，连接账号，再指定需要处理的会话。','Choose a platform, connect your account, then select a conversation.')}</p></div>
   {!status&&!error&&<p className="im-help" role="status">{t('正在加载通信平台…','Loading messaging platforms…')}</p>}
   <div className="im-channel-grid">{(status?.supported??[]).map(item=><button key={item.channel} type="button" className="im-channel-card" disabled={pending} onClick={()=>choose(item.channel)}><ChannelIcon channel={item.channel}/><strong>{channelLabel(item.channel,item.label)}</strong><span>{item.canRead?t('读取与发送','Read and send'):t('手动发送','Manual sending')}</span><ArrowRight/></button>)}</div>
   {!!status?.unavailable?.length&&<details className="im-setup-details im-setup-compatibility"><summary>{t('其他平台的兼容性','Other platform compatibility')}<ChevronDown/></summary><div>{status.unavailable.map(item=><article key={item.channel}><ChannelIcon channel={item.channel}/><div><strong>{channelLabel(item.channel,item.label)}</strong><p>{t(item.reason.zh,item.reason.en)}</p><a className="im-setup-doc-link" href={item.docsUrl} target="_blank" rel="noopener noreferrer">{t('查看平台说明','Platform documentation')}<ExternalLink/></a></div></article>)}</div></details>}
   <div className="im-setup-directory-footer"><span>{t('仅处理你指定的会话。','Only the conversations you choose.')}</span><Button color="secondary" variant="ghost" size="sm" disabled={pending} onClick={onAdvanced}>{t('使用已有工具','Use an existing tool')}<ArrowRight/></Button></div>
  </>:<>
   <div className="im-setup-channel-heading"><ChannelIcon channel={channel}/><div><h3>{t(`连接 ${channelLabel(channel,current?.label??channel)}`,`Connect ${channelLabel(channel,current?.label??channel)}`)}</h3><p>{step==='scope'?t('指定本次连接可以访问的会话。','Choose the conversation this connection may access.'):t('完成平台授权后，即可在 SecondU 中处理指定会话。','Authorize the platform to work with selected conversations in SecondU.')}</p></div></div>
   {status?.showcase?<div className="im-setup-showcase"><p>{t('这是示例空间。连接自己的账号，请返回个人空间。','This is an example workspace. Return to your personal workspace to connect your own account.')}</p><Button color="secondary" variant="outline" onClick={()=>setStep('channel')}>{t('查看其他平台','Browse other platforms')}</Button></div>:<>
   {step==='runtime'&&<>
    <div className="im-setup-prepare"><div><h4>{managed?channelInstalled?t('已准备好连接','Ready to connect'):t('准备连接组件','Prepare the connection'):t('使用已有账号','Use an existing account')}</h4><p>{managed?channelInstalled?t('下一步，按平台要求完成账号授权。','Next, authorize your account with the platform.'):t('SecondU 将安装该平台的连接组件。账号授权由你本人完成。','SecondU will install the components for this platform. You complete the account authorization yourself.'):t('使用本机工具中已完成授权的账号。','Use an account already authorized in your local tool.')}</p></div><Button color="primary" loading={busy} disabled={pending||!current} onClick={()=>{if(!managed)void listChannels();else if(channelInstalled)setStep('account');else void install();}}>{managed&&!channelInstalled?t('安装并继续','Install and continue'):t('继续连接','Continue')}<ArrowRight/></Button></div>
    <details className="im-setup-details"><summary>{t('已有 OpenClaw 或其他配置','Existing OpenClaw or custom setup')}<ChevronDown/></summary><div><div className="im-setup-choice"><Button color="secondary" variant="outline" selected={managed} disabled={pending} onClick={()=>void selectRuntime('managed')}>{t('SecondU 独立管理','Managed by SecondU')}</Button><Button color="secondary" variant="outline" selected={!managed} disabled={pending||!status?.existing} onClick={()=>void selectRuntime('existing')}>{t('使用已有 OpenClaw','Use existing OpenClaw')}</Button></div><div className="im-setup-runtime"><span>{status?.existing?t(`已检测到 OpenClaw ${status.existing.version}`,`Detected OpenClaw ${status.existing.version}`):t('检查是否已安装 OpenClaw','Check for an existing OpenClaw installation')}</span><Button color="secondary" variant="ghost" size="sm" disabled={pending} onClick={()=>void perform(async()=>{setStatus(await write<SetupStatus>('/im-setup/detect'));})}><Reload/>{t('检测','Detect')}</Button></div><p className="im-help">{managed?t('连接配置单独保存在本机，不覆盖已有 OpenClaw 设置。','Connection settings stay in a separate local folder without overwriting existing OpenClaw settings.'):t('已有工具的配置与服务由原工具管理。','Your existing tool continues to manage its configuration and service.')}</p></div></details>
    <details className="im-setup-details"><summary>{t('安装详情','Installation details')}<ChevronDown/></summary><div><p className="im-help">{t(`连接组件使用 OpenClaw ${status?.release.version??''}，需要 Node.js ${status?.release.node??''} 与 npm。安装时从 npm 下载官方程序与依赖。`,`The connection uses OpenClaw ${status?.release.version??''} and requires Node.js ${status?.release.node??''} and npm. The official package and dependencies are downloaded from npm.`)}</p>{current?.docsUrl&&<a className="im-setup-doc-link" href={current.docsUrl} target="_blank" rel="noopener noreferrer">{t('查看平台说明','Read the platform guide')}<ExternalLink/></a>}</div></details>
   </>}
   {step==='account'&&<>
    <div className="im-setup-account-guide"><p>{current?.help?t(current.help,current.helpEn??current.help):current?.auth==='qr'?t('保存连接配置后，用自己的账号扫码登录。','Save the connection settings, then scan with your own account.'):t('按官方说明创建应用，将需要的授权信息填入下方。','Follow the official guide to create an app, then enter the required credentials below.')}</p>{current?.docsUrl&&<a href={current.docsUrl} target="_blank" rel="noopener noreferrer">{t('打开授权说明','Open setup guide')}<ExternalLink/></a>}</div>
    {!!current?.requirements?.length&&<ul className="im-setup-requirements">{current.requirements.map((item,index)=><li key={index}>{t(item.zh,item.en)}</li>)}</ul>}
    {current?.requirement&&<p className="im-help">{t(current.requirement,current.requirementEn??current.requirement)}</p>}
    {!current?.singleAccount&&(!managed&&accounts.length?<Field label={t('选择已授权账号','Choose an authorized account')}><Select disabled={pending} value={accountId} options={accounts.map(value=>({value,label:value}))} onChange={option=>{setAccountId(option.value);setConnected(false);}}/></Field>:<details className="im-setup-details"><summary>{t('账号标识','Account identifier')}<span>{accountId}</span><ChevronDown/></summary><div><Field label={t('账号标识','Account ID')}><Input value={accountId} disabled={pending} onChange={event=>{setAccountId(event.target.value);setConnected(false);}} aria-label={t('账号标识','Account ID')}/></Field></div></details>)}
    {managed?<>
     <div className="im-setup-credential-fields">{fields.map(field=><Field key={field.key} label={fieldLabel(field)} hint={field.help?t(field.help,field.helpEn??field.help):undefined}>{field.type==='select'?<Select disabled={pending} value={fieldValue(field)} options={field.options??[]} onChange={option=>setCredentials(current=>({...current,[field.key]:option.value}))} aria-label={fieldLabel(field)}/>:field.type==='textarea'?<Textarea rows={6} autoComplete="off" spellCheck={false} disabled={pending} value={fieldValue(field)} onChange={event=>setCredentials(current=>({...current,[field.key]:event.target.value}))} placeholder={field.placeholder} aria-label={fieldLabel(field)}/>:<Input type={field.type} autoComplete="off" disabled={pending} value={fieldValue(field)} onChange={event=>setCredentials(current=>({...current,[field.key]:event.target.value}))} placeholder={field.placeholder} aria-label={fieldLabel(field)}/>}</Field>)}</div>
     <div className="im-setup-buttons"><Button color="secondary" variant="outline" disabled={pending||fields.some(field=>field.required&&!fieldValue(field).trim())} onClick={()=>void configure()}>{t('保存授权配置','Save authorization')}</Button>{current?.auth==='qr'&&<Button color="secondary" variant="outline" disabled={pending} onClick={()=>void perform(async()=>{setOperation(await write<Operation>('/im-setup/login',{channel,accountId,confirmed:true}));})}>{t('显示登录二维码','Show sign-in QR code')}</Button>}</div>
     <div className="im-setup-runtime"><span><i className={status?.managed.gateway==='running'?'is-running':''}/>{status?.managed.gateway==='running'?t('通信服务已启动','Messaging service is running'):status?.managed.gateway==='starting'?t('通信服务正在启动','Messaging service is starting'):status?.managed.gateway==='failed'?t('通信服务启动失败','Messaging service failed to start'):t('通信服务未启动','Messaging service is stopped')}</span><Button color="secondary" variant="outline" size="sm" disabled={pending} onClick={()=>void perform(async()=>{setStatus(await write<SetupStatus>('/im-setup/gateway',{action:status?.managed.gateway==='running'?'stop':'start',confirmed:true}));})}>{status?.managed.gateway==='running'?t('停止服务','Stop service'):t('启动服务','Start service')}</Button></div>
    </>:<Button color="secondary" variant="ghost" disabled={pending} onClick={()=>void listChannels()}><Reload/>{t('刷新账号','Refresh accounts')}</Button>}
    <p className="im-help">{current?.canRead?t('支持读取最近消息，预览后再保存。','Read recent messages and review them before saving.'):t('此平台支持手动发送，暂不读取历史消息。','This platform supports manual sending; history reading is not available.')}</p>
    <div className="im-actions im-setup-continue"><Button color="primary" loading={busy} disabled={pending||!accountId.trim()} onClick={()=>void probe()}>{t('检查连接并继续','Check connection and continue')}<ArrowRight/></Button></div>
   </>}
   {step==='scope'&&<>
    <p className="im-notice"><CheckCircle/>{t('账号已连接','Account connected')}</p>
    <Field label={t('连接名称','Connection name')}><Input value={name} onChange={event=>setName(event.target.value)} aria-label={t('连接名称','Connection name')}/></Field>
    <Field label={t('会话或收件人 ID','Conversation or recipient ID')} hint={t('仅处理这个会话，不会同步其他聊天。','Only this conversation is used; other chats are not synced.')}><Input value={target} onChange={event=>setTarget(event.target.value)} placeholder={channel==='slack'?'channel:C0123456789':channel==='discord'?'channel:123456789':channel==='whatsapp'?'+1234567890':t('填写平台中的会话标识','Conversation identifier from the platform')} aria-label={t('会话或收件人 ID','Conversation or recipient ID')}/></Field>
    <details className="im-setup-details"><summary>{t('本人账号信息（可选）','Your account details (optional)')}<ChevronDown/></summary><div><Field label={t('本人用户 ID','Your user ID')}><Input value={selfId} onChange={event=>setSelfId(event.target.value)} aria-label={t('本人用户 ID','Your user ID')}/></Field></div></details>
    <div className="im-actions im-setup-continue"><Button color="primary" loading={busy} disabled={pending||!connected||!name.trim()||!target.trim()} onClick={()=>void perform(async()=>{onConnected(await write<ImConnection>('/im-setup/connection',{channel,accountId,target,name,selfId}));})}>{t('保存并打开会话','Save and open conversation')}<ArrowRight/></Button></div>
   </>}
   </>}
  </>}
  {operation?.status==='running'&&<div className="im-setup-operation" role="status"><span>{stageLabel(operation.stage)}</span>{operation.qr&&<><p>{t('请本人扫码完成登录。','Scan the code yourself to sign in.')}</p><pre className="im-setup-qr" aria-label={t('登录二维码','Sign-in QR code')}>{operation.qr}</pre></>}<Button color="secondary" variant="ghost" size="sm" onClick={()=>void perform(async()=>{setOperation(await write<Operation>(`/im-setup/operations/${operation.id}`,{},'DELETE'));})}>{t('取消','Cancel')}</Button></div>}
  {notice&&<p role="status" className="im-setup-notice">{notice}</p>}<ErrorNotice error={error}/>
 </section>;
}
