import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../server/store.mjs';import {previewChatImport,commitChatImport} from '../server/imports.mjs';import {chatPlatforms} from '../server/chat-adapters.mjs';
function fixture(t){const dir=mkdtempSync(path.join(os.tmpdir(),'hither-platforms-'));const store=new Store(dir,{seed:false});t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});return store;}
const raw=(platform,value,extra={})=>({platform,filename:'fixture.json',accountId:'fictional',content:JSON.stringify(value),...extra});
test('all listed platforms support normalized files and remain isolated by platform',t=>{const s=fixture(t),doc={format:'hither.chat.v1',people:[{id:'a',name:'Fictional A'}],conversations:[{id:'c',title:'Test',kind:'direct',participantIds:['a'],messages:[{id:'m',senderId:'a',text:'original',time:'2026-09-29T10:00:00Z'}]}]};for(const platform of chatPlatforms){const p=previewChatImport(s,raw(platform,doc));assert.equal(p.counts.newPeople,1);commitChatImport(s,p.previewId);}assert.equal(s.list('conversations').length,chatPlatforms.length);assert.equal(s.list('facts').length,0);});
test('Slack native array requires channel identity, keeps originals and merges incremental dates once',t=>{const s=fixture(t),rows=[{type:'message',user:'U1',text:'  Original\n',ts:'1750000000.000001'}];assert.throws(()=>previewChatImport(s,raw('slack',rows)),e=>e.code==='invalid_chat_export');const b=raw('slack',rows,{conversationId:'C1'}),p=previewChatImport(s,b);assert.equal(s.list('sources').length,0);const r=commitChatImport(s,p.previewId);assert.equal(s.get('sources',r.sourceId).text,b.content);assert.equal(s.get('conversations',r.conversationIds[0]).messages[0].content,'  Original\n');assert.equal(previewChatImport(s,b).counts.duplicates,1);assert.throws(()=>previewChatImport(s,raw('slack',[{...rows[0],channel:'C2'}],{conversationId:'C1'})));});
test('Telegram desktop rich text, service events and multi-chat exports preserve stable ids',t=>{const s=fixture(t),doc={chats:{list:[{id:123,name:'Study',type:'personal_chat',messages:[{id:1,from:'A',from_id:'user1',text:['Hello ',{type:'bold',text:'world'}],date_unixtime:'1750000000'},{id:2,actor:'A',actor_id:'user1',type:'service',text:'',date_unixtime:'1750000001'}]}]}};const p=previewChatImport(s,raw('telegram',doc));assert.equal(p.conversations[0].messages[0].content,'Hello world');assert.match(p.conversations[0].messages[1].content,/未下载/);const r=commitChatImport(s,p.previewId);assert.equal(s.get('conversations',r.conversationIds[0]).kind,'direct');});
test('Feishu saved message response reads text, warns about remaining pages, never fetches',t=>{const s=fixture(t),doc={code:0,data:{has_more:true,items:[{message_id:'m1',chat_id:'oc1',sender:{id:'ou1'},msg_type:'text',body:{content:JSON.stringify({text:'Original Feishu text'})},create_time:'1750000000000'}]}};const p=previewChatImport(s,raw('feishu',doc));assert.equal(p.conversations[0].messages[0].content,'Original Feishu text');assert.ok(p.warnings.some(x=>x.includes('后续页')));commitChatImport(s,p.previewId);assert.equal(s.list('facts').length,0);assert.throws(()=>previewChatImport(s,raw('feishu',{...doc,code:123})));});
test('malformed native exports fail instead of producing missing people or invented timestamps',t=>{const s=fixture(t);for(const [platform,doc]of [['slack',[null]],['telegram',{id:1,messages:[{id:1,from:'A',text:'x',date:'2026-09-29'}]}],['feishu',{items:[{message_id:'m',chat_id:'c',sender:{id:'u'},body:{content:'not-json'},create_time:'1'}]}]])assert.throws(()=>previewChatImport(s,raw(platform,doc,{conversationId:'c'})));assert.equal(s.list('people').length,0);});
