export type Localized = readonly [string, string];
export type NetworkService = {
  id: string; agentName: Localized; agentRole: Localized; providerName: Localized; providerUsername: string; title: Localized; summary: Localized;
  category: 'design' | 'research' | 'writing' | 'engineering' | 'life';
  approach: Localized; price: Localized; amount: number; duration: Localized;
  request: Localized; inputs: Localized[]; deliverables: Localized[]; sample: Localized; boundaries: Localized[];
};

// Fictional profiles and local interaction scripts, independent of personal-space data.
export const NETWORK_SERVICES: NetworkService[] = [
  {
    id: 'design', agentName: ['产品体验评审', 'Product UX Review'], agentRole: ['流程诊断与改进建议', 'Flow findings and improvements'], providerName: ['陈静', 'Emily Carter'], providerUsername: '@prismstudio',
    title: ['让预约流程更容易完成', 'Make your booking flow easier to finish'],
    summary: ['从第一次使用的视角，找到让人犹豫、误解或中途离开的环节。', 'See where a first-time visitor hesitates, misunderstands, or drops out.'],
    category: 'design',
    approach: ['按照提供方设定的评审方法，把问题对应到具体截图，再给出修改建议。产品取舍由你确认。', 'This service follows its creator’s review method, ties each finding to a screenshot, and proposes a concrete change. You decide the product trade-offs.'],
    price: ['¥280', '$45'], amount: 280, duration: ['1 个工作日', '1 business day'],
    request: ['评审社区活动的预约流程，重点看第一次使用和手机操作。', 'Review our community activity booking flow, focusing on first-time use and mobile access.'],
    inputs: [['预约流程截图，共 5 张', '5 booking-flow screenshots'], ['已去除个人信息的需求说明', 'A brief with personal information removed']],
    deliverables: [['带截图标注的评审文档', 'An annotated review document'], ['按影响排序的 5 条改进建议', '5 improvements ranked by impact'], ['一次范围内的修改', 'One revision within the agreed scope']],
    sample: ['“继续”没有告诉用户下一步会确认什么。建议在日期下方补上人数与费用，再把按钮改为“核对预约”。', '“Continue” does not explain what comes next. Show party size and price below the date, then use “Review booking” for the button.'],
    boundaries: [['只读取本次选择的截图和说明。', 'Reads only the screenshots and brief selected for this request.'], ['不访问私人对话、联系人和其他项目。', 'Cannot access private chats, contacts, or other projects.'], ['修改范围与费用需要再次确认。', 'Scope or price changes require another confirmation.']],
  },
  {
    id: 'research', agentName: ['用户研究分析', 'User Research Analysis'], agentRole: ['访谈主题与证据核对', 'Interview themes and source checks'], providerName: ['梁文浩', 'Daniel Brooks'], providerUsername: '@traceworks',
    title: ['从访谈里找到值得解决的问题', 'Find the problems worth solving in interviews'],
    summary: ['整理反复出现的主题，也保留少数意见和不支持结论的证据。', 'Find repeated themes while preserving minority views and evidence that challenges them.'],
    category: 'research',
    approach: ['把每个主题与访谈原文关联，保留反例与分歧，交付一份可复核的研究整理。', 'This service links each theme to its source transcript, preserves counterexamples and disagreements, and delivers a reviewable synthesis.'],
    price: ['¥360', '$60'], amount: 360, duration: ['2 个工作日', '2 business days'],
    request: ['整理 4 份社区服务访谈，区分重复问题与个人偏好。', 'Synthesize 4 community-service interviews, separating repeated problems from individual preferences.'],
    inputs: [['4 份去标识的访谈记录', '4 de-identified interview transcripts'], ['研究问题与范围', 'The research question and scope']],
    deliverables: [['主题与原文出处对照', 'Themes linked to source excerpts'], ['主要反例和分歧', 'Counterexamples and disagreements'], ['下一轮访谈提纲', 'A follow-up interview outline']],
    sample: ['三位受访者说“找不到报名入口”，但其中两位是在活动已满后进入页面。应先区分入口问题与名额状态反馈。', 'Three participants could not find the sign-up action, but two arrived after the event was full. Separate navigation friction from availability feedback first.'],
    boundaries: [['只处理本次选定的去标识记录。', 'Processes only the de-identified transcripts selected here.'], ['不补造引述，也不推断受访者身份。', 'Does not invent quotes or infer participant identities.'], ['交付前保留出处和不确定性。', 'Keeps sources and uncertainty visible in the result.']],
  },
  {
    id: 'writing', agentName: ['项目案例编辑', 'Project Case Editing'], agentRole: ['案例结构与事实校对', 'Case structure and fact checks'], providerName: ['苏雅', 'Megan Reed'], providerUsername: '@draftroom',
    title: ['把你的项目故事讲清楚', 'Tell your project story clearly'],
    summary: ['理顺案例结构和表达，让读者看懂你做了什么、为什么这样做。', 'Shape a case study around what you did, why you did it, and what changed.'],
    category: 'writing',
    approach: ['整理案例结构与措辞，标出需要核对的事实，保留团队与个人贡献的区别。', 'This service refines structure and wording, flags facts to verify, and distinguishes individual contributions from the team’s work.'],
    price: ['¥220', '$35'], amount: 220, duration: ['1 个工作日', '1 business day'],
    request: ['编辑这篇作品集案例，说明实际贡献，保留需要核对的数字。', 'Edit this portfolio case study, clarify my contribution, and flag figures that need checking.'],
    inputs: [['一篇作品集案例草稿', 'One portfolio case-study draft'], ['已确认的经历与表达偏好', 'Confirmed experience and tone preferences']],
    deliverables: [['保留修改痕迹的文稿', 'A draft with reviewable edits'], ['结构调整说明', 'Notes on structural changes'], ['事实核对清单', 'A fact-checking list']],
    sample: ['把“负责用户体验优化”改成具体的决定：发现什么问题、你改了哪一步、用户行为如何变化。数据未核实的地方保留标记。', 'Replace “improved the user experience” with the actual decision: what problem appeared, which step you changed, and what users did afterward. Flag unverified figures.'],
    boundaries: [['不夸大经历、头衔与项目成果。', 'Does not inflate experience, titles, or outcomes.'], ['不发布或投递编辑后的文稿。', 'Cannot publish or submit the edited draft.'], ['本次任务结束后停止访问材料。', 'Material access ends with the request.']],
  },
  {
    id: 'patchwork', agentName: ['代码质量评审', 'Code Quality Review'], agentRole: ['行为边界与测试检查', 'Behavior, edge cases and tests'], providerName: ['周昊', 'Michael Turner'], providerUsername: '@patchwork',
    title: ['在合并前找出真正的问题', 'Catch the issues that matter before merging'],
    summary: ['围绕一份改动，检查行为变化、边界条件和测试缺口。', 'Review a change for behavior shifts, edge cases, and gaps in coverage.'],
    category: 'engineering',
    approach: ['沿着改动的调用路径检查上下文，为每条问题提供位置、触发条件和修改建议。', 'This service follows changed call paths and gives each finding a location, a trigger, and a proposed fix.'],
    price: ['¥420', '$65'], amount: 420, duration: ['1 个工作日', '1 business day'],
    request: ['评审这份活动报名改动，重点检查重复提交和名额用尽的情况。', 'Review this event sign-up change, focusing on duplicate submissions and full capacity.'],
    inputs: [['一份代码差异及必要上下文', 'One code diff and its relevant context'], ['预期行为与现有测试说明', 'Expected behavior and current test notes']],
    deliverables: [['按影响排序的评审意见', 'Review findings ranked by impact'], ['具体触发路径与修复建议', 'Concrete triggers and suggested fixes'], ['需要补充的测试场景', 'Test scenarios to add']],
    sample: ['重试请求重新生成了报名标识。若首次写入成功但响应丢失，第二次请求可能重复占用名额；建议复用本次操作的幂等标识。', 'A retry creates a new registration ID. If the first write succeeds but its response is lost, the retry can consume another place. Reuse an idempotency key for the operation.'],
    boundaries: [['只检查本次提供的代码和说明。', 'Reviews only the code and notes supplied for this request.'], ['不运行生产操作，也不读取密钥。', 'Does not run production operations or read secrets.'], ['评审意见需要结合实际环境验证。', 'Findings need validation in the actual environment.']],
  },
  {
    id: 'roam', agentName: ['周末行程规划', 'Weekend Trip Planning'], agentRole: ['时间安排与备选路线', 'Schedules and alternative routes'], providerName: ['唐悦', 'Rachel Adams'], providerUsername: '@slowweekends',
    title: ['留一点余地，安排一个好周末', 'Plan a weekend with room to breathe'],
    summary: ['根据同行人的节奏，把想去的地方排成轻松、可调整的一天。', 'Turn a shortlist into a flexible day that suits everyone’s pace.'],
    category: 'life',
    approach: ['整理你提供的地点、时间和交通条件，安排停留与缓冲，并准备天气变化时的替代方案。', 'This service organizes the places, hours, and travel details you provide, adds breaks, and proposes a weather alternative.'],
    price: ['¥120', '$20'], amount: 120, duration: ['1 个工作日', '1 business day'],
    request: ['给两位朋友安排周六半日散步，包含书店、午餐和一个雨天替代地点。', 'Plan a half-day Saturday walk for two friends, with a bookshop, lunch, and a rainy-day alternative.'],
    inputs: [['想去的地点与已核实开放时间', 'Places to visit and their verified opening hours'], ['同行偏好、出发点与预算', 'Preferences, starting point, and budget']],
    deliverables: [['带停留时间的半日安排', 'A half-day plan with time at each stop'], ['雨天替代路线', 'A rainy-day alternative'], ['出发前待确认事项', 'A checklist to confirm before leaving']],
    sample: ['先在书店停留一小时，再步行去午餐；下午只保留一个可选地点。若下雨，将河边散步换成附近展览，并在出发前确认开放时间。', 'Spend an hour at the bookshop, then walk to lunch. Keep just one optional afternoon stop. If it rains, replace the riverside walk with the nearby exhibition and confirm its hours before leaving.'],
    boundaries: [['不自动定位，也不读取日历。', 'Does not locate you or read your calendar.'], ['地点与开放时间以提供的材料为依据。', 'Places and hours are based on the materials provided.'], ['不预订、购票或联系商家。', 'Does not book, buy tickets, or contact venues.']],
  },
  {
    id: 'hue', agentName: ['品牌视觉设计', 'Brand Identity Design'], agentRole: ['颜色、字体与版式规范', 'Color, type and layout rules'], providerName: ['许宁', 'Sarah Bennett'], providerUsername: '@hueatelier',
    title: ['让品牌视觉形成一致的语言', 'Give your brand a consistent visual language'],
    summary: ['从现有标识和页面出发，整理颜色、字体与版式的使用规则。', 'Build practical color, type, and layout rules from your existing logo and pages.'],
    category: 'design',
    approach: ['比较现有材料中的视觉差异，提出一套可沿用的基础规则，并用两个应用场景说明用法。', 'This service compares the current materials, proposes reusable visual rules, and shows their use in two practical contexts.'],
    price: ['¥380', '$60'], amount: 380, duration: ['2 个工作日', '2 business days'],
    request: ['整理这家独立书店的视觉规范，让活动海报与网站保持一致。', 'Create visual guidelines for an independent bookshop so its event posters and website feel consistent.'],
    inputs: [['已有标识与获准使用的图片', 'The existing logo and approved images'], ['网站截图与两张活动海报', 'Website screenshots and two event posters']],
    deliverables: [['颜色与字体使用规范', 'Color and typography guidelines'], ['两个版式应用示例', 'Two layout examples'], ['交接给设计者的检查清单', 'A handoff checklist for designers']],
    sample: ['正文统一使用一套字体和三个字号。绿色只用于活动日期与主要行动，海报和网站沿用相同规则，避免每个区域都争夺注意力。', 'Use one body typeface at three sizes. Reserve green for event dates and primary actions, following the same rule on posters and the website.'],
    boundaries: [['沿用提供的品牌资产，不冒充原创授权。', 'Uses supplied brand assets without claiming new rights to them.'], ['交付视觉提案，未经确认不替换线上内容。', 'Delivers a proposal; live content changes require confirmation.'], ['不包含商标检索与法律判断。', 'Does not include trademark searches or legal judgments.']],
  },
  {
    id: 'access', agentName: ['无障碍体验评审', 'Accessibility Review'], agentRole: ['键盘、标签与状态反馈', 'Keyboard access, labels and feedback'], providerName: ['刘敏', 'Olivia Morgan'], providerUsername: '@accesspath',
    title: ['让关键操作更容易被看见和使用', 'Make key actions easier to perceive and use'],
    summary: ['检查提供的页面与交互说明，定位键盘、标签和反馈中的障碍。', 'Review supplied pages and interaction notes for keyboard, labeling, and feedback barriers.'],
    category: 'design',
    approach: ['结合截图、语义结构和操作记录，区分已观察到的问题与需要实际设备复核的项目。', 'This service combines screenshots, semantic markup, and interaction notes, separating observed issues from items needing device checks.'],
    price: ['¥320', '$50'], amount: 320, duration: ['2 个工作日', '2 business days'],
    request: ['检查报名表单的键盘流程、错误提示和输入标签，列出可落地的修改。', 'Review a sign-up form’s keyboard flow, errors, and labels, then propose actionable changes.'],
    inputs: [['表单截图与相关语义结构', 'Form screenshots and relevant semantic markup'], ['键盘操作记录与错误状态说明', 'Keyboard interaction notes and error-state descriptions']],
    deliverables: [['逐项标注的问题清单', 'An itemized list of findings'], ['标签与交互修改建议', 'Labeling and interaction recommendations'], ['辅助技术复核步骤', 'Steps for assistive-technology verification']],
    sample: ['错误提示只出现在页面顶部，输入框没有对应说明。建议把错误文字关联到字段，并在提交失败后把焦点移到错误摘要。', 'The error appears only at the top of the page, with no field association. Connect the message to its input and move focus to the error summary after a failed submission.'],
    boundaries: [['结论限于提供的页面和操作证据。', 'Conclusions cover only the supplied pages and interaction evidence.'], ['截图检查不等同于辅助技术实测。', 'Screenshot review does not establish assistive-technology compatibility.'], ['不提供认证或全面合规承诺。', 'Does not provide certification or a blanket compliance guarantee.']],
  },
  {
    id: 'compass', agentName: ['竞品研究分析', 'Competitor Research'], agentRole: ['功能对照与来源核验', 'Feature comparisons and evidence'], providerName: ['赵辰', 'Andrew Collins'], providerUsername: '@compassnotes',
    title: ['把竞品差异放到同一张表里', 'Compare product differences on equal terms'],
    summary: ['围绕一个决策问题，比较功能、使用条件与尚未核实的信息。', 'Compare features, conditions, and unknowns around one concrete decision.'],
    category: 'research',
    approach: ['使用本次提供的官方资料，逐项记录出处与时间，区分功能描述、体验证据和推断。', 'This service uses the official materials supplied, records sources and dates, and separates product claims from observed behavior and inference.'],
    price: ['¥460', '$75'], amount: 460, duration: ['2 个工作日', '2 business days'],
    request: ['比较三个社区活动工具的报名、候补和退款流程，支持下一轮产品取舍。', 'Compare sign-up, waitlist, and refund flows in three community-event tools to inform product priorities.'],
    inputs: [['三个产品的官方资料与截图', 'Official materials and screenshots for three products'], ['需要回答的决策问题', 'The decision this comparison should inform']],
    deliverables: [['包含出处与日期的比较表', 'A comparison table with sources and dates'], ['关键差异与适用条件', 'Key differences and their conditions'], ['需要进一步验证的问题', 'Questions for further validation']],
    sample: ['A 支持候补名单，但资料未说明是否自动补位；B 明确提供限时确认。当前证据能支持比较通知机制，尚不能判断实际补位成功率。', 'A supports a waitlist but does not explain automatic promotion; B describes a timed confirmation. The evidence supports comparing notifications, not actual promotion success rates.'],
    boundaries: [['不把营销描述当成实际体验结论。', 'Does not treat marketing descriptions as observed results.'], ['资料之外的能力保留为未知。', 'Capabilities absent from the supplied materials stay unknown.'], ['不登录他人账户或采集私人数据。', 'Does not sign into other accounts or collect private data.']],
  },
  {
    id: 'signal', agentName: ['问卷数据分析', 'Survey Data Analysis'], agentRole: ['数据质量与群体比较', 'Data quality and group comparisons'], providerName: ['韩佳', 'Jessica Parker'], providerUsername: '@signaldesk',
    title: ['读懂问卷结果里的差异与局限', 'Understand what your survey does and does not show'],
    summary: ['整理有效回答、群体差异和开放意见，让结论保留样本边界。', 'Summarize valid responses, group differences, and comments without losing the sample’s limits.'],
    category: 'research',
    approach: ['先检查题目口径、缺失值和重复记录，再比较比例与开放回答，保留分母和样本限制。', 'This service checks definitions, missing values, and duplicates before comparing response shares and comments, keeping denominators and sample limits visible.'],
    price: ['¥400', '$65'], amount: 400, duration: ['2 个工作日', '2 business days'],
    request: ['整理 120 份活动问卷，比较首次参与者与常客的反馈。', 'Analyze 120 event-survey responses, comparing first-time visitors with returning attendees.'],
    inputs: [['去标识的问卷结果表', 'A de-identified survey response table'], ['问卷题目与发放方式', 'Survey questions and distribution details']],
    deliverables: [['数据质量与有效样本说明', 'Data-quality and valid-sample notes'], ['分组比较与图表说明', 'Group comparisons with chart notes'], ['开放意见主题与原文出处', 'Comment themes linked to original responses']],
    sample: ['首次参与者中有 18／40 人提到入口难找，常客中为 9／80 人。两组回答比例有差异，但自愿填写的样本不能直接代表全部来访者。', '18 of 40 first-time visitors mention trouble finding the entrance, compared with 9 of 80 returning attendees. Response shares differ, but this voluntary sample may not represent all visitors.'],
    boundaries: [['只分析本次提供的去标识数据。', 'Analyzes only the de-identified data supplied here.'], ['不从小样本推断个人身份。', 'Does not infer identities from small groups.'], ['观察到的差异不自动解释为因果。', 'Observed differences are not automatically treated as causal.']],
  },
  {
    id: 'voice', agentName: ['品牌文案编辑', 'Brand Copy Editing'], agentRole: ['语气规范与文案修订', 'Voice guidelines and copy revisions'], providerName: ['宋怡', 'Laura Mitchell'], providerUsername: '@voicestudio',
    title: ['让每一段文案都像同一个品牌', 'Make your copy sound like one brand'],
    summary: ['对照已有表达，把首页、介绍和邮件草稿调整为一致的语气。', 'Bring a homepage, about text, and email draft into a voice consistent with your existing work.'],
    category: 'writing',
    approach: ['提炼你确认的用词和语气，重写关键段落，并说明每处修改如何服务读者。', 'This service extracts approved wording and tone, revises key passages, and explains how each change helps the reader.'],
    price: ['¥260', '$40'], amount: 260, duration: ['1 个工作日', '1 business day'],
    request: ['把工作室首页和欢迎邮件改得自然、具体，避免空泛宣传。', 'Make our studio homepage and welcome email natural and specific, avoiding vague promotional claims.'],
    inputs: [['首页与欢迎邮件草稿', 'Homepage and welcome-email drafts'], ['三段已认可的品牌表达', 'Three approved examples of the brand voice']],
    deliverables: [['两份可编辑的文案修订稿', 'Two editable copy revisions'], ['语气与用词简表', 'A concise voice and wording guide'], ['修改说明与待确认事实', 'Edit notes and facts to confirm']],
    sample: ['将“为你打造无限可能”改为“带上初稿，我们一起把它改成能上线的第一页”。具体说明可以得到什么，也保留工作室原本轻松的语气。', 'Replace “unlock limitless possibilities” with “Bring a draft; we’ll help turn it into a first page you can launch.” Explain the offer while keeping the studio’s relaxed voice.'],
    boundaries: [['不编造客户、业绩或服务承诺。', 'Does not invent customers, results, or service promises.'], ['尊重提供的署名与引用来源。', 'Preserves the supplied attribution and sources.'], ['只交付草稿，不自动发送邮件。', 'Delivers drafts without sending emails.']],
  },
  {
    id: 'release', agentName: ['产品更新说明', 'Product Release Notes'], agentRole: ['版本变化与使用说明', 'Version changes and instructions'], providerName: ['吴越', 'David Foster'], providerUsername: '@releasenotes',
    title: ['把开发记录写成用户看得懂的更新', 'Turn development notes into useful product updates'],
    summary: ['解释用户会看到什么变化、怎样使用，以及仍有哪些限制。', 'Explain what changes for users, how to use it, and what limits remain.'],
    category: 'writing',
    approach: ['核对已完成与待发布状态，把技术改动转成具体使用情境，保留兼容要求和已知限制。', 'This service checks completion and release status, translates changes into user scenarios, and preserves compatibility requirements and known limits.'],
    price: ['¥180', '$30'], amount: 180, duration: ['1 个工作日', '1 business day'],
    request: ['根据本次已验收的改动，写一份简短更新说明与帮助页补充。', 'Write a concise update and help-page addition from this batch of accepted changes.'],
    inputs: [['本次改动与验收记录', 'Change descriptions and acceptance notes'], ['发布范围及已知限制', 'Release scope and known limitations']],
    deliverables: [['面向用户的更新说明', 'User-facing release notes'], ['帮助页使用步骤', 'Help-page instructions'], ['发布前核对清单', 'A pre-publication checklist']],
    sample: ['现在可以在预约详情里修改参与人数。若剩余名额不足，页面会保留原预约并提示可增加的人数；此功能仅适用于尚未开始的活动。', 'You can now change party size in booking details. If capacity is insufficient, the original booking remains and the page shows how many people you can add. This applies only to events that have not started.'],
    boundaries: [['未发布的功能保留明确状态。', 'Unreleased features keep an explicit status.'], ['不把测试通过写成上线或用户采用。', 'Does not equate passing tests with release or user adoption.'], ['发布渠道与最终发送由你确认。', 'You approve publication channels and final sending.']],
  },
  {
    id: 'schema', agentName: ['接口文档编写', 'API Documentation'], agentRole: ['字段、错误与调用示例', 'Fields, errors and request examples'], providerName: ['郑凯', 'Brian Hayes'], providerUsername: '@schemabook',
    title: ['让接口说明能直接拿来联调', 'Make API documentation ready for integration'],
    summary: ['整理请求、响应、错误和示例，暴露文档与实现之间的缺口。', 'Document requests, responses, errors, and examples while surfacing gaps between documentation and implementation.'],
    category: 'engineering',
    approach: ['从提供的定义和实现中对齐字段、状态码与约束，标记无法从材料确认的行为。', 'This service aligns fields, status codes, and constraints across the supplied definitions and implementation, flagging behavior the materials cannot confirm.'],
    price: ['¥340', '$55'], amount: 340, duration: ['2 个工作日', '2 business days'],
    request: ['补齐活动报名接口的说明，包含重复提交、名额不足和取消报名。', 'Complete documentation for an event registration API, including duplicates, full capacity, and cancellation.'],
    inputs: [['接口定义与相关实现片段', 'API definitions and relevant implementation excerpts'], ['已去除凭据的请求响应样例', 'Request and response examples with credentials removed']],
    deliverables: [['字段、状态码和约束说明', 'Fields, status codes, and constraints'], ['可复核的请求响应示例', 'Reviewable request and response examples'], ['文档与实现差异清单', 'A list of documentation and implementation gaps']],
    sample: ['人数超过剩余名额时返回 409，并包含 availableSeats。调用方应保留表单内容，提示当前可用人数；示例中的身份字段全部使用占位值。', 'When party size exceeds remaining capacity, return 409 with availableSeats. The client should retain the form and show the available number; all identity fields in examples use placeholders.'],
    boundaries: [['不请求生产接口或索取访问密钥。', 'Does not call production APIs or ask for access keys.'], ['无法证实的接口行为保留待确认。', 'Unverified API behavior stays marked for confirmation.'], ['示例只使用虚构或脱敏数据。', 'Examples use fictional or sanitized data only.']],
  },
  {
    id: 'checkpoint', agentName: ['验收测试设计', 'Acceptance Test Design'], agentRole: ['关键路径与故障场景', 'User journeys and failure scenarios'], providerName: ['孙磊', 'Mark Sullivan'], providerUsername: '@checkpointlab',
    title: ['把需求变成能判断对错的验收', 'Turn requirements into clear acceptance checks'],
    summary: ['从关键用户路径出发，覆盖成功、失败、恢复和状态一致性。', 'Cover success, failure, recovery, and state consistency across key user journeys.'],
    category: 'engineering',
    approach: ['把需求拆成可观察结果，说明前置条件、操作与预期，优先覆盖会造成真实影响的边界。', 'This service converts requirements into observable outcomes, with preconditions, actions, and expectations, prioritizing consequential edge cases.'],
    price: ['¥300', '$50'], amount: 300, duration: ['1 个工作日', '1 business day'],
    request: ['为草稿保存和重新打开设计验收场景，覆盖网络中断与重复点击。', 'Design acceptance checks for saving and reopening drafts, including network interruption and repeated clicks.'],
    inputs: [['需求说明与状态流转图', 'Requirements and a state-transition diagram'], ['现有测试与已知故障记录', 'Existing checks and known failure reports']],
    deliverables: [['按风险排序的验收场景', 'Acceptance scenarios ranked by risk'], ['每个场景的前置条件与预期', 'Preconditions and expectations for each scenario'], ['可自动化与需人工检查的划分', 'Automation candidates and manual checks']],
    sample: ['保存完成前断网：页面应保留编辑内容并显示未保存；恢复连接后再次保存，只生成一个新版本。重新打开后应看到刚才确认保存的内容。', 'Disconnect before saving completes: keep the edits and show an unsaved state. After reconnecting, save again and create only one new version. Reopening should show the content confirmed as saved.'],
    boundaries: [['测试设计不等于测试已经执行。', 'A test plan does not mean the tests have run.'], ['不使用真实用户数据构造样本。', 'Does not use real user data for fixtures.'], ['实际通过情况需由运行证据确认。', 'Actual pass results require execution evidence.']],
  },
  {
    id: 'pantry', agentName: ['家庭备餐规划', 'Household Meal Planning'], agentRole: ['备菜顺序与采购清单', 'Preparation and shopping lists'], providerName: ['叶青', 'Katherine Reed'], providerUsername: '@pantrynotes',
    title: ['用好冰箱里的食材，少做几次决定', 'Use what is in your fridge and simplify dinner'],
    summary: ['围绕已有食材、口味和做饭时间，安排几顿容易衔接的家常饭。', 'Plan connected home meals around your ingredients, preferences, and cooking time.'],
    category: 'life',
    approach: ['优先使用你列出的食材，把准备工作集中到少数步骤，并单独列出需要补买的东西。', 'This service prioritizes the ingredients you list, groups preparation into a few steps, and separates what still needs buying.'],
    price: ['¥90', '$15'], amount: 90, duration: ['1 个工作日', '1 business day'],
    request: ['用现有蔬菜、鸡蛋和豆腐安排三个工作日晚餐，每晚做饭不超过半小时。', 'Plan three weeknight dinners using our vegetables, eggs, and tofu, with no more than half an hour of cooking each night.'],
    inputs: [['现有食材与可用厨房设备', 'Available ingredients and kitchen equipment'], ['人数、忌口与做饭时间', 'Number of diners, food restrictions, and cooking time']],
    deliverables: [['三日晚餐安排与简要步骤', 'Three dinner plans with short instructions'], ['合并后的备菜顺序', 'A combined preparation sequence'], ['按用量整理的补购清单', 'A shopping list organized by quantity']],
    sample: ['周一做番茄豆腐配米饭，顺手洗好第二天要用的青菜；周二做青菜蛋炒饭。补购清单只保留缺少的葱和一份主食，并先核对食材状态。', 'Make tomato tofu with rice on Monday and wash Tuesday’s greens at the same time. Make vegetable egg fried rice on Tuesday. The shopping list includes only missing scallions and one staple; check ingredients before use.'],
    boundaries: [['按用户明确提供的忌口安排。', 'Follows the food restrictions explicitly supplied.'], ['不提供医疗营养方案或诊断。', 'Does not provide medical nutrition plans or diagnoses.'], ['不下单购买，也不判断食材实际安全状态。', 'Does not place orders or verify the physical safety of ingredients.']],
  },
  {
    id: 'shelf', agentName: ['阅读笔记分析', 'Reading Notes Analysis'], agentRole: ['主题关联与观点对照', 'Themes and contrasting viewpoints'], providerName: ['林岚', 'Anna Wallace'], providerUsername: '@bookmarkshelf',
    title: ['让读过的内容成为可回看的笔记', 'Turn your reading into notes you can return to'],
    summary: ['整理你已有的摘录与想法，建立主题关联和下一步阅读问题。', 'Organize your excerpts and thoughts into themes and questions for further reading.'],
    category: 'life',
    approach: ['区分作者观点、你的批注和整理时的推断，保留出处，把重复出现的问题串起来。', 'This service distinguishes the author’s views, your annotations, and synthesis inferences, preserving references and connecting recurring questions.'],
    price: ['¥150', '$25'], amount: 150, duration: ['1 个工作日', '1 business day'],
    request: ['把这两本书的个人笔记按“城市与归属感”整理，保留我不同意的地方。', 'Organize my notes from two books around cities and belonging, preserving where I disagree.'],
    inputs: [['本人整理的摘录与阅读笔记', 'Your own excerpts and reading notes'], ['书目、页码与关注的问题', 'Book references, page numbers, and questions of interest']],
    deliverables: [['按主题组织的阅读笔记', 'Reading notes organized by theme'], ['观点、批注与分歧对照', 'A comparison of views, annotations, and disagreements'], ['可继续追问的五个问题', 'Five questions for further exploration']],
    sample: ['两份笔记都提到熟悉的日常路线，但你在第二本旁边写了“流动也能形成归属”。把它保留为分歧，继续追问：归属感依赖地点，还是稳定的关系？', 'Both sets of notes mention familiar routines, but beside the second book you wrote, “Belonging can also form through movement.” Preserve this disagreement and ask whether belonging depends on place or stable relationships.'],
    boundaries: [['只使用本次提供的摘录与笔记。', 'Uses only the excerpts and notes supplied for this request.'], ['不补造未读章节或作者原话。', 'Does not invent unread passages or quotes.'], ['不自动共享或发布私人批注。', 'Does not automatically share or publish private annotations.']],
  },
];

export type InterestId = 'walks' | 'cooking' | 'books' | 'photography' | 'outdoors';
export const INTERESTS: { id: InterestId; label: Localized }[] = [
  {id:'walks',label:['城市漫步','City walks']}, {id:'cooking',label:['做饭','Cooking']},
  {id:'books',label:['阅读','Reading']}, {id:'photography',label:['摄影','Photography']}, {id:'outdoors',label:['户外','Outdoors']},
];
export type NetworkPerson = {
  id: string; name: Localized; age: number; gender:'women'|'men'; portrait:number; city:Localized; work:Localized;
  about:Localized; intention:Localized; interests:InterestId[]; prompts:{question:Localized;answer:Localized}[];
  incomingLike:boolean; incomingComment:Localized; opening:Localized;
};
export const NETWORK_PEOPLE: NetworkPerson[] = [
  {id:'lin',name:['林晨','Lin Chen'],age:29,gender:'women',portrait:3,city:['杭州','Portland'],work:['建筑设计师','Architect'],
    about:['工作日画房子，周末走进小街小巷。会为一棵开花的树绕远路。','I draw buildings during the week and wander side streets on weekends. I’ll take the long way for a tree in bloom.'],
    intention:['想认真了解一段长期关系','Looking to get to know someone for a long-term relationship'],interests:['walks','photography','cooking'],
    prompts:[{question:['我理想的周末','My kind of weekend'],answer:['不设闹钟，找一家没去过的早餐店，然后带着相机沿河走一段。','No alarm, breakfast somewhere new, and a walk by the river with my camera.']},{question:['可以一直聊下去的话题','Something I can talk about for hours'],answer:['一座城市为什么让人想留下来。可能是一家书店，也可能只是回家路上的灯。','What makes a city feel like home. Sometimes it’s a bookshop; sometimes it’s the lights on the way back.']}],
    incomingLike:true,incomingComment:['我也喜欢走不熟悉的小路。你最近拍到过什么有意思的地方？','I like taking unfamiliar streets too. Have you photographed anywhere interesting lately?'],opening:['你说的那条河边路线我很想试试。你会先选早餐店，还是先选散步路线？','I’d love to try that riverside walk. Do you pick the breakfast spot first, or the route?']},
  {id:'emma',name:['艾米','Emma Brooks'],age:30,gender:'women',portrait:2,city:['杭州','Portland'],work:['社区项目策划','Community program designer'],
    about:['喜欢把朋友聚在一起，试着做一道新菜。旅行时更愿意逛菜市场，而不是赶景点。','I bring friends together to try a new recipe. When traveling, I’d rather visit a market than race through landmarks.'],
    intention:['希望从轻松交流开始，认真认识彼此','An easy conversation first, with an open mind about a lasting relationship'],interests:['cooking','books','walks'],
    prompts:[{question:['一道会做给朋友的菜','What I cook for friends'],answer:['一大锅番茄炖豆，配刚烤好的面包。简单一点，才有时间坐下来聊天。','A big pot of tomato beans with fresh bread. Simple food leaves more time to sit and talk.']},{question:['最近的一件小事','A small thing that made my week'],answer:['邻居借给我一本做满批注的旧书，像多认识了她一点。','A neighbor lent me a book full of notes. It felt like getting to know her a little better.']}],
    incomingLike:false,incomingComment:['',''],opening:['你提到喜欢做饭，我有点好奇你最近最满意的一道菜。','You mentioned cooking. What’s something you’ve made recently that you were pleased with?']},
  {id:'alex',name:['亚历克斯','Alex Morgan'],age:34,gender:'men',portrait:5,city:['杭州','Portland'],work:['户外课程教练','Outdoor educator'],
    about:['喜欢慢慢走完一段路，也喜欢回家后窝在沙发里看电影。周末偶尔带大家认识身边的植物。','I like taking a trail slowly, then settling in for a film at home. Some weekends I lead walks to learn about nearby plants.'],
    intention:['寻找一段稳定、彼此支持的关系','Looking for a steady, supportive relationship'],interests:['outdoors','photography','books'],
    prompts:[{question:['值得早起的事','Worth getting up early for'],answer:['雨后森林的味道，还有爬完山以后那碗热腾腾的面。','The smell of the woods after rain, and a hot bowl of noodles after the hike.']},{question:['一起试一件新鲜事','Something new we could try'],answer:['交换一本最喜欢的书，再找个安静的地方聊聊喜欢它的原因。','Swap a favorite book, then find a quiet place to talk about why it stayed with us.']}],
    incomingLike:false,incomingComment:['',''],opening:['如果交换一本书，你会先选哪一本？','If we swapped a book, which one would you choose first?']},
];
