import { t } from '../i18n';

export type GuideChapterId = 'vision'|'devices'|'cognition'|'life'|'experts'|'projects'|'world'|'history';
export type GuideChapter = {id:GuideChapterId; label:string; title:string; description:string; detail?:string; note:string; status:string; action:string; target:string; steps:string[]};
export {GUIDE_VERSION,readGuideProgress,hasSeenProductGuide,saveGuideProgress,completeGuideChapter} from './guideProgress.mjs';
export function getGuideChapters():GuideChapter[] { const chapters:GuideChapter[] = [
  {id:'vision',label:t('认识 Hither','Meet Hither'),title:t('个人认知，驱动判断与行动','Personal understanding that guides judgment and action'),description:t('Hither 希望成为高精度数字分身认知驱动的个人超级助理。理解你的目标、价值排序、决策方式、现实约束、关系语境与表达偏好，在新情境中一起判断取舍，并把重要的事推进到交付。','Hither aims to be a personal super-assistant guided by precise digital-twin cognition: your goals, priorities, decision style, constraints, relationships, and expression, applied to new decisions and meaningful work.'),note:t('高精度与超级助理是目标，尚未完成本人盲测或证明 AGI。当前用有来源的认知、任务、纠正与反馈建立可验证的起点。','Precision and super-assistance are goals, not validated personal accuracy or AGI. Traceable context, tasks, corrections, and feedback are the current foundation.'),status:t('产品方向','Product vision'),action:t('开始一段对话','Start a conversation'),target:'assistant',steps:[t('了解当下','Your context'),t('一起做事','Work together'),t('从反馈继续','Learn from feedback')]},
  {id:'devices',label:t('随身 Hither','Hither with you'),title:t('换一个设备，仍接着同一件事','The same intention, across devices'),description:t('桌面处理复杂工作，手机随手补充与审阅，眼镜在现实场景接住短暂的意图。需要你判断时，回到适合阅读和确认的界面。','Use a desktop for deep work, a phone to add context and review, and glasses to capture a brief intention in the world. Return to the right screen when a decision needs attention.'),note:t('当前可运行的是桌面。手机与眼镜为设备无关方案，尚未接入真实设备或完成硬件验证。','The desktop runs today. Phone and glasses are device-independent designs, without live device integration or hardware validation.'),status:t('桌面可用，多端规划','Desktop today, more planned'),action:t('体验跨端 Dev','Try the cross-device Dev'),target:'devices',steps:[t('桌面审阅','Desktop review'),t('手机补充','Phone context'),t('眼镜轻交互','Glasses interaction')]},
  {id:'cognition',label:t('了解你，也允许纠正','Understand and correct'),title:t('它如何理解你，你看得见','See how it understands you'),description:t('从自我、当前生活、联系人记录、人生时间轴和人物关系五个视图了解你。判断能回到来源，候选与确认分开；纠正一条理解，保留原版，并让更新进入下一次协作。','Understand yourself through five views: profile, life now, contact history, timeline, and relationships. Trace judgments to sources, distinguish candidates from confirmed context, and carry corrections into future work.'),note:t('确认事实与候选分开；选中的认知附版本和有限证据摘录。当前不是全库语义检索，也不会自动把推测变成事实。','Confirmed facts and candidates stay separate. Selected context carries versions and bounded evidence excerpts. This is not full semantic retrieval, and inferences do not become facts automatically.'),status:t('已实现','Implemented'),action:t('查看自我认识','Explore your profile'),target:'self',steps:[t('查看理解','Inspect context'),t('回到依据','Open evidence'),t('纠正并保留版本','Correct with history')]},
  {id:'life',label:t('工作与生活','Work and life'),title:t('把眼前的事，放回长期目标里','Keep today connected to the longer view'),description:t('工作任务、家人、导师与休息时间，都影响一周的取舍。将长期目标放回当前生活，安排获授权的例行工作；继续建设只在有变化或需要你判断时提醒的主动协作。','Work, family, mentors, and rest all shape the week. Bring long-term goals into life now and authorize routines, while building toward proactive help that surfaces meaningful changes and decisions.'),note:t('自动化依赖本机服务运行。电脑活动是明确标注的 Dev 示例，尚未采集这台电脑的跨应用历史。','Automations depend on the local service staying active. Computer activity is a labelled Dev example, with no cross-app collection on this computer.'),status:t('本机能力与 Dev','Local features and Dev'),action:t('安排本机自动化','Explore local automations'),target:'automations',steps:[t('本周重点','This week'),t('安排例行工作','Set a routine'),t('回看与调整','Review and adjust')]},
  {id:'experts',label:t('你的专家与团队','Your experts and team'),title:t('给不同事情，合适的伙伴','The right partner for each kind of work'),description:t('从 108 个职责预设中选择起点，再补上你的目标与做事方式。每位助理有工牌、模型与持续会话，也可以加入同一个群聊。','Start with one of 108 role presets, then add your goals and ways of working. Each assistant has an identity, a model, and an ongoing conversation, and can join a shared room.'),note:t('108 指角色预设数量，不是已接入的外部服务。群聊按明确角色顺序协作，不宣称自治并行团队。','108 counts role presets, not integrated external services. Group conversations use explicit sequential roles, not an autonomous parallel team.'),status:t('已实现','Implemented'),action:t('发现合适的专家','Discover experts'),target:'agents',steps:[t('选择职责','Choose a role'),t('加入个人背景','Add your context'),t('一起协作','Work as a team')]},
  {id:'projects',label:t('项目与实际执行','Projects and execution'),title:t('在真正的工作目录里，把事情做完','Work inside a real project'),description:t('把会话关联到本地项目，自选模型并提供密钥，使用 Codex Harness 执行工具、处理审批和保存成果。需要补充时停下来，结束后保留消息、过程与实际文件。','Connect a conversation to a local project with your chosen model and key. The Codex Harness runs tools, handles approvals, and captures artifacts. Pause for input and retain the conversation, activity, and actual files.'),note:t('普通回复不强制造文件。远程仓库目前只是引用，云执行器尚未接入；真实提供方的工具能力需要逐连接验证。','Ordinary replies do not force file creation. Remote repositories are references only; cloud execution is not connected. Tool compatibility needs per-connection validation.'),status:t('本机执行','Local execution'),action:t('打开项目','Open projects'),target:'projects',steps:[t('选项目与目标','Project and goal'),t('查看过程与审批','Activity and approval'),t('审阅实际成果','Review actual files')]},
  {id:'world',label:t('走入现实世界','Into the real world'),title:t('从一个场景，走到一项可确认的行动','From a situation to an action you can review'),description:t('二维码可以成为场所或物品的入口。工具与账户 Dev 演示每位助理的电脑、邮箱、电话和钱包，以及餐厅菜单、预算和逐次批准。','A QR code can be an entry to a place or object. Tools and accounts Dev demonstrates an assistant’s computer, email, phone, and wallet, with restaurant menus, budgets, and action-by-action approval.'),note:t('账户与餐厅流程均为虚构演示，没有发信、拨号、商家请求或支付。真实服务、身份与授权体系列入开发计划。','Accounts and restaurant flows are fictional demos: no email, calls, merchant requests, or payments. Live services, identities, and grants are planned.'),status:'Dev',action:t('查看助理工具入口','Explore assistant resources'),target:'agents',steps:[t('识别场景','Identify the situation'),t('查看准确内容','Review exact details'),t('批准演示动作','Approve the demo')]},
  {id:'history',label:t('能力地图与进展','Capabilities and progress'),title:t('每一步进展，都有可核对的记录','Progress you can inspect'),description:t('从首个可运行桌面，到统一组件体系，再到这一轮认知、专家、模型和现实场景。保留用户反馈、设计取舍、失败和修复证据。','From the first working desktop to a shared UI system, then cognition, experts, model connections, and real-world scenarios. Keep the feedback, decisions, failures, and fixes visible.'),note:t('两次已提交基线之后，本轮仍在开发与分项验收。实现、测试、实屏和用户验收分别记录，不把规划当作已经完成。','After two committed baselines, this iteration remains in development and scoped verification. Implementation, tests, UI checks, and user acceptance are recorded separately.'),status:t('持续建设','In development'),action:t('查看开发进度','View development progress'),target:'development',steps:[t('首个桌面','First desktop'),t('统一设计体系','Shared design system'),t('本轮持续迭代','Current iteration')]},
];
  const concise:Record<GuideChapterId,{label:string;title:string;description:string;steps:string[]}> = {
    vision:{label:t('认识 Hither','Meet Hither'),title:t('想做什么，告诉 Hither','Tell Hither what you want to do'),description:t('从你的习惯和正在做的事出发，理清下一步，一起把事情做完。','Bring your habits and current plans into the conversation. Find a next step and work through it together.'),steps:[t('说说想法','Share an idea'),t('结合你的情况','Use your context'),t('一起完成','Make it happen')]},
    cognition:{label:t('让它了解你','Help it know you'),title:t('让 Hither 越来越懂你','Help Hither understand you'),description:t('经历、习惯和在意的人，都有迹可循。理解有偏差时，随时改正。','Connect your experiences, habits, and people. Inspect where an understanding came from and correct it anytime.'),steps:[t('看看它的理解','See your profile'),t('查看来历','See the source'),t('改得更准确','Make a correction')]},
    life:{label:t('照顾工作与生活','Work and life'),title:t('忙眼前，也顾得上生活','Make room for work and life'),description:t('记住想做的事，也留意重要的人。让例行整理按你设定的时间发生。','Keep your plans and important people in view. Schedule regular reviews at a time you choose.'),steps:[t('看看这一周','View your week'),t('安排一次整理','Set a review'),t('留出生活的时间','Make room for life')]},
    experts:{label:t('找个懂行的帮手','Find an expert'),title:t('找一位懂行的帮手','Bring in the right help'),description:t('找专家聊一个问题，或让几位助理一起帮忙。你的背景不用从头再讲。','Talk through a problem with an expert, or bring several assistants together with your context already there.'),steps:[t('选一位专家','Choose an expert'),t('一起讨论','Work together'),t('收到完整建议','Get a useful answer')]},
    projects:{label:t('一起做项目','Work on a project'),title:t('带着助理，一起做项目','Work on a project together'),description:t('打开一个本地项目，边讨论边修改文件，最后直接检查成果。','Open a local project, discuss the work, edit files, and inspect the result.'),steps:[t('打开项目','Open a project'),t('确认本次修改','Review the change'),t('查看成果','Inspect the result')]},
    world:{label:t('走进现实场景','Out in the world'),title:t('到一个地方，就能开始','Start where you are'),description:t('试着扫一家餐厅：看菜单、选好菜，再确认这次要做什么。','Try a restaurant scenario: read the menu, choose a meal, and review the action before proceeding.'),steps:[t('看菜单','View the menu'),t('核对菜品与价格','Check the order'),t('确认这一次','Confirm this order')]},
    devices:{label:t('随身 Hither','Hither with you'),title:t('走到哪儿，都能接着做','Pick up where you left off'),description:t('在外面随口记下，回桌面继续整理，离开电脑也能看一眼结果。','Capture a thought outside, continue at your desk, and review it away from your computer.'),steps:[t('现场记下','Capture outside'),t('桌面整理','Edit at your desk'),t('手机确认','Review on your phone')]},
    history:{label:t('开始体验','Start exploring'),title:t('从你眼前的一件事开始','Start with something on your mind'),description:t('聊聊想法、整理个人资料，或打开一个项目。按自己的节奏试试。','Talk through an idea, organize your personal context, or open a project. Explore at your own pace.'),steps:[t('聊聊想法','Start a conversation'),t('整理资料','Add your context'),t('打开项目','Open a project')]},
  };
  return (['vision','cognition','life','experts','projects','world','devices','history'] as GuideChapterId[]).map(id=>{const chapter=chapters.find(item=>item.id===id)!;return {...chapter,detail:chapter.description,...concise[id],...(id==='history'?{action:t('开始一段对话','Start a conversation'),target:'assistant'}:{}),...(id==='devices'?{action:t('亲自试一遍','Try the walkthrough')}:{}),...(id==='life'?{action:t('安排例行整理','Set up a routine')}:{}),...(id==='world'?{action:t('试试现实场景','Try a real-world scenario')}:{})};});
}
