// Served from the isolated capability origin. No owner UI, cookies, storage,
// remote assets or application API are available in this document.
export function delegationPage(nonce) {
  return String.raw`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SecondU 受限分身</title>
<style nonce="${nonce}">
:root{color-scheme:light dark;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#202020;background:#f8f8f7;font-size:14px}*{box-sizing:border-box}body{margin:0}main{max-width:760px;margin:0 auto;padding:48px 24px 72px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;padding-bottom:24px;border-bottom:1px solid #dededc}.brand{font-weight:600;letter-spacing:-.3px}header small{color:#777}h1{font-size:28px;font-weight:550;line-height:1.25;letter-spacing:-.7px;margin:30px 0 12px}p{line-height:1.75;white-space:pre-wrap;margin:0 0 16px}#description{color:#666}.scope{padding:18px 0;border-top:1px solid #dededc;border-bottom:1px solid #dededc;margin:24px 0}.scope h2,h2{font-size:14px;font-weight:600;margin:0 0 12px}.scope p{font-size:14px;margin:0 0 8px}#limits{font-size:13px;color:#777}label{display:grid;gap:9px;margin:20px 0 14px;font-weight:550}input,select,textarea{font:inherit;color:inherit;background:#fff;border:1px solid #d4d4d2;border-radius:10px;padding:11px 12px}textarea{resize:vertical;min-height:130px;font-weight:400}button{border:0;border-radius:24px;padding:11px 18px;font:inherit;font-weight:550;cursor:pointer;background:#202020;color:#fff}button:disabled{opacity:.4;cursor:not-allowed}.subtle{background:transparent;color:inherit;border:1px solid #d4d4d2;padding:8px 13px}.actions,.section-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.actions small{font-size:13px;color:#777}.section-heading{margin:38px 0 16px}.section-heading h2{margin:0}#error{color:#b42318;line-height:1.6;margin:14px 0;white-space:pre-wrap}article{padding:20px 0;border-top:1px solid #dededc}article .task-head{display:flex;justify-content:space-between;gap:14px;font-size:13px;color:#777;margin-bottom:12px}article p{font-size:14px}article .result{padding:15px 17px;border-radius:12px;background:#eee;}article button{font-size:14px}.empty{color:#777;font-size:14px}footer{margin-top:32px;font-size:13px;color:#777;line-height:1.7}a{color:inherit}#locale{font-size:13px} [hidden]{display:none!important}@media(max-width:480px){main{padding:24px 20px 48px}h1{font-size:25px}.actions{align-items:flex-start;flex-direction:column}.actions button{width:100%}}@media(prefers-color-scheme:dark){:root{background:#191919;color:#eee}header,.scope,article{border-color:#373737}input,select,textarea{background:#222;border-color:#484848}button{background:#eee;color:#171717}.subtle{color:#eee;border-color:#484848}article .result{background:#292929}#description,#limits,.actions small,.empty,footer,header small,article .task-head{color:#aaa}#error{color:#ffaaa0}}
</style><main><header><span class="brand">SecondU</span><div><small id="device"></small> <button class="subtle" id="locale">English</button></div></header>
<h1 id="name">受限分身</h1><p id="description"></p><section class="scope"><h2 id="scope-title"></h2><p id="rules"></p><p id="limits"></p></section>
<form id="request-form"><label><span id="purpose-label"></span><select id="purpose"></select></label><label><span id="input-label"></span><textarea id="input" required></textarea></label><div class="actions"><small id="approval"></small><button id="send" disabled></button></div></form><p id="error" role="alert"></p>
<div class="section-heading"><h2 id="requests-title"></h2><button id="refresh" class="subtle"></button></div><section id="tasks"></section><footer id="boundary"></footer></main>
<script nonce="${nonce}">
'use strict';
let en=navigator.language.startsWith('en'),token=new URLSearchParams(location.hash.slice(1)).get('access'),info,busy=false,authorized=false;
const shareId=location.pathname.split('/')[2],$=id=>document.getElementById(id),t=(zh,english)=>en?english:zh;
history.replaceState(null,'',location.pathname);
// Opening a new grant in this same tab changes only the fragment. Reload so
// pending requests and in-memory authorization from the previous grant end.
addEventListener('hashchange',()=>{if(new URLSearchParams(location.hash.slice(1)).has('access'))location.reload();});
const labels={consultation:['咨询建议','Consultation'],collaboration:['协作提案','Collaboration proposal'],matching:['匹配建议','Matching suggestion'],transaction:['交易意向','Transaction inquiry']};
const states={TASK_STATE_SUBMITTED:['等待审批','Awaiting approval'],TASK_STATE_AUTH_REQUIRED:['等待本人审批','Awaiting owner approval'],TASK_STATE_WORKING:['处理中','Working'],TASK_STATE_COMPLETED:['已完成','Completed'],TASK_STATE_FAILED:['未完成','Failed'],TASK_STATE_REJECTED:['未批准','Declined'],TASK_STATE_CANCELED:['已取消','Canceled']};
function render(){document.documentElement.lang=en?'en':'zh-CN';document.title=t('SecondU 受限分身','SecondU limited delegate');$('locale').textContent=en?'中文':'English';$('device').textContent=t('仅限这台设备','This device only');$('scope-title').textContent=t('服务范围','Service scope');$('purpose-label').textContent=t('本次用途','Purpose');$('input-label').textContent=t('你希望获得什么帮助','What would you like help with?');$('input').placeholder=t('描述问题、约束与期待的结果。','Describe your question, constraints and desired result.');$('send').textContent=t('提交请求','Send request');$('requests-title').textContent=t('本授权的请求','Requests under this grant');$('refresh').textContent=t('刷新','Refresh');$('boundary').textContent=t('当前提供文本建议和提案。不会代你联系他人、付款、签约或执行外部操作。链接仅能在运行 SecondU 的这台设备上使用。','This delegate provides text advice and proposals. It cannot contact people, pay, enter agreements or perform external actions. This link works only on the device running SecondU.');if(info){$('name').textContent=info.name;$('description').textContent=info.description;$('rules').textContent=info.serviceRules;$('limits').textContent=t('版本 '+info.version+'，剩余 '+info.remainingCalls+' 次，有效至 ','Version '+info.version+', '+info.remainingCalls+' calls remaining, expires ')+new Date(info.expiresAt).toLocaleString();$('approval').textContent=info.approvalPolicy==='every_call'?t('每次请求须经本人审批。','Each request needs the owner’s approval.'):t('本人已允许按此范围自动回答。','The owner allows automatic replies within this scope.');$('input').maxLength=info.maxInputChars;const selected=$('purpose').value;$('purpose').replaceChildren(...info.purposes.map(p=>{const option=document.createElement('option');option.value=p;option.textContent=labels[p][en?1:0];return option;}));if(info.purposes.includes(selected))$('purpose').value=selected;}$('send').disabled=!authorized||!info?.allowCalls||info.remainingCalls<=0||busy;}
async function request(path,body){if(!token)throw new Error(t('授权链接缺失，请使用本人提供的完整链接重新打开。','Open the complete access link supplied by the owner.'));const response=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json','A2A-Version':'1.0'}:{})},...(body?{body:JSON.stringify(body)}:{}),credentials:'omit',cache:'no-store'});const value=await response.json();if(!response.ok){if(response.status===401||response.status===403){authorized=false;token=null;render();}throw new Error(value.error||t('请求未完成。','Request failed.'));}if(value.error)throw new Error(value.error.message||value.error);return value;}
async function rpc(method,params){return (await request('/a2a/'+shareId,{jsonrpc:'2.0',id:crypto.randomUUID(),method,params})).result;}
function showTasks(tasks){$('tasks').replaceChildren();if(!tasks.length){const p=document.createElement('p');p.className='empty';p.textContent=t('还没有请求。','No requests yet.');$('tasks').append(p);}for(const task of tasks){const article=document.createElement('article'),head=document.createElement('div'),state=document.createElement('span'),date=document.createElement('span');head.className='task-head';state.textContent=(states[task.status.state]||[task.status.state,task.status.state])[en?1:0];date.textContent=new Date(task.status.timestamp).toLocaleString();head.append(state,date);article.append(head);const input=document.createElement('p');input.textContent=task.history?.[0]?.parts?.[0]?.text||'';article.append(input);const result=document.createElement('p');result.className='result';result.textContent=task.artifacts?.flatMap(a=>a.parts?.map(p=>p.text||'')).join('\n')||task.status.message?.parts?.map(p=>p.text||'').join('\n')||'';article.append(result);if(!['TASK_STATE_COMPLETED','TASK_STATE_FAILED','TASK_STATE_CANCELED','TASK_STATE_REJECTED'].includes(task.status.state)){const cancel=document.createElement('button');cancel.className='subtle';cancel.textContent=t('取消请求','Cancel request');cancel.onclick=async()=>{try{await rpc('CancelTask',{id:task.id});await refresh();}catch(error){$('error').textContent=error.message;}};article.append(cancel);}$('tasks').append(article);}}
async function refresh(){if(!token)return;try{info=await request('/share/'+shareId+'/info');authorized=true;const result=await rpc('ListTasks',{pageSize:100,includeArtifacts:true});showTasks(result.tasks);render();}catch(error){$('error').textContent=error.message;}}
$('request-form').onsubmit=async event=>{event.preventDefault();if(busy||!authorized)return;busy=true;render();$('error').textContent='';try{await rpc('SendMessage',{message:{messageId:crypto.randomUUID(),role:'ROLE_USER',parts:[{text:$('input').value}]},metadata:{purpose:$('purpose').value},configuration:{returnImmediately:true,acceptedOutputModes:['text/plain']}});$('input').value='';await refresh();}catch(error){$('error').textContent=error.message;}finally{busy=false;render();}};
$('refresh').onclick=()=>void refresh();$('locale').onclick=()=>{en=!en;render();void refresh();};render();if(token)void refresh();else $('error').textContent=t('请使用包含授权的完整链接打开。刷新后需重新打开原链接。','Open the complete access link. After a page reload, reopen the original link.');setInterval(()=>{if(authorized&&!busy&&document.visibilityState==='visible')void refresh();},2500);
</script></html>`;
}
