import { Camera, Check, Desktop, Document, Glasses, Mic, Mobile } from '@openai/apps-sdk-ui/components/Icon';
import { HitherMark } from '../HitherMark';
import { HitherWordmark } from '../HitherWordmark';
import { t } from '../i18n';
import { MotionAppear, MotionWrite } from './filmMotion';
import './guideDevicesFilm.css';

const Appear = MotionAppear;
const taskTitle = () => t('桌面工作台内测', 'Desktop workspace pilot');
function Brand() { return <span className="device-film-brand"><HitherMark /><HitherWordmark /></span>; }
function SourceStrip() { return <div className="device-film-source-strip"><span><Mic />{t('现场语音', 'Voice note')}</span><span><Camera />{t('现场图像', 'Scene image')}</span><small>{t('同一任务的原始记录', 'Original records for this task')}</small></div>; }
function SceneImage() { return <div className="device-film-scene-image"><img className="device-film-scene-photo" src="/art/guide-device-context-v1.png" alt={t('第一人称视角的产品测试现场：桌上有电脑、笔记本和茶杯，桌旁摆放着椅子。生成插画。', 'An illustrated first-person view of a product testing area with a laptop, notebooks, cups and chairs. Generated artwork.')} width={1448} height={1086} draggable={false}/><span className="device-film-image-caption"><Glasses />{t('眼镜中的现场', 'Through your glasses')}</span></div>; }
function GlassesShot() { return <Appear at={0} until={6100} className="device-film-field"><div className="device-film-field-heading"><Glasses /><span>{t('将现场记录加入任务', 'Add field records to a task')}</span></div><div className="device-film-field-pair"><div className="device-film-image-card"><SceneImage /></div><div className="device-film-voice-card"><div className="device-film-voice-top"><Mic /><span>{t('语音记录', 'Voice note')}</span><small>00:08</small></div><p><MotionWrite at={650} ms={2300} value={t('周五 17 点安排内测，8 名用户。请汇总访谈，准备验证流程。', 'Plan a pilot for eight users, Friday at five. Review the interviews and prepare the steps.')} /></p><div className="device-film-wave">{[12,22,15,31,40,24,35,46,28,18,32,42,25,36,18,29,39,21,15,25,13,18].map((height,i)=><i key={i} style={{height,animationDelay:`${i*-.09}s`}}/>)}</div><Appear at={3500} className="device-film-field-saved"><Check />{t('记录已保存，可在电脑继续', 'Records saved; continue on your computer')}</Appear></div></div></Appear>; }
function DesktopShot({time}:{time:number}) { const changed=time>=9600; return <Appear at={6500} className={`device-film-desktop ${time>=13300?'is-behind-phone':''}`}><div className="device-film-windowbar"><span><i/><i/><i/></span><Desktop />{taskTitle()}</div><div className="device-film-desktop-body"><aside><Brand /><h3>{taskTitle()}</h3><p>{t('语音、图像与成果保留在同一任务。', 'Voice, images and results stay in the same task.')}</p><SourceStrip /><div className="device-film-note"><Mic /><p>{t('“周五 17 点安排内测，8 名用户。”', '“A pilot for eight users, Friday at five.”')}</p></div><div className="device-film-result"><Document /><span>{t('内测验证方案.md', 'Pilot validation plan.md')}</span><small>v{changed?'2':'1'}</small></div></aside><article><header><Document /><span>{t('内测验证方案', 'Pilot validation plan')}</span><button className="device-film-save">{changed?<Check/>:null}{changed?t('已保存', 'Saved'):t('保存', 'Save')}</button></header><div className="device-film-paper"><small>{t('周五 17:00', 'FRIDAY 5:00 PM')}</small><h2>{t('内测验证方案', 'Pilot validation plan')}</h2><p>{t('8 名参与者，聚焦保存与跨设备续接。', 'Eight participants; focus on saving and task continuity.')}</p><section><span>01</span><div><strong>{t('操作验证', 'Validate the workflow')}</strong><p>{t('完成任务、编辑保存、核对版本。', 'Complete a task, edit, save and check the version.')}</p></div><small>20 min</small></section><section className={changed?'is-edited':''}><span>02</span><div><strong>{t('问题复盘', 'Review issues')}</strong><p>{t('记录异常步骤、复现条件与影响。', 'Record failures, reproduction steps and impact.')}</p></div><small className="device-film-edit-time">{changed?'20':'10'} min</small></section><Appear at={11400} className="device-film-ready"><Check />{t('已保存第 2 版，可在手机继续确认', 'Version 2 saved; continue the review on your phone')}</Appear></div></article></div></Appear>; }
function PhoneShot({time}:{time:number}) { const confirmed=time>=15900; return <Appear at={13300} className="device-film-phone-shot"><div className="device-film-phone"><div className="device-film-phone-status"><span>17:08</span><i/></div><header><HitherMark/><span>SecondU</span></header><small className="device-film-phone-eyebrow">{t('继续同一任务', 'CONTINUE THE SAME TASK')}</small><h2>{taskTitle()}</h2><SourceStrip/><div className="device-film-phone-document"><Document/><strong>{t('内测验证方案', 'Pilot validation plan')}</strong><span>v2</span><p>{t('操作验证', 'Workflow check')}<b>20 min</b></p><p className="is-current">{t('问题复盘', 'Issue review')}<b>20 min</b></p><small>{t('来自电脑上保存的最新版本', 'The latest version saved on your computer')}</small></div><button className={`device-film-confirm ${confirmed?'is-confirmed':''}`}>{confirmed?<Check/>:<Mobile/>}{confirmed?t('已确认', 'Approved'):t('确认第 2 版', 'Approve version 2')}</button><p className="device-film-phone-footnote">{confirmed?t('确认状态已同步至任务', 'Review status synced to the task'):t('核对内容与版本后确认', 'Check the content and version before approving')}</p></div></Appear>; }
export function GuideDevicesFilm({time}:{time:number}) { return <><GlassesShot/><DesktopShot time={time}/><PhoneShot time={time}/></>; }
