import {useRef,type CSSProperties,type ReactNode} from 'react';
import {FilmMotionProvider,MotionAppear,MotionWrite,MotionPointer,NativeFilmMotion,useFilmDriver,type FilmMove,type FilmPointerStep} from './filmMotion';
import {Button} from '@openai/apps-sdk-ui/components/Button';
import {ArrowUp,ArrowRight,Check,CheckCircle,Document,Folder,Mic,Search,Terminal,User,Calendar,Edit,Plus} from '@openai/apps-sdk-ui/components/Icon';
import {HitherMark} from '../HitherMark';
import {AgentAvatar} from '../agents/AgentIdentity';
import {t} from '../i18n';
import type {GuideChapterId} from './guideContent';
import './guideFilms.css';

const durations:Record<GuideChapterId,number>={vision:18000,cognition:17500,life:16500,experts:19000,projects:18500,world:16500,devices:19000,history:15500};
const bound=(n:number)=>Math.max(0,Math.min(1,n));
const ease=(n:number)=>1-Math.pow(1-bound(n),4);
const progress=(time:number,start:number,duration=650)=>ease((time-start)/duration);
function Appear({time:_time,...props}:{time:number;at:number;until?:number;children:ReactNode;className?:string;style?:CSSProperties}){return <MotionAppear {...props}/>;}
function Write({time:_time,...props}:{value:string;time:number;at:number;ms?:number}){return <MotionWrite {...props}/>;}
function Topbar({children,right}:{children:ReactNode;right?:ReactNode}){return <div className="film-topbar"><HitherMark/><span>{children}</span><small>{right}</small></div>;}
const expertNames=()=>[t('苏青','Su Qing'),t('陆川','Lu Chuan'),t('阿乔','A Qiao'),t('牧野','Mu Ye')];
function Person({n,size=28}:{n:number;size?:number}){return <AgentAvatar agent={{id:['film-qing','film-chuan','film-qiao','film-mu'][n],name:expertNames()[n],avatarStyle:'notionists'}} size={size}/>;}
function Row({children,check=false}:{children:ReactNode;check?:boolean}){return <div className="film-check-row"><span>{check?<Check/>:<i/>}</span>{children}</div>;}
function DocumentPage({time,at,title=t('周五前，完成一轮内测','A pilot before Friday'),editAt}:{time:number;at:number;title?:string;editAt?:number}){return <article className="film-document-page"><small>SecondU / {t('工作计划','WORK PLAN')}</small><h4><Write value={title} time={time} at={at} ms={700}/></h4><Appear time={time} at={at+650}><p className="film-doc-intro">{t('把最重要的事情做好，也为生活留出时间。','Make progress on what matters, with room for life.')}</p></Appear>{[{n:'01',title:t('周三，完整试跑','Wednesday, Try'),body:t('邀请三位体验者，从一句请求走到拿到清单。','Invite three people. Go from a request to a usable checklist.')},{n:'02',title:t('周四，修掉卡点','Thursday, Refine'),body:t('记录中断的位置，修正后重新走一遍。','Capture the interruptions, fix the friction, and try again.')},{n:'03',title:t('周五，收尾与反馈','Friday, Review'),body:t('整理反馈，决定下一步。周末留给家人。','Collect feedback and decide the next step. Keep the weekend for family.')}].map((row,i)=><Appear key={i} time={time} at={at+1400+i*850} className="film-doc-section"><span>{row.n}</span><div><h5><span style={i===0&&editAt&&time>editAt&&time<editAt+1000?{background:"#dce6fa"}:undefined}>{i===0&&editAt&&time>editAt+1000?t('周三 15:00，完整试跑','Wednesday 15:00, Try'):row.title}</span></h5><p><Write value={row.body} time={time} at={at+1500+i*850} ms={650}/></p></div></Appear>)}</article>;}

function ConversationFilm({time}:{time:number}){
 const move=progress(time,3900,1200),document=progress(time,7200,1100),edited=time>14600;
 return <><div className="film-conversation-camera" style={{transform:`translateY(${(1-move)*48}px)`}}><div className="film-entry-wordmark" style={{opacity:1-move,transform:`translateY(${-move*25}px)`}}><HitherMark/><h4>{t('一起，把事情做好。','Make it happen, together.')}</h4></div><div className="film-conversation-screen" style={{opacity:move}}><Topbar right={t('个人助理','Personal assistant')}>{t('这周先做什么','What to focus on this week')}</Topbar></div><div className="film-request-orbit" style={{left:`${24-move*20}%`,top:`${37-move*20}%`,width:`${52-move*11}%`}}><span><Write value={t('这周事情有点多。帮我看看先做什么，周末还想和家人见面。','There is a lot on this week. Help me choose what comes first, with time for family this weekend.')} time={time} at={600} ms={2400}/></span><Button size="sm" color="primary" uniform><ArrowUp/></Button></div><div className="film-conversation-reply" style={{opacity:move}}><Appear time={time} at={4600}><div className="film-author"><HitherMark/>SecondU</div><p><Write value={t('先把工作台的一次内测做完整。它贴近你的产品目标，也能在周五前收尾。','Finish one workbench pilot. It serves your product goal and can be wrapped up before Friday.')} time={time} at={5100} ms={1800}/></p></Appear><Appear time={time} at={6400} className="film-source-tags"><span>{t('产品目标','Product goal')}</span><span>{t('做事习惯','Working style')}</span><span>{t('周末安排','Weekend plans')}</span></Appear><Appear time={time} at={10800} className="film-result-link"><Document/><div>{t('本周内测计划','This week’s pilot plan')}<small>{t('已整理，可继续编辑','Ready to edit')}</small></div><ArrowRight/></Appear></div><div className="film-plan-workspace" style={{opacity:document,transform:`translateX(${(1-document)*70}px)`,width:'49%'}}><div className="film-editor-toolbar"><Document/>{t('本周内测计划','This week’s pilot plan')}<span>{edited?'v2':'v1'}</span><button className="film-editor-save">{edited?<Check/>:<Document/>}{edited?t('已保存','Saved'):t('保存','Save')}</button></div><DocumentPage time={time} at={8000} editAt={12900}/></div></div></>;
}
function CognitionFilm({time}:{time:number}){const drawer=progress(time,4300,850),correction=time>9400;return <><div className="film-profile-app"><Topbar>{t('自我认识','Your profile')}</Topbar><section className="film-profile-surface" style={{paddingRight:`${5+drawer*43}%`}}><div className="film-profile-person"><span>{t('万','C')}</span><div><h4>{t('万叶','Caspian')}</h4><p>{t('月之暗面，Kimi 产品工程师','Moonshot AI, Kimi product engineer')}</p></div></div><nav><strong>{t('当前理解','Current understanding')}</strong><span>{t('已确认','Confirmed')}</span><span>{t('待确认','To review')}</span></nav><div className={`film-profile-line ${time>3500?'is-selected':''}`}><small>{t('表达习惯','Communication')}</small><p>{time>13300?t('先把关键流程跑通；重要判断说明依据。','Try the core flow first; give evidence for important decisions.'):t('做事前喜欢先看一份完整计划。','Likes to see a complete plan before acting.')}</p><ArrowRight/></div><div className="film-profile-line"><small>{t('工作习惯','Working style')}</small><p>{t('先把关键流程做通，再增加功能。','Validate the core journey before adding features.')}</p></div><div className="film-profile-line"><small>{t('最近在意','Current focus')}</small><p>{t('做好工作，也顾得上家人。','Do good work and make room for family.')}</p></div><Appear time={time} at={13600} className="film-version-note"><CheckCircle/>{t('已更新，原来的版本仍然保留','Updated, The previous version is still available')}</Appear></section><aside className="film-evidence-drawer" style={{transform:`translateX(${(1-drawer)*105}%)`}}><header><Document/><strong>{t('这条理解的来历','Where this came from')}</strong></header><small>{t('周二的对话，14:32','Tuesday’s conversation, 14:32')}</small><blockquote>{t('“先让我试完整个流程，再讨论要加什么。关键判断要有依据。”','“Let me try the whole flow before adding features. Show the evidence for key decisions.”')}</blockquote><div className="film-inline-edit" style={{opacity:progress(time,7000)}}><label>{t('补充这条理解','Add more detail')}</label><div><Write value={t('先把关键流程跑通；重要判断说明依据。','Try the core flow first; give evidence for important decisions.')} time={time} at={8200} ms={2500}/></div><Button size="sm" color="primary">{correction&&time>13300?<Check/>:<Edit/>}{time>13300?t('已保存修正','Correction saved'):t('保存修正','Save correction')}</Button></div></aside></div></>;}
function LifeFilm({time}:{time:number}){const arranged=time>8300;return <><div className="film-life-page"><Topbar right={t('已结合个人背景','Using personal context')}>{t('当前生活','Life now')}</Topbar><div className="film-life-heading"><div><small>{t('本周','THIS WEEK')}</small><h4>{t('按你的节奏，安排这一周。','Plan the week around your rhythm.')}</h4></div><Calendar/></div><div className="film-calendar">{[t('周一','MON'),t('周二','TUE'),t('周三','WED'),t('周四','THU'),t('周五','FRI'),t('周六','SAT'),t('周日','SUN')].map((d,i)=><div key={i} className={i>4?'is-weekend':''}><header><small>{d}</small><strong>{[28,29,30,1,2,3,4][i]}</strong></header></div>)}<div className="film-calendar-block film-block-work"><small>09:00 — 11:00</small><strong>{t('工作台内测','Workbench pilot')}</strong><span>{t('上午两小时不排会','Two meeting-free hours')}</span></div><div className="film-calendar-block film-block-mentor"><small>{t('周三，15:00','WED, 15:00')}</small><strong>{t('和乔宁看内测反馈','Review feedback with Qiao Ning')}</strong></div><div className="film-calendar-block film-block-family"><small>{t('周六','SATURDAY')}</small><strong>{t('和家人见面','See family')}</strong></div><Appear time={time} at={8400} className="film-calendar-block film-block-review"><small>{t('周五，17:00','FRI, 17:00')}</small><strong>{t('整理本周进展','Review the week')}</strong><CheckCircle/></Appear></div><Appear time={time} at={2300} until={9300} className="film-routine-popover"><div className="film-author"><HitherMark/>SecondU</div><p><Write value={t('你习惯上午专注，也想给家人留出周末。把每周整理放在周五 17:00？','You keep mornings for focus and weekends for family. Schedule the weekly review for Friday at 17:00?')} time={time} at={2800} ms={1800}/></p><div className="film-routine-time"><Calendar/><span>{t('每周五','Every Friday')}</span><strong>17:00</strong></div><Button size="sm" color="primary">{arranged?<Check/>:<ArrowRight/>}{arranged?t('已安排','Scheduled'):t('就这个时间','Use this time')}</Button></Appear><Appear time={time} at={10100} className="film-life-footer"><CheckCircle/><span>{t('已安排周五整理，周末留给生活。','Friday review scheduled. The weekend is yours.')}</span></Appear></div></>;}
function ExpertsFilm({time}:{time:number}){const group=progress(time,5500,1200);return <><div className="film-experts-directory" style={{opacity:1-group,transform:`translateX(${-group*120}px)`}}><Topbar>{t('找个懂行的帮手','Find an expert')}</Topbar><div className="film-expert-search"><Search/><span><Write value={t('准备一次产品内测','Prepare a product pilot')} time={time} at={500} ms={1500}/></span></div><div className="film-expert-roster">{[t('产品筹划','Product planner'),t('质量复核','Quality reviewer'),t('文字整理','Writer')].map((r,i)=><div key={i} className={time>2800+i*500?'is-chosen':''}><Person n={i} size={68}/><h4>{expertNames()[i]}</h4><p>{r}</p><span>{time>2800+i*500?<><Check/>{t('加入会话','Added to chat')}</>:t('一起聊聊','Start a chat')}</span></div>)}</div><Appear time={time} at={3800} className="film-create-team"><Button size="md" color="primary">{t('和这三位一起聊','Chat with all three')}<ArrowRight/></Button></Appear></div><div className="film-expert-group" style={{opacity:group,transform:`translateX(${(1-group)*120}px)`}}><Topbar right={t('3 位成员','3 members')}>{t('周五内测筹备','Friday pilot planning')}</Topbar><div className="film-group-members">{[0,1,2].map(n=><span key={n}><Person n={n} size={22}/>{expertNames()[n]}</span>)}</div><div className="film-group-viewport"><div className="film-group-chat"><Appear time={time} at={6100} className="film-group-request">{t('清单控制在一页，重点看新用户能不能走完。','Keep the checklist to one page. Focus on whether new users can complete the journey.')}</Appear>{[t('先做三人的小内测，把“走到结果”作为重点。','Start with three people and focus on reaching a useful result.'),t('我补两项检查：中断发生在哪里，最后拿到什么。','Check where interruptions happen and what each person ends up with.'),t('整理好了，现场直接照着这张清单走。','Ready. Follow this checklist during the session.')].map((v,i)=><Appear key={i} time={time} at={7200+i*2100} className="film-group-message"><Person n={i}/><div><strong>{expertNames()[i]}</strong><p><Write value={v} time={time} at={7600+i*2100} ms={1200}/></p>{i===2&&<Appear time={time} at={12000} className="film-group-file"><Document/><span>{t('内测现场清单.md','Pilot checklist.md')}<small>{t('准备，试跑，反馈','Prepare, Try, Feedback')}</small></span><ArrowRight/></Appear>}</div></Appear>)}</div></div></div></>;}
function ProjectFilm({time}:{time:number}){const output=progress(time,10200,1100);return <><div className="film-project-desktop"><Topbar right={t('本地项目','Local project')}>{t('Kimi 工作台内测','Kimi workspace pilot')}</Topbar><aside className="film-project-tree"><strong><Folder/>{t('Kimi 工作台','Kimi workspace')}</strong><span><Document/>README.md</span><span><Folder/>notes</span><span className={time>11400?'is-selected':''}><Document/>checklist.md</span></aside><section className="film-project-console" style={{right:`${output*46}%`}}><div className="film-console-request"><Write value={t('看看项目记录，整理一份现场清单。','Review the project notes and prepare a pilot checklist.')} time={time} at={500} ms={1500}/></div><Appear time={time} at={2600} className="film-tool-call"><Terminal/><span>{t('查看项目记录','Read project notes')}<small>README.md, notes/</small></span><Check/></Appear><Appear time={time} at={4300} className="film-tool-call"><Document/><span>{t('整理清单','Prepare checklist')}<small>{t('准备、试跑与反馈','Prepare, try, and gather feedback')}</small></span>{time>6500&&<Check/>}</Appear><Appear time={time} at={6200} className="film-project-approval"><strong>{t('保存这次修改？','Save this change?')}</strong><span>notes/checklist.md</span><p>{t('一份新文件，包含三项准备和三个现场检查。','One new file with preparation and on-site checks.')}</p><Button size="sm" color="primary">{time>9600?<Check/>:<ArrowRight/>}{time>9600?t('已确认','Approved'):t('确认并保存','Approve and save')}</Button></Appear><Appear time={time} at={11600} className="film-project-written"><CheckCircle/>{t('checklist.md 已保存','checklist.md saved')}</Appear></section><div className="film-project-output" style={{opacity:output,transform:`translateX(${(1-output)*80}px)`}}><div className="film-editor-toolbar"><Document/>checklist.md<span>v1</span></div><DocumentPage time={time} at={10900} title={t('内测现场清单','Pilot checklist')}/></div></div></>;}
function WorldFilm({time}:{time:number}){
 const ready=time>8300,reviewed=time>12900;
 return <div className="film-share-workspace"><Topbar>{t('万叶的产品评审分身','Caspian’s product reviewer')}</Topbar>
  <section className="film-capability-card"><div className="film-share-person"><span>{t('万','C')}</span><div><h4>{t('产品方案评审','Product review')}</h4><small>{t('万叶，产品工程师','Caspian, Product engineer')}</small></div></div><p>{t('从真实任务出发，检查目标、交互与交付是否接得上。','Review how the goal, interaction, and delivery connect in a real task.')}</p><div className="film-share-method"><small>{t('可以提供','CAN HELP WITH')}</small><Row check>{t('找出流程中的缺口','Find gaps in the flow')}</Row><Row check>{t('给出可验证的改进建议','Suggest testable improvements')}</Row></div><div className="film-share-private"><User/><span>{t('个人生活、联系人与私人聊天保持私密','Personal life, contacts, and private chats stay private')}</span></div></section>
  <section className="film-share-settings"><header><strong>{t('这次开放的范围','Scope for this share')}</strong></header><div className="film-share-source"><Document/><span><strong>{t('产品评审方法','Product review method')}</strong><small>{t('已选资料，2 份','2 selected sources')}</small></span><span className="film-share-checkbox">{time>3300?<Check/>:<i/>}</span></div><div className="film-share-caller"><User/><span>{t('允许协作的助理','Allowed collaborator')}</span><strong>{t('乔宁的助理','Qiao Ning’s assistant')}</strong></div><div className="film-share-expiry"><Calendar/><span>{t('有效期','Expires in')}</span><strong>{t('7 天','7 days')}</strong></div><p>{t('可读取已选资料，返回评审意见。','Read selected sources and return a review.')}</p><Button className="film-share-create" color="primary" size="sm">{ready?<Check/>:<ArrowRight/>}{ready?t('分享范围已设定','Scope set'):t('预览分享','Preview share')}</Button></section>
  <Appear time={time} at={9300} className="film-a2a-handoff"><div className="film-a2a-route"><span><HitherMark/>{t('乔宁的助理','Qiao’s assistant')}</span><ArrowRight/><span><User/>{t('产品评审分身','Product reviewer')}</span></div><p><Write value={t('请看这份报名流程，哪里会让用户不确定是否完成？','Review this signup flow. Where could a user be unsure whether it is complete?')} time={time} at={9900} ms={1900}/></p><div className="film-a2a-receipt"><CheckCircle/><div><strong>{reviewed?t('评审结果已返回','Review returned'):t('按所选范围协作','Working within the selected scope')}</strong><small>{reviewed?t('2 份资料，1 次调用，可随时撤回','2 sources, 1 call, Revoke anytime'):t('产品评审方法与这次提交的流程','Review method and the submitted flow')}</small></div><button className="film-a2a-review">{t('查看记录','View record')}</button></div></Appear>
 </div>;
}
function DevicesFilm({time}:{time:number}){const desktop=progress(time,5800,1200),phone=progress(time,12300,1000);return <><div className="film-voice-moment" style={{opacity:1-desktop,transform:`translateY(${-desktop*65}px)`}}><div className="film-audio-line">{Array.from({length:35},(_,i)=><i key={i} style={{height:`${8+Math.sin(i*.7)**2*40}px`,animationDelay:`${i*53}ms`}}/>)}</div><div className="film-voice-transcript"><Mic/><p><Write value={t('乔宁刚确认了三位内测用户。把准备事项加进工作台项目，回桌面继续。','Qiao Ning confirmed three pilot users. Add the preparation to the workspace project so I can continue at my desk.')} time={time} at={650} ms={2600}/></p></div><Appear time={time} at={3600}><span className="film-voice-answer">{t('记下了，回到桌面可以接着看。','Captured. Pick it up at your desk.')}</span></Appear></div><div className="film-device-desktop" style={{opacity:desktop,transform:`translateX(${-phone*90}px) scale(${1-phone*.12})`}}><Topbar>{t('Kimi 工作台内测清单','Kimi workspace pilot checklist')}</Topbar><div className="film-device-document"><DocumentPage time={time} at={6500} title={t('周五，让用户走完一个任务','Friday: complete one real task')}/></div><div className="film-desktop-stand"/></div><div className="film-mobile-device" style={{opacity:phone,transform:`translateX(${(1-phone)*80}px)`}}><div className="film-mobile-camera"/><span>9:41</span><header><HitherMark/>SecondU</header><Appear time={time} at={13100} className="film-mobile-notice"><Document/><h4>{t('内测清单准备好了','Your pilot checklist is ready')}</h4><p>{t('三项准备，一项待确认。','Three things to prepare. One to confirm.')}</p><Button size="sm" color="primary" block>{time>15900?<Check/>:<ArrowRight/>}{time>15900?t('已确认','Approved'):t('看过了，可以继续','Reviewed, continue')}</Button></Appear><Appear time={time} at={16100} className="film-mobile-complete"><CheckCircle/>{t('还是刚才那件事。','The same task, carried through.')}</Appear></div></>;}
function StartFilm({time}:{time:number}){const chosen=progress(time,3600,900);return <><div className="film-start-wall" style={{opacity:1-chosen,transform:`translateY(${-chosen*35}px)`}}><div className="film-start-greeting"><HitherMark/><h4>{t('今天，想一起做点什么？','What shall we work on today?')}</h4></div><div className="film-start-objects"><div><Document/><strong>{t('一份资料','A source')}</strong><small>{t('让我更了解你','Help me know you')}</small></div><div><Mic/><strong>{t('一个想法','An idea')}</strong><small>{t('从这里往下做','Start here')}</small></div><div><Folder/><strong>{t('一个项目','A project')}</strong><small>{t('一起推进到交付','Work toward delivery')}</small></div></div></div><div className="film-start-chat" style={{opacity:chosen,transform:`translateY(${(1-chosen)*45}px)`}}><Topbar>{t('新对话','New conversation')}</Topbar><div className="film-start-message"><span><Write value={t('国庆想回杭州陪家人。帮我把工作和回家的安排理清楚。','I want to visit my family in Hangzhou. Help me arrange work and the trip home.')} time={time} at={4200} ms={2500}/></span><Button size="sm" color="primary" uniform><ArrowUp/></Button></div><Appear time={time} at={7500} className="film-start-answer"><div className="film-author"><HitherMark/>SecondU</div><p><Write value={t('先把到家的那天留出来。工作提前收好，下午陪家人吃饭、散步。','Keep one afternoon for family. Wrap up work before you leave, then enjoy a meal and a walk together.')} time={time} at={8000} ms={1800}/></p><div className="film-trip-plan"><span>{t('国庆回杭州','HOME TO HANGZHOU')}</span><h4>{t('留一天下午。','An afternoon at home.')}</h4><div className="film-trip-stops"><span><Calendar/>{t('先定回家的日期','Pick the day')}</span><span><Document/>{t('出发前收好工作','Wrap up work')}</span><span><User/>{t('吃饭，散步，慢慢聊','Eat, walk, catch up')}</span></div><small>{t('车次待定，时间留给家人','Train to choose, Time for family')}</small></div></Appear></div></>;}

// A click always names the rendered control. Only resting positions use stage percentages.
const pointerSteps:Record<GuideChapterId,FilmPointerStep[]>={
 vision:[{at:0,position:[67,74]},{at:3100,target:'.film-request-orbit>button',click:true},{at:10500,target:'.film-plan-workspace .film-document-page>h4'},{at:12800,target:'.film-plan-workspace .film-doc-section h5 span',click:true},{at:14300,target:'.film-editor-save',click:true},{at:16500,position:[90,88]}],
 cognition:[{at:0,position:[82,85]},{at:3500,target:'.film-profile-line',click:true},{at:7800,target:'.film-inline-edit>div',click:true},{at:12900,target:'.film-inline-edit>button',click:true},{at:15000,position:[86,85]}],
 life:[{at:0,position:[82,80]},{at:5700,target:'.film-routine-time'},{at:7600,target:'.film-routine-popover>button',click:true},{at:10500,target:'.film-block-review'},{at:13000,position:[82,54]}],
 experts:[{at:0,position:[74,79]},{at:2600,target:'.film-expert-roster>div:nth-child(1)>span:last-child',click:true},{at:3200,target:'.film-expert-roster>div:nth-child(2)>span:last-child',click:true},{at:3800,target:'.film-expert-roster>div:nth-child(3)>span:last-child',click:true},{at:5100,target:'.film-create-team>button',click:true},{at:14500,target:'.film-group-file'},{at:16500,position:[85,88]}],
 projects:[{at:0,position:[83,78]},{at:3000,target:'.film-tool-call'},{at:8000,target:'.film-project-approval>button'},{at:9400,target:'.film-project-approval>button',click:true},{at:12200,target:'.film-project-output .film-document-page>h4'},{at:17000,position:[88,87]}],
 world:[{at:0,position:[88,87]},{at:3300,target:'.film-share-checkbox',click:true},{at:4800,target:'.film-share-caller'},{at:6500,target:'.film-share-expiry'},{at:8100,target:'.film-share-create',click:true},{at:13700,target:'.film-a2a-review',click:true},{at:15000,position:[89,90]}],
 devices:[{at:0,position:[90,88]},{at:10700,target:'.film-device-document .film-document-page>h4'},{at:14400,target:'.film-mobile-notice>button'},{at:15800,target:'.film-mobile-notice>button',click:true},{at:17400,position:[92,83]}],
 history:[{at:0,position:[84,87]},{at:2900,target:'.film-start-objects>div:nth-child(2)',click:true},{at:7000,target:'.film-start-message>button',click:true},{at:11700,target:'.film-trip-plan'},{at:13800,position:[88,86]}]
};

const movements:Record<GuideChapterId,FilmMove[]>={
 vision:[
 {selector:'.film-conversation-camera',at:3900,duration:1200,from:{transform:'translateY(48px)'},to:{transform:'translateY(0px)'}},
 {selector:'.film-entry-wordmark',at:3900,duration:700,from:{opacity:1,transform:'translateY(0px)'},to:{opacity:0,transform:'translateY(-25px)'}},
 {selector:'.film-conversation-screen',at:3900,duration:900,from:{opacity:0},to:{opacity:1}},
 {selector:'.film-request-orbit',at:3900,duration:1000,from:{left:'24%',top:'37%',width:'52%'},to:{left:'4%',top:'17%',width:'41%'}},
 {selector:'.film-conversation-reply',at:3900,duration:800,from:{opacity:0},to:{opacity:1}},
 {selector:'.film-plan-workspace',at:7200,duration:900,from:{opacity:0,transform:'translateX(70px)'},to:{opacity:1,transform:'translateX(0px)'}}],
 cognition:[{selector:'.film-profile-surface',at:4300,duration:700,from:{paddingRight:'5%'},to:{paddingRight:'48%'}},{selector:'.film-evidence-drawer',at:4300,duration:700,from:{transform:'translateX(105%)'},to:{transform:'translateX(0%)'}},{selector:'.film-inline-edit',at:7000,from:{opacity:0},to:{opacity:1}}],
 life:[],
 experts:[{selector:'.film-group-chat',at:11600,duration:800,from:{transform:'translateY(0px)'},to:{transform:'translateY(min(0px, calc(100cqh - 470px)))'}},{selector:'.film-experts-directory',at:5500,duration:800,from:{opacity:1,transform:'translateX(0px)'},to:{opacity:0,transform:'translateX(-120px)'}},{selector:'.film-expert-group',at:5500,duration:800,from:{opacity:0,transform:'translateX(120px)'},to:{opacity:1,transform:'translateX(0px)'}}],
 projects:[{selector:'.film-project-console',at:10200,duration:800,from:{right:'0%'},to:{right:'46%'}},{selector:'.film-project-output',at:10200,duration:800,from:{opacity:0,transform:'translateX(80px)'},to:{opacity:1,transform:'translateX(0px)'}}],
 world:[{selector:'.film-capability-card',at:9300,duration:650,from:{opacity:1},to:{opacity:.22}},{selector:'.film-share-settings',at:9300,duration:650,from:{opacity:1},to:{opacity:.22}}],
 devices:[{selector:'.film-voice-moment',at:5800,duration:900,from:{opacity:1,transform:'translateY(0px)'},to:{opacity:0,transform:'translateY(-65px)'}},{selector:'.film-device-desktop',at:5800,duration:900,from:{opacity:0},to:{opacity:1}},{selector:'.film-device-desktop',at:12300,duration:800,from:{transform:'translateX(0px) scale(1)'},to:{transform:'translateX(var(--device-shift)) scale(.88)'}},{selector:'.film-mobile-device',at:12300,duration:800,from:{opacity:0,transform:'translateX(80px)'},to:{opacity:1,transform:'translateX(0px)'}}],
 history:[{selector:'.film-start-wall',at:3600,duration:700,from:{opacity:1,transform:'translateY(0px)'},to:{opacity:0,transform:'translateY(-35px)'}},{selector:'.film-start-chat',at:3600,duration:700,from:{opacity:0,transform:'translateY(45px)'},to:{opacity:1,transform:'translateY(0px)'}}]
};
export function GuideFilm({id,onComplete}:{id:GuideChapterId;onComplete:()=>void}){const {clock,time}=useFilmDriver(durations[id],onComplete);const stage=useRef<HTMLDivElement>(null);const components={vision:ConversationFilm,cognition:CognitionFilm,life:LifeFilm,experts:ExpertsFilm,projects:ProjectFilm,world:WorldFilm,devices:DevicesFilm,history:StartFilm};const Film=components[id];return <FilmMotionProvider clock={clock}><div className={`guide-film film-${id}`} role="img" aria-label={t('SecondU 功能操作动画，使用虚构示例。','SecondU product walkthrough with fictional example content.')}><div ref={stage} className="film-stage" inert><Film time={time}/><MotionPointer steps={pointerSteps[id]}/></div><NativeFilmMotion stage={stage} moves={movements[id]}/></div></FilmMotionProvider>;}
