import { ArrowRight, Brain, Calendar, Camera, Chat, Check, Document, Folder, Group, Link, Mic, Search, User } from '@openai/apps-sdk-ui/components/Icon';
import { HitherMark } from '../HitherMark';
import { PlatformIcon } from '../cognition/PlatformIcon';
import { t } from '../i18n';
import { MotionAppear, MotionWrite } from './filmMotion';
import './guideCognitionFilm.css';

const Appear=MotionAppear;
function SourceItem({platform,title,detail}:{platform:string;title:string;detail:string}) { return <div className="cognition-film-source"><PlatformIcon platform={platform}/><div className="cognition-film-source-copy"><strong>{title}</strong><span>{detail}</span></div></div>; }
function Gather() { return <Appear at={0} until={5300} className="cognition-film-gather"><div className="cognition-film-sources-left"><SourceItem platform={t('wechat','imessage')} title={t('家人聊天','Family messages')} detail={t('约好周六回家吃饭','Saturday lunch with your parents')}/><SourceItem platform={t('feishu','slack')} title={t('项目讨论','Project discussions')} detail={t('周五内测前完成设备预检','Check devices before Friday’s pilot')}/><SourceItem platform="generic" title={t('履历与作品','Résumé and work samples')} detail={t('经历、项目和做过的决定','Experience, projects and decisions')}/></div><div className="cognition-film-gather-center"><div className="cognition-film-gather-mark"><HitherMark/></div><h2>{t('关联资料，形成个人认知','Build context from connected records')}</h2><p>{t('从选定来源提取经历、关系与近期安排。','Connect experiences, relationships and plans from chosen sources.')}</p><Appear at={2400} className="cognition-film-gather-status"><Check/><span>{t('保留来源，关联人物与事件','Link people and events to their sources')}</span></Appear></div><div className="cognition-film-sources-right"><SourceItem platform="generic" title={t('旅行记录','Travel records')} detail={t('地点、同行者与共同经历','Places, companions and experiences')}/><SourceItem platform="generic" title={t('语音备忘','Voice notes')} detail={t('待处理事项与阶段性判断','Follow-ups and working judgments')}/><SourceItem platform="generic" title={t('近期安排','Current plans')} detail={t('项目进展、家庭约定与出行','Project progress, family plans and travel')}/></div></Appear>; }
const navItems=()=>[{icon:User,label:t('个人画像','Profile')},{icon:Calendar,label:t('生活近况','Current life')},{icon:Chat,label:t('聊天记录','Conversations')},{icon:Calendar,label:t('时间轴','Timeline')},{icon:Link,label:t('关系图谱','Connections')},{icon:Folder,label:t('资料来源','Sources')}];
function Nav({active=0}:{active?:number}) { return <aside className="cognition-film-nav"><strong><Brain/>{t('数字分身','Your digital twin')}</strong>{navItems().map(({icon:Icon,label},index)=><div key={label} className={index===active?'is-selected':''}><Icon/><span>{label}</span></div>)}</aside>; }
function Profile({time}:{time:number}) { const life=time>=9600; return <Appear at={5600} until={12700} className="cognition-film-window"><Nav active={life?1:0}/><section className="cognition-film-content"><header><span>{life?t('生活近况','Current life'):t('个人画像','Personal profile')}</span><Search/></header>{!life?<div className="cognition-film-profile"><div className="cognition-film-person"><div><User/></div><section><h2>{t('关于你','About you')}</h2><p>{t('经历、能力、关系与判断偏好','Experience, skills, relationships and preferences')}</p></section></div><div className="cognition-film-profile-grid"><section><small>{t('工作与能力','WORK & SKILLS')}</small><h3>{t('产品设计与工程','Product design & engineering')}</h3><p>{t('参与用户研究、交互设计与产品实现。','Works across user research, interaction design and implementation.')}</p></section><section><small>{t('生活与关系','LIFE & RELATIONSHIPS')}</small><h3>{t('家庭沟通与周末安排','Family and weekend plans')}</h3><p>{t('定期与父母见面，出行时预留休息时间。','Visits parents regularly and leaves room to rest when travelling.')}</p></section><section><small>{t('经历与兴趣','EXPERIENCE & INTERESTS')}</small><h3>{t('摄影、旅行与创作','Photography, travel and creative work')}</h3><p>{t('关注旅行中的影像记录与共同经历。','Values photographs and shared experiences from trips.')}</p></section><section><small>{t('偏好与判断','PREFERENCES & JUDGMENT')}</small><h3>{t('小范围验证，保留依据','Test on a small scale and keep evidence')}</h3><p>{t('先定义验证标准，再根据结果调整判断。','Defines pass criteria and revises judgments from the results.')}</p></section></div><footer><Document/>{t('可展开查看具体记录、来源与修订历史','Inspect records, sources and revision history')}<ArrowRight/></footer></div>:<div className="cognition-film-life"><h2>{t('近期安排与待办','Current plans and follow-ups')}</h2><p>{t('结合当前目标、关系与时间安排判断优先级。','Assess priorities using current goals, relationships and timing.')}</p><section><span><Folder/></span><div><strong>{t('周五开展桌面工作台内测','Run the desktop workspace pilot on Friday')}</strong><p>{t('方案已修订至第 2 版，周四完成设备预检。','The plan is at version 2; device checks are due Thursday.')}</p></div><small>{t('工作','WORK')}</small></section><section><span><Calendar/></span><div><strong>{t('周六回家与父母见面','Visit your parents on Saturday')}</strong><p>{t('已约好在家吃午饭，周六上午需出发。','Lunch at home is agreed; leave on Saturday morning.')}</p></div><small>{t('家人','FAMILY')}</small></section><section><span><Camera/></span><div><strong>{t('整理上次旅行的照片','Sort photos from the last trip')}</strong><p>{t('筛选后发给同行朋友，保留原始照片。','Select photos to share with companions and keep the originals.')}</p></div><small>{t('生活','LIFE')}</small></section><footer><Check/>{t('根据新增记录与确认更新状态','Update status from new records and confirmations')}</footer></div>}</section></Appear>; }
function ConnectionGraph() {
 const center={x:260,y:176};
 const nodes=[
  {id:'family',x:106,y:78,label:t('家人','Family'),detail:t('共同经历与近况','Shared experiences'),above:true},
  {id:'work',x:414,y:78,label:t('工作伙伴','Colleagues'),detail:t('项目与合作记录','Projects & collaboration'),above:true},
  {id:'friends',x:106,y:272,label:t('朋友','Friends'),detail:t('相处与共同兴趣','Time together & interests'),above:false},
  {id:'community',x:414,y:272,label:t('社群','Communities'),detail:t('活动与新的联系','Activities & connections'),above:false}
 ];
 return <section className="cognition-film-graph"><span className="cognition-film-section-title"><Link/>{t('关系图谱','Relationship map')}</span><h2>{t('关联人物、事件与合作','Connect people, events and collaboration')}</h2><div className="cognition-film-graph-canvas"><svg viewBox="0 0 520 360" className="cognition-film-graph-diagram" role="img" aria-label={t('你与家人、工作伙伴、朋友和社群的联系','Your connections with family, colleagues, friends and communities')}>
  <g className="cognition-film-graph-links">{nodes.map(node=><line key={node.id} x1={center.x} y1={center.y} x2={node.x} y2={node.y}/>)}</g>
  {nodes.map(node=><g key={node.id} className="cognition-film-graph-person" transform={`translate(${node.x} ${node.y})`}><circle r="25"/><Group x={-13} y={-13} width={26} height={26} className="cognition-film-graph-node-icon"/><text className="cognition-film-graph-label" y={node.above?-54:50}>{node.label}</text><text className="cognition-film-graph-detail" y={node.above?-34:72}>{node.detail}</text></g>)}
  <g className="cognition-film-graph-person is-self" transform={`translate(${center.x} ${center.y})`}><circle r="33"/><User x={-14} y={-14} width={28} height={28} className="cognition-film-graph-node-icon"/><text className="cognition-film-graph-label" y="56">{t('你','You')}</text></g>
 </svg></div></section>;
}
function Connections() { return <Appear at={13100} until={19700} className="cognition-film-connections"><section className="cognition-film-timeline"><span className="cognition-film-section-title"><Calendar/>{t('时间轴','Timeline')}</span><h2>{t('按时间回顾重要经历','Review key experiences over time')}</h2><div><time>2019</time><article><strong>{t('开始第一份工作','Started a first job')}</strong><p>{t('认识了一起做项目的同事','Met the people on a first project')}</p></article></div><div><time>2023</time><article><strong>{t('搬到新的城市','Moved to a new city')}</strong><p>{t('换了住处，也开始新的生活节奏','A new home and a different routine')}</p></article></div><div><time>2026</time><article><strong>{t('开始自己的项目','Started a personal project')}</strong><p>{t('工作、朋友和兴趣有了新的交集','Work, friends and interests came together')}</p></article></div><footer><Camera/><Mic/><Document/>{t('原始记录一直保留','Original records stay available')}</footer></section><ConnectionGraph/></Appear>; }
function UseContext() { return <Appear at={20100} className="cognition-film-apply"><div className="cognition-film-request"><HitherMark/><div><h2>{t('结合近期安排，提示时间冲突','Use current plans to flag conflicts')}</h2><div className="cognition-film-query"><MotionWrite at={20400} ms={1600} value={t('检查这周安排，提醒与周末回家冲突的事项。','Review this week’s plans and flag conflicts with my family visit.')} /></div><div className="cognition-film-context"><span><User/>{t('家人约定','Family plans')}</span><span><Calendar/>{t('内测进度','Pilot progress')}</span><span><Chat/>{t('返程与休息时间','Travel and rest time')}</span></div></div></div><Appear at={22400} className="cognition-film-answer"><strong>{t('将设备预检与材料整理提前','Complete device checks and materials earlier')}</strong><p>{t('周六上午需要出发回家。建议周四完成设备预检，周五内测后先记录关键问题，完整复盘安排在下周。','You need to leave Saturday morning. Finish device checks Thursday, capture key issues after Friday’s pilot and schedule the full review for next week.')}</p><footer><Document/>{t('依据家人聊天、内测计划与出行偏好','Based on family messages, the pilot plan and travel preferences')}</footer></Appear></Appear>; }
export function GuideCognitionFilm({time}:{time:number}) { return <><Gather/><Profile time={time}/><Connections/><UseContext/></>; }
