import { useLayoutEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { ArrowUp, ArrowRight, Calendar, Check, ChevronDown, Document, Edit, Folder, Group, Link, Plus, Search, User } from '@openai/apps-sdk-ui/components/Icon';
import { AgentAvatar } from '../agents/AgentIdentity';
import type { AgentProfile } from '../../shared/contracts';
import { HitherMark } from '../HitherMark';
import { HitherWordmark } from '../HitherWordmark';
import { t } from '../i18n';
import type { GuideChapterId } from './guideContent';
import { GuideCognitionFilm } from './GuideCognitionFilm';
import { GuideDevicesFilm } from './GuideDevicesFilm';
import { FilmMotionProvider, MotionAppear, MotionPointer, MotionWrite, NativeFilmMotion, useFilmDriver, type FilmPointerStep } from './filmMotion';
import { FILM_PLAYBACK_RATE } from './filmTiming';
import { GuideConversationFilm, GuideTeamFilm, GuideArtifactsFilm } from './GuideIterationFilms';
import './guideShowcaseFilms.css';

const Appear=MotionAppear, Write=MotionWrite;
function Brand(){return <span className="showcase-brand"><HitherMark/><HitherWordmark/></span>;}
function MiniButton({children,className=''}:{children:ReactNode;className?:string}){return <button className={`showcase-button ${className}`}>{children}</button>;}
function FileRow({title,detail,className=''}:{title:string;detail?:string;className?:string}){return <div className={`showcase-file ${className}`}><span><Document/></span><div><strong>{title}</strong>{detail&&<small>{detail}</small>}</div><ArrowRight/></div>;}
function WindowChrome({title,children}:{title:string;children?:ReactNode}){return <div className="showcase-chrome"><span className="showcase-window-dots"><i/><i/><i/></span><span>{title}</span>{children}</div>;}
function Composer({at=400,value}:{at?:number;value:string}){return <div className="showcase-composer"><p><Write at={at} ms={2100} value={value}/></p><footer><Plus/><span><Folder/>{t('桌面工作台内测','Desktop workspace pilot')}</span><button className="showcase-send"><ArrowUp/></button></footer></div>;}
function ChatColumn({time,overview=false}:{time:number;overview?:boolean}){
 const done=time>8300;
 return <aside className="showcase-chat"><Brand/><div className="showcase-user-message">{overview?t('结合我的做事方式和本周安排，准备下一轮内测。','Plan the next pilot around how I work and this week’s commitments.'):t('汇总 5 份访谈，准备下一轮内测方案。','Review five interviews and plan the next pilot.')}</div><div className="showcase-assistant"><HitherMark/><div><p>{overview?t('我会结合已确认的偏好、当前安排与任务证据。','I’ll use your confirmed preferences, current plans and task evidence.'):t('先核对访谈原文，再定义流程与通过标准。','I’ll check the sources, then define steps and pass criteria.')}</p><div className="showcase-steps"><span><Check/>{t('核对访谈来源','Check interview sources')}</span><span className={time>6500?'':'is-running'}>{time>6500?<Check/>:<i/>}{t('定义验证流程','Define validation steps')}</span><span className={done?'':'is-pending'}>{done?<Check/>:<i/>}{t('生成可编辑文档','Create editable document')}</span></div></div></div><Appear at={8700} className="showcase-result-link"><FileRow title={t('内测验证方案.md','Pilot validation plan.md')} detail={t('包含流程、标准与准备清单','Steps, criteria and preparation')}/></Appear><div className="showcase-small-composer"><span>{t('补充要求或修改…','Add requirements or revisions…')}</span><div><Plus/><ArrowUp/></div></div></aside>;
}
function SessionDocument({time}:{time:number;overview?:boolean}){
 const revised=time>13300,saved=time>14600;
 return <section className="showcase-document"><div className="showcase-doc-tabs"><span><Document/>{t('内测验证方案.md','Pilot validation plan.md')}</span><small>{saved?'v2':'v1'}</small><button className="showcase-save">{saved?<Check/>:<Edit/>}{saved?t('已保存','Saved'):t('编辑','Edit')}</button></div><div className="showcase-doc-toolbar"><span className="is-selected">{t('预览','Preview')}</span><span>{t('编辑','Edit')}</span><span>{t('版本','Versions')}</span></div><article className="showcase-paper"><span className="showcase-doc-eyebrow">{t('桌面工作台的下一轮内测','NEXT DESKTOP WORKSPACE PILOT')}</span><h2>{t('内测验证方案','Pilot validation plan')}</h2><p className="showcase-doc-lead">{t('邀请 8 名用户，验证成果保存与跨设备续接。','Invite eight users to validate saved work and task continuity.')}</p><div className="showcase-doc-rule"/><div className="showcase-doc-columns"><section><h3>{t('验证流程','Validation steps')}</h3><ol><li>{t('完成任务并编辑成果','Complete a task and edit the result')}</li><li>{t('保存后重新打开，核对版本','Save, reopen and check the version')}</li><li>{t('在手机上继续同一项任务','Continue the same task on a phone')}</li></ol></section><section><h3>{t('通过标准','Pass criteria')}</h3><p>{t('重新打开后，内容与版本一致','Content and version match on reopen')}<br/>{t('换设备后，资料与修改可见','Sources and edits persist across devices')}<br/>{t('待确认事项有明确状态','Pending reviews have a clear status')}</p></section></div><div className={`showcase-time-edit ${revised?'is-revised':''}`}><span>{t('提前准备','Preparation')}</span><strong><span className="showcase-edit-number">{revised?'5':'3'}</span> {t('天','days')}</strong><span>{t('参与者招募、材料与设备预检','Recruitment, materials and device checks')}</span></div></article></section>;
}
function TaskScene({time,overview=false}:{time:number;overview?:boolean}){
 const value=overview?t('帮我推进下一轮内测，结合我的做事方式和本周安排。','Help me move the next pilot forward, using how I work and this week’s commitments.'):t('汇总 5 份访谈，给出内测流程、通过标准和准备清单。','Review five interviews. Draft the pilot steps, pass criteria and preparation checklist.');
 return <><Appear at={0} until={3600} className="showcase-intro"><div className="showcase-intro-camera"><Brand/><Composer value={value}/>{overview&&<div className="showcase-context-hints"><span><Document/>{t('5 份访谈记录','Five interview records')}</span><span><User/>{t('先明确小范围验证标准','Define criteria for a small pilot')}</span></div>}</div></Appear><Appear at={3100} className={`showcase-main-window ${overview?'showcase-overview-window':''}`}><WindowChrome title={t('桌面工作台内测','Desktop workspace pilot')}/><div className="showcase-split"><ChatColumn time={time} overview={overview}/><div className="showcase-work-area"><Appear at={3500} until={8300} className="showcase-source-reading"><span className="showcase-source-chip"><Search/>{t('核对原文与验证目标','Checking sources and goals')}</span><div className="showcase-source-page"><Document/><h2>{t('5 份访谈记录','Five interview records')}</h2><p>{t('“电脑上改过文稿，手机打开时看不出是不是最新版本。”','“I edited the draft on my computer, but can’t tell if the phone has the latest version.”')}</p><div/><div/><div/></div><div className="showcase-context-note"><User/><p>{t('已确认的偏好：先小范围验证，保留判断依据。','Confirmed preference: start small and keep the evidence.')}</p></div></Appear><Appear at={8700} className="showcase-document-layer"><SessionDocument time={time} overview={overview}/></Appear></div></div></Appear>{overview&&<div className="showcase-overview-cycle" aria-label={t('数字分身的持续协作','Ongoing collaboration with your digital twin')}><span className={time<8300?'is-current':''}><User/>{t('有依据地理解你','Understand you through sources')}</span><ArrowRight/><span className={time>=8300&&time<13300?'is-current':''}><Check/>{t('带着背景完成任务','Use context to complete work')}</span><ArrowRight/><span className={time>=13300?'is-current':''}><Edit/>{t('确认反馈，更新理解','Confirm feedback and update understanding')}</span></div>}</>;
}

function ProjectScene({time}:{time:number}){
 return <><GuideArtifactsFilm time={time}/><Appear at={12900} className="showcase-project-schedule"><div className="showcase-automation-card"><div><Calendar/><span className="showcase-toggle"/></div><h2>{t('每周内测复盘','Weekly pilot review')}</h2><p>{t('每周五 17:00','Every Friday, 17:00')}</p><div className="showcase-automation-rule"/><span>{t('归档本周反馈，核对完成项，标出待决定的问题。','File weekly feedback, check completed work and flag pending decisions.')}</span><footer><i/>{time>14400?t('刚刚完成','Completed just now'):t('已安排','Scheduled')}</footer></div><div className="showcase-project-notification"><div className="showcase-notification-top"><Brand/><small>{t('周五 17:00','FRI 17:00')}</small></div><Appear at={13000}><h3>{t('本周内测准备进展','This week’s pilot preparation')}</h3><p>{t('访谈整理与方案修订已完成，参与者时段尚待确认。','Interview review and plan revisions are complete. Participant times still need confirmation.')}</p><FileRow title={t('本周项目进展.md','Weekly project review.md')}/></Appear></div></Appear></>;
}
function SharingScene({time}:{time:number}){
 const agent:AgentProfile={id:'guide-specialist-twin',name:t('产品评审分身','Product review twin'),role:t('流程评审与验收建议','Flow reviews and acceptance criteria'),instructions:'',createdAt:'2026-09-30',avatarStyle:'notionists'};
 return <><Appear at={0} until={8300} className="showcase-sharing-setup"><div className="showcase-sharing-identity"><AgentAvatar agent={agent} size={76}/><h2>{agent.name}</h2><p>{t('基于选定资料提供产品评审建议。','Offer product review advice from selected sources.')}</p><div className="showcase-sharing-method"><Document/><span>{t('产品评审方法','Product review method')}</span></div><div className="showcase-sharing-method"><Document/><span>{t('流程检查清单','Flow review checklist')}</span></div></div><div className="showcase-sharing-permissions"><span className="showcase-section-label"><Link/>{t('资料与调用范围','SOURCES AND ACCESS')}</span><h2>{t('设置共享权限','Set sharing permissions')}</h2><div><span>{t('可用资料','Available sources')}</span><strong>{t('这两份公开资料','These two public sources')}</strong></div><div><span>{t('允许操作','Allowed actions')}</span><strong>{t('提供文本评审建议','Provide text review advice')}</strong></div><div><span>{t('有效期','Available for')}</span><strong>{t('7 天','7 days')}</strong></div><MiniButton className="showcase-sharing-create"><Link/>{t('创建分享','Create share')}</MiniButton><small>{t('其他资料保持私密','Other information stays private')}</small></div></Appear><Appear at={9000} className="showcase-sharing-conversation"><div className="showcase-sharing-counterpart"><span className="showcase-section-label"><Group/>{t('对方的 SecondU','THEIR SECONDU')}</span><div className="showcase-sharing-question"><Write at={9500} ms={1700} value={t('如何判断报名流程是否达到交付标准？','How do we decide whether a signup flow is ready to ship?')}/></div><div className="showcase-sharing-route"><ArrowRight/><span>{t('调用产品评审分身','Consulting the product review twin')}</span></div></div><div className="showcase-sharing-answer"><div><AgentAvatar agent={agent} size={51}/><h3>{agent.name}</h3></div><Appear at={12000}><h2>{t('明确成功状态与异常路径','Define success and error paths')}</h2><p>{t('提交后显示报名结果、时间和地址；异常时保留已填内容，并提供重试路径。','Show the result, time and location after submission. On failure, retain entered details and provide a retry path.')}</p><span className="showcase-sharing-citation"><Document/>{t('参考：流程检查清单','Source: Flow review checklist')}</span></Appear><Appear at={15100} className="showcase-sharing-record"><span><Check/>{t('已回答 1 个问题','1 question answered')}</span><button className="showcase-sharing-stop">{t('停止分享','Stop sharing')}</button></Appear></div></Appear></>;
}
function FeedbackScene({time}:{time:number}){
 const confirmed=time>13300;
 return <><Appear at={0} until={6500} className="showcase-feedback-intro"><div className="showcase-feedback-result"><FileRow title={t('内测验证方案.md','Pilot validation plan.md')} detail={t('方案修订记录','Plan revision record')}/><div><span>{t('准备时间','Preparation time')}</span><strong>{t('3 天 → 5 天','3 days → 5 days')}</strong></div></div><Composer value={t('3 天准备时间不足。下次提前 5 天，并将招募和设备预检列入清单。','Three days wasn’t enough. Next time allow five, with recruitment and device checks on the list.')}/></Appear><Appear at={7000} className="showcase-feedback-review"><div className="showcase-feedback-evidence"><span className="showcase-section-label"><Document/>{t('反馈与修订依据','FEEDBACK AND REVISION EVIDENCE')}</span><div className="showcase-feedback-evidence-item"><span><Edit/></span><div><strong>{t('已保存的修改','Saved revision')}</strong><p>{t('准备时间从 3 天改成了 5 天。','Preparation changed from three days to five.')}</p></div></div><div className="showcase-feedback-evidence-item"><span><User/></span><div><strong>{t('本次任务反馈','Task feedback')}</strong><p>{t('“下次提前 5 天，列入招募和设备预检。”','“Allow five days, with recruitment and device checks.”')}</p></div></div><small>{t('原文和修改记录都会保留。','Originals and changes stay available.')}</small></div><div className={`showcase-feedback-memory ${confirmed?'is-confirmed':''}`}><span className="showcase-feedback-memory-state">{confirmed?<Check/>:<User/>}{confirmed?t('已按你的确认更新','Updated with your confirmation'):t('待确认的认知更新','Context update awaiting review')}</span><h2><Write at={7500} ms={1500} value={t('内测准备至少提前 5 天','Allow five days to prepare a pilot')}/></h2><p>{t('安排小范围内测时，至少提前 5 天启动准备，并检查参与者招募与设备状态。','For small pilots, start preparation at least five days ahead and check recruitment and devices.')}</p><MiniButton className="showcase-feedback-confirm">{confirmed?<Check/>:<Plus/>}{confirmed?t('已更新','Updated'):t('确认更新','Confirm update')}</MiniButton><Appear at={14400} className="showcase-feedback-next"><span>{t('后续内测任务','FUTURE PILOT TASKS')}</span><strong><Calendar/>{t('采用 5 天准备与设备预检','Use five days and device checks')}</strong></Appear></div></Appear></>;
}

const pointers:Partial<Record<GuideChapterId,FilmPointerStep[]>>={
 devices:[{at:0,position:[91,88]},{at:9600,target:'.device-film-edit-time',click:true},{at:11400,target:'.device-film-save',click:true},{at:15900,target:'.device-film-confirm',click:true},{at:17700,position:[93,91]}],
 cognition:[{at:0,position:[94,91]},{at:8800,target:'.cognition-film-nav>div:nth-child(3)',click:true},{at:13000,position:[94,91]},{at:20700,position:[94,91]}],
 experts:[{at:0,position:[90,85]},{at:2500,target:'.ag-room-selected[data-guide-member="2"]',click:true},{at:4500,target:'.ag-room-selected[data-guide-member="0"]',click:true},{at:4800,target:'.guide-team-mode',click:true},{at:8300,target:'.team-run-workers'},{at:11400,target:'.team-run-workers'},{at:14600,target:'.team-run-node[data-kind=lead]'},{at:16400,position:[93,91]}],
 projects:[{at:0,position:[92,88]},{at:2500,target:'.guide-artifact-item[data-guide-format="1"]',click:true},{at:4500,target:'.guide-artifact-item[data-guide-format="2"]',click:true},{at:7900,target:'.guide-artifact-item[data-guide-format="3"]',click:true},{at:14300,target:'.showcase-automation-card'},{at:16200,position:[93,91]}],
 world:[{at:0,position:[90,87]},{at:4800,target:'.showcase-sharing-permissions'},{at:7800,target:'.showcase-sharing-create',click:true},{at:14400,target:'.showcase-sharing-citation'},{at:16600,position:[93,91]}],
 history:[{at:0,position:[84,88]},{at:5300,target:'.showcase-send',click:true},{at:9400,target:'.showcase-feedback-memory'},{at:13300,target:'.showcase-feedback-confirm',click:true},{at:16100,position:[93,91]}],
 vision:[{at:0,position:[81,76]},{at:2800,target:'.showcase-send',click:true},{at:6500,target:'.showcase-context-note'},{at:9400,target:'.showcase-result-link',click:true},{at:12300,target:'.showcase-edit-number',click:true},{at:14600,target:'.showcase-save',click:true},{at:16500,position:[93,91]}],
 life:[{at:0,position:[81,76]},{at:3000,target:'.guide-revision-edit',click:true},{at:6300,target:'.guide-revision-save',click:true},{at:9400,target:'.message-reactions button',click:true},{at:11200,target:'.guide-reply-action',click:true},{at:14600,target:'.guide-version-save',click:true},{at:16500,position:[93,91]}]
};
export function GuideShowcaseFilm({id,onComplete}:{id:GuideChapterId;onComplete:()=>void}){
 const {clock,time}=useFilmDriver(id==='cognition'?25500:19000,onComplete,id==='cognition'?6050:id==='world'?9450:0),viewport=useRef<HTMLDivElement>(null),stage=useRef<HTMLDivElement>(null);
 const [scale,setScale]=useState(1);
 useLayoutEffect(()=>{const node=viewport.current;if(!node)return;const update=()=>setScale(Math.min(node.clientWidth/1280,node.clientHeight/720));const observer=new ResizeObserver(update);observer.observe(node);update();return()=>observer.disconnect();},[]);
 return <FilmMotionProvider clock={clock}><div className={`showcase-film showcase-${id}`} ref={viewport} style={{'--film-playback-rate':FILM_PLAYBACK_RATE} as CSSProperties} role="img" aria-label={t('SecondU 功能演示，使用虚构示例','SecondU walkthrough using fictional examples')}><div className="showcase-scale" style={{transform:`translate(-50%,-50%) scale(${scale})`}}><div className="showcase-stage" ref={stage} inert>{id==='devices'?<GuideDevicesFilm time={time}/>:id==='cognition'?<GuideCognitionFilm time={time}/>:id==='experts'?<GuideTeamFilm time={time}/>:id==='life'?<GuideConversationFilm time={time}/>:id==='projects'?<ProjectScene time={time}/>:id==='world'?<SharingScene time={time}/>:id==='history'?<FeedbackScene time={time}/>:<TaskScene time={time} overview={id==='vision'}/>}<MotionPointer steps={pointers[id]||pointers.vision!}/></div></div><NativeFilmMotion stage={stage} moves={id==='vision'?[{selector:'.showcase-intro-camera',at:2800,duration:850,from:{transform:'translate(0,0) scale(1)'},to:{transform:'translate(-365px,-142px) scale(.42)'}},{selector:'.showcase-split',at:3000,duration:1000,from:{clipPath:'inset(0 73% 0 0)'},to:{clipPath:'inset(0 0% 0 0)'}}]:[]}/></div></FilmMotionProvider>;
}
