import { t } from '../i18n';

export type GuideChapterId = 'vision'|'devices'|'cognition'|'life'|'experts'|'projects'|'world'|'history';
export type GuideChapter = {id:GuideChapterId;label:string;title:string;description:string;detail:string;note:string;status:string;action:string;target:string;steps:string[];preview?:boolean};
export {GUIDE_VERSION,readGuideProgress,hasSeenProductGuide,saveGuideProgress,completeGuideChapter} from './guideProgress.mjs';
export function getGuideChapters():GuideChapter[]{return [
 {id:'vision',label:t('认识 SecondU','Meet SecondU'),title:t('有一个持续理解你的 SecondU','A SecondU that grows to understand you'),description:t('把你的经历、习惯与正在做的事连起来。遇到新的问题，带着对你的理解，一起判断，也一起行动。','Connect your experiences, habits, and current work. Bring that understanding into new decisions and the work that follows.'),detail:t('个人认知是 SecondU 的共同基础：它影响如何建议、选择哪位专家、如何推进项目，以及何时需要你来决定。','Personal understanding is the shared foundation: it shapes suggestions, expert selection, project work, and the decisions brought back to you.'),note:t('当前可查看和修正有来源的理解，并将选定背景用于新任务。理解是否准确，要由你在实际使用中检验。','You can inspect and correct sourced context and use selected context in new tasks. Its accuracy remains yours to judge in real use.'),status:t('开始了解','Introduction'),action:t('开始一段对话','Start a conversation'),target:'assistant',steps:[t('理解你的情况','Understand your context'),t('一起判断取舍','Decide together'),t('推进眼前的事','Move the work forward')]},
 {id:'cognition',label:t('个人认知体系','Understanding'),title:t('关于你的理解，看得见，也改得动','See and shape how it understands you'),description:t('从万叶的经历、近况与关系开始，看看一条理解如何回到原始记录。觉得不准确，就补充和修正。','Follow Caspian’s experiences, life, and relationships to the records behind each insight. Add context or make a correction whenever needed.'),detail:t('个人画像、生活近况、聊天记录、时间轴与关系图谱提供不同视角。目标、偏好和约束有各自来源，原始记录与历次修订保留。','Profile, life, conversations, timeline, and relationships offer complementary views. Goals, preferences, and constraints keep their sources and revisions.'),note:t('候选与已确认的理解分开；确认后的修正用于之后的新任务。','Candidate insights stay separate from confirmed understanding. Confirmed corrections are used in future tasks.'),status:t('可体验','Available'),action:t('看看个人画像','Explore your profile'),target:'self',steps:[t('了解当前画像','Inspect your profile'),t('回到来源','Trace the source'),t('修正并保留版本','Correct and keep revisions')]},
 {id:'life',label:t('个性化执行','Personal action'),title:t('同一件事，按你的情况来做','Make the plan fit your life'),description:t('上午留给专注，周末留给家人。把这些偏好带进本周安排，再决定哪些事情交给 SecondU 持续处理。','Keep mornings for focused work and weekends for family. Bring those preferences into the week and choose which routines SecondU should handle.'),detail:t('任务可选择已确认的个人背景、连接器与项目。计划、工具使用、结果和反馈围绕同一件事展开；例行整理可以设置本机自动化。','Tasks can use confirmed personal context, selected connectors, and a project. Plans, tools, results, and feedback stay with the task; recurring reviews can run as local automations.'),note:t('真实执行需要可用的模型与工具连接；本机自动化需要服务保持运行。','Live execution needs a working model and tool connection. Local automations need the service to remain running.'),status:t('可体验','Available'),action:t('安排例行整理','Set up a routine'),target:'automations',steps:[t('带上个人背景','Include your context'),t('安排可执行的一步','Choose a practical step'),t('从结果继续调整','Refine from the result')]},
 {id:'experts',label:t('专业智能体协作','Expert team'),title:t('需要专业判断时，请合适的人加入','Bring the right expertise into the conversation'),description:t('规划、复核、整理各有分工。挑选专家，让他们围绕同一个问题协作，你随时可以补充方向。','Give planning, review, and writing clear roles. Bring experts together around one problem and add direction as the work develops.'),detail:t('从专家目录选择职责，配置各自的模型与工作方式。可以单独沟通，也可以组成群聊，指定成员、引用消息并继续同一项任务。','Choose roles from the expert directory and configure their models and working styles. Work one-to-one or in a room with member selection, quoted replies, and a shared task.'),note:t('专家目录提供角色起点；群聊按明确的成员顺序执行，保留各自消息与过程。','The directory provides starting roles. Group work follows an explicit member order and retains each member’s messages and activity.'),status:t('可体验','Available'),action:t('寻找合适的专家','Find an expert'),target:'agents',steps:[t('选择分工','Choose the roles'),t('共同讨论','Work in one conversation'),t('检查完整结果','Review the result')]},
 {id:'projects',label:t('项目与长期事务','Ongoing work'),title:t('事情会持续，进度也留得住','Keep progress across days and conversations'),description:t('把内测计划、资料和会话放进同一个项目。这次做完一部分，下次带着文件与进度接着做。','Keep the pilot plan, sources, and conversations in one project. Finish a part today and return to the files and progress next time.'),detail:t('项目关联本地工作目录，任务可以读取和修改实际文件；长期目标、待办与自动化分别记录方向、下一步和例行工作。','Projects connect to a local folder where tasks can read and edit actual files. Goals, to-dos, and automations retain direction, next steps, and recurring work.'),note:t('本地文件成果可直接审阅。远程仓库目前作为引用保存。','Local file results can be inspected directly. Remote repositories are currently stored as references.'),status:t('可体验','Available'),action:t('打开项目','Open projects'),target:'projects',steps:[t('汇集相关资料','Bring the context together'),t('推进实际文件','Work on real files'),t('下次继续','Continue next time')]},
 {id:'devices',label:t('多设备与多模态','Across devices'),title:t('换个设备，仍是刚才那件事','The same task, on the right device'),description:t('路上说一句，桌面上仔细整理，手机上看结果。文字、语音、图片和屏幕，接住不同场景下的表达。','Speak while out, work carefully at your desk, and review on your phone. Use text, voice, images, and screen context where each makes sense.'),detail:t('桌面用于完整工作，手机用于随手补充与审阅，眼镜用于场景中的短暂交互。设计围绕同一个任务与个人认知，不要求每个设备重讲背景。','The desktop supports deeper work, the phone adds context and review, and glasses support brief interactions in a scene. All are designed around the same task and personal understanding.'),note:t('当前桌面可用；手机与眼镜的连续体验在设备预览中演示，尚未连接真实硬件。','The desktop is available. Continuity with phones and glasses is demonstrated in the device preview, without live hardware integration.'),status:t('预览','Preview'),preview:true,action:t('打开设备预览','Explore device preview'),target:'devices',steps:[t('现场补充','Capture in context'),t('桌面处理','Work at your desk'),t('随身审阅','Review on the move')]},
 {id:'world',label:t('受限能力分享','Skill sharing'),title:t('把一项专长交出去，范围由你决定','Share a skill with boundaries you choose'),description:t('把万叶的产品评审方法做成一个专业分身。只开放选定的能力与资料，让别人的助理按范围来协作。','Turn Caspian’s product review method into a focused professional twin. Share selected skills and sources so another assistant can collaborate within that scope.'),detail:t('规划中的 A2A 分享包括能力说明、允许使用的资料、调用方与有效期；通过链接或二维码交给对方，调用有记录，权限可以撤回。','Planned A2A sharing combines a capability description, permitted sources, callers, and an expiry. A link or QR code hands it over, with recorded calls and revocable access.'),note:t('这段展示交互方向。当前角色名片可导入；可调用的个人分身发布、访问控制与调用回执尚待实现。','This scene previews the interaction. Role cards can be imported today; publishing callable personal twins, access control, and call receipts remain planned.'),status:t('预览','Preview'),preview:true,action:t('查看当前助理入口','Explore current assistants'),target:'agents',steps:[t('选择能力与资料','Choose a skill and sources'),t('限定对象与期限','Set the caller and expiry'),t('查看调用与撤回','Review calls and revoke')]},
 {id:'history',label:t('开始体验','Start exploring'),title:t('从你眼前的一件事开始','Start with something on your mind'),description:t('整理一份资料，聊聊一个想法，或打开正在做的项目。让 SecondU 从这次协作开始了解你。','Add a source, talk through an idea, or open a project in progress. Let SecondU begin understanding you through the work you do together.'),detail:t('示例空间中的万叶（Caspian）方便完整体验；自己的空间保留自己的资料与会话。可以随时从侧栏重新打开介绍。','Caspian’s example space provides a complete walkthrough. Your own space keeps your sources and conversations. Reopen this guide from the sidebar anytime.'),note:t('章节动画使用示例内容，只演示交互。下方入口打开对应的实际工作区。','Chapter animations use example content to demonstrate interactions. The links below open the actual workspaces.'),status:t('开始使用','Get started'),action:t('开始一段对话','Start a conversation'),target:'assistant',steps:[t('说说眼前的事','Share what is on your mind'),t('补充个人背景','Add your context'),t('一起推进','Work through it together')]}
];}
