import { t } from '../i18n';

export type GuideChapterId = 'vision'|'devices'|'cognition'|'life'|'experts'|'projects'|'world'|'history';
export type GuideChapter = {id:GuideChapterId;label:string;title:string;description:string;note:string;action:string;target?:string;uses:string[];preview?:boolean};
export {GUIDE_VERSION,readGuideProgress,hasSeenProductGuide,saveGuideProgress,completeGuideChapter} from './guideProgress.mjs';
export function getGuideChapters():GuideChapter[]{return [
 {id:'vision',label:t('产品概览','Overview'),title:t('你的数字分身，与你一起完成任务','Your digital twin, working alongside you'),description:t('SecondU 从有来源的资料中理解你的经历、偏好与近况，带着相关背景参与任务，并让你随时纠正。','SecondU builds an understanding of your experiences, preferences and current plans from sources, brings relevant context to tasks, and lets you correct it.'),note:t('资料保存在本机，模型由你选择；云模型会接收经授权用于当前任务的内容。引导使用虚构资料，跨设备章节为方向演示。可进入示例空间，随时返回自己的空间。','Sources stay on this computer and you choose the model; cloud models receive authorized task context. The guide uses fictional sources, and the cross-device chapter is a concept demonstration. Open the example workspace and return to your own space at any time.'),action:t('查看示例','View example'),target:'assistant',uses:[t('在持续更新的个人认知基础上开展任务','Work from an evolving understanding of you'),t('结合近期安排提示冲突与待办','Surface conflicts and follow-ups from current plans'),t('保留任务依据、成果与修改记录','Keep evidence, results and revisions')]},
 {id:'cognition',label:t('数字分身','Digital twin'),title:t('让数字分身持续理解你','A digital twin that keeps learning about you'),description:t('将经历、关系与近况连成有来源的个人认知。相关理解参与任务，你可以查看依据、纠正内容，并确认新的更新。','Connect experiences, relationships and current plans into sourced personal context. Bring relevant understanding to tasks, inspect its evidence, correct it and confirm updates.'),note:t('已支持来源查阅、认知修正与版本记录；任务按相关性和授权选取背景。','Source inspection, corrections and revisions are available. Tasks select relevant, authorized context.'),action:t('查看数字分身','View your digital twin'),target:'self',uses:[t('保留原始资料与判断依据','Keep original records and supporting evidence'),t('区分已确认事实与待复核判断','Separate confirmed facts from interpretations'),t('在新任务中复用相关背景','Reuse relevant context in new tasks')]},
 {id:'life',label:t('任务执行','Task execution'),title:t('从需求到可编辑成果','From a request to an editable result'),description:t('修改已发出的问题，引用具体回复，再将成果保存为新版本。','Revise a sent request, quote a specific reply, and save changes to a result as a new revision.'),note:t('问题修改保留独立分支与原对话；文本成果可编辑保存版本，PDF 与 Office 为只读预览。真实任务需配置模型与相应工具。','Message edits preserve the original chat in a separate branch. Text results support saved revisions; PDF and Office previews are read-only. Live tasks need a model and relevant tools.'),action:t('创建任务','Create a task'),target:'assistant',uses:[t('修改问题后保留原对话','Keep the original chat when revising a request'),t('用表情和引用回应具体消息','React to or quote a specific message'),t('修改同一成果并保留版本','Edit the same result and keep its versions')]},
 {id:'experts',label:t('多专家协作','Expert collaboration'),title:t('围绕任务开展多专家协作','Coordinate specialists around a task'),description:t('像组织一支团队一样，选择不同专长的成员、指定负责人，再按任务需要分工并汇总结果。','Build a team with different specialties, choose its lead, then delegate as needed and gather the results.'),note:t('共同讨论与负责人调度均可用。执行树由真实运行记录更新；这里展示虚构状态，不调用模型。外部账户能力需分别接通。','Discussion and lead-based teams are available. Execution trees use saved runtime events; this film shows fictional states without model calls. External accounts require their own connections.'),action:t('查看专家','View experts'),target:'agents',uses:[t('在已选成员旁直接指定负责人','Assign the lead beside a selected member'),t('分别配置模型、知识与工具','Configure each expert’s model, knowledge and tools'),t('查看派发、待审批、结果与失败状态','Inspect assignments, approvals, results and failures')]},
 {id:'projects',label:t('项目上下文','Project context'),title:t('保留项目上下文，持续跟进','Preserve context and follow progress'),description:t('预览文档、代码、表格与 PDF，保留原文件和版本，按计划跟进项目。','Preview documents, code, tables and PDFs; keep originals and revisions, and follow up on the project.'),note:t('代码高亮、表格与本地 PDF 预览可用；Office 预览需本机安装 LibreOffice，原文件始终保留。自动化需服务持续运行。','Code highlighting, tables and local PDF previews are available. Office previews require local LibreOffice; original files remain available. Automations require the service to keep running.'),action:t('打开项目','Open projects'),target:'projects',uses:[t('在同一位置查看不同格式成果','Inspect different result formats in one place'),t('根据进度与决策继续已有工作','Continue from recorded progress and decisions'),t('通过自动化整理、提醒与执行','Automate reviews, reminders and agreed actions')]},
 {id:'devices',label:t('跨设备协同','Across devices'),title:t('跨设备继续同一项任务','Continue the same task across devices'),description:t('语音和图像进入同一任务，跨设备继续编辑与确认。','Bring voice and images into one task, then continue editing and reviewing across devices.'),note:t('以下为跨设备流程动画，未连接真实眼镜或手机；每次任务仍按相关性和权限选取资料。','This animated concept does not connect to real phones or glasses. Each task still selects sources by relevance and permission.'),action:t('继续浏览','Continue'),uses:[t('完整保留原始资料、来源与时间','Retain originals, provenance and time'),t('换设备后继续同一任务与成果','Continue the same task and result on another device'),t('离线恢复时核对版本与确认状态','Check revisions and approvals when reconnecting')],preview:true},
 {id:'world',label:t('能力与连接','Capabilities and connections'),title:t('让专业能力走出去，让合适的人相遇','Share expertise and connect with the right people'),description:t('从限定资料与权限的专业分身出发，逐步延伸到 A2A 协作、专业服务，以及双方同意的 Agent Dating。','Start with specialist twins using scoped sources and permissions, and extend toward A2A collaboration, professional services and mutually agreed Agent Dating.'),note:t('本机受限分身、API Key 文本调用、审批与撤销可用；远程分发、真实社交匹配及交易尚未交付。','Local text delegates, API key calls, approvals and revocation are available. Remote distribution, live social matching and transactions are not yet delivered.'),action:t('查看 Agent 市场','View the Agent market'),target:'agents/market',uses:[t('将专业方法转化为受限咨询能力','Make professional methods available for scoped consultation'),t('明确资料范围、调用权限与服务规则','Define context, calling permissions and service rules'),t('查看调用记录，随时调整或撤回','Inspect calls and change or revoke access')],preview:true},
 {id:'history',label:t('反馈更新','Feedback and updates'),title:t('从反馈中更新个人认知','Update personal context through feedback'),description:t('经你确认的修改与反馈会更新数字分身的个人认知，供后续任务参考。','Confirmed changes and feedback update your digital twin’s personal context for future tasks.'),note:t('任务反馈可形成待确认候选，确认后用于新任务；模型升级后的批量重解析仍在规划中。','Task feedback can create reviewable candidates for future tasks. Bulk reanalysis after model upgrades remains planned.'),action:t('开始使用 SecondU','Start using SecondU'),target:'assistant',uses:[t('保留原始证据与历史版本','Preserve original evidence and earlier versions'),t('复核新信息、纠正与实际结果','Review new information, corrections and outcomes'),t('将确认后的理解用于后续任务','Apply confirmed understanding to future tasks')]}
];}
