import type { TeamConfiguration, TeamRun } from './team-run-types';
export type { TeamConfiguration, TeamRun, TeamRunNode } from './team-run-types';
import type { RemoteRun } from './remote-computer-types';
import type { ContextRequest } from './cognition-context';
export type { ContextRequest, ContextPurpose, FeedbackScope, TaskFeedbackRecord } from './cognition-context';
import type { Connector } from './connectors';
export type { Connector, ConnectorKind, ConnectorStatus, ConnectorTool, SaveConnector, ConnectorTestResult, ConnectorAuthMode, ConnectorOAuthConfig, ConnectorOAuthPublic, ConnectorOAuthStart, ConnectorOAuthStatus } from './connectors';
export type FactKind = 'preference' | 'value' | 'capability' | 'constraint' | 'identity' | 'decision';
export type PreferenceDomain = 'work' | 'taste' | 'general';
export type FactStatus = 'confirmed' | 'inferred' | 'candidate' | 'superseded';
export interface Source { id: string; title: string; kind: 'note'|'conversation'|'document'|'feedback'; text: string; createdAt: string; demo: boolean; activityImport?: {format: 'hither.activity.v1'; sourceId: string; filename: string; sha256: string; importedAt: string}; import?: {platform: ChatImportPlatform; accountId: string; filename: string; sha256: string; importedAt: string} }
export interface FactRevision { kind?: FactKind; preferenceDomain?: PreferenceDomain; sourceIds?: string[]; version: number; statement: string; status: FactStatus; reason: string; recordedAt: string }
export interface Fact { id: string; kind: FactKind; preferenceDomain?: PreferenceDomain; statement: string; status: FactStatus; sourceIds: string[]; updatedAt: string; version: number; history: FactRevision[] }
export type PortraitKind = 'identity'|'background'|'preference'|'experience'|'goal'|'boundary'|'note';
export interface PortraitEntry { id: string; kind: PortraitKind; statement: string; status: FactStatus; sourceIds: string[]; privacy: 'private'|'sensitive'; recordedAt: string; validFrom?: string; validTo?: string; note?: string }
export interface PersonPortrait { schema: 'hither.person.v1'; version: number; updatedAt: string; entries: PortraitEntry[]; history: Array<{version: number; recordedAt: string; entries: PortraitEntry[]}> }
export interface Person { id: string; name: string; role: string; description: string; sourceIds: string[]; portrait?: PersonPortrait }
export interface Relationship { id: string; from: string; to: string; label: string; description: string; sourceIds: string[] }
export interface LifeEvent { endDate?: string; scope?: 'milestone'|'note'; attachmentIds?: string[]; platform?: string; location?: string; id: string; date: string; title: string; description: string; category: string; personIds: string[]; sourceIds: string[] }
export interface DailyActivity { id: string; kind: 'task'|'room'|'import'|'manual'; title: string; summary: string; startAt?: string; endAt?: string; date?: string; endDate?: string; app?: string; status: TaskStatus|'recorded'; taskId?: string; roomId?: string; roomTitle?: string; lifeEventId?: string; sourceIds: string[]; sourceUrl?: string; reference?: string; demo: boolean }
export interface ActivityImportPreview { previewId: string; filename: string; sha256: string; sourceId: string; counts: {total: number; added: number; duplicates: number}; items: DailyActivity[]; expiresAt: string }
export interface ActivityImportResult { importId: string; sourceId: string; activityIds: string[]; added: number; duplicates: number; alreadyImported: boolean }
export interface ConversationMessage { id: string; senderId: string; content: string; time: string; sourceId: string; sourceIds?: string[]; externalId?: string }
export interface Conversation { id: string; title: string; personIds: string[]; kind: 'direct'|'group'; messages: ConversationMessage[]; platform?: ChatImportPlatform; accountId?: string; externalId?: string; demo?: boolean }
export interface GoalList { id: string; name: string; color: 'blue'|'orange'|'red'|'purple'|'green'|'gray'; createdAt: string; updatedAt: string }
export interface Goal { id: string; title: string; description: string; status: 'active'|'done'|'paused'; dueDate?: string; listId?: string; flagged?: boolean; completedAt?: string; createdAt?: string; updatedAt?: string; sourceIds: string[] }
export type AvatarStyle = 'pixelArt'|'notionists'|'openPeeps'|'lorelei'|'micah'|'adventurer'|'avataaars'|'bottts'|'thumbs'|'shapes';
export interface AgentProfile { id: string; name: string; role: string; instructions: string; sourceUrl?: string; connectionId?: string; avatarStyle?: AvatarStyle; avatarImage?: string; createdAt: string }
export interface Attachment { id: string; name: string; mime: string; size: number; kind: 'image'|'text'|'file'; url: string; createdAt: string }
export type AttachmentRef = Attachment;
export interface AgentRoomReaction { emoji: string; actor: 'self'; createdAt: string }
export interface AgentRoomMessage { reactions?: AgentRoomReaction[]; attachmentIds?: string[]; recipientIds?: string[]; replyToMessageId?: string; id: string; role: 'user'|'assistant'|'system'; content: string; createdAt: string; agentId?: string; taskId?: string; taskMessageId?: string; demo?: boolean }
export interface AgentRoom { forkedFrom?: {roomId: string; messageId: string}; team?: TeamConfiguration; approvalMode?: ApprovalMode | null; digitalTwinEnabled?: boolean; connectorIds?: string[]; archived?: boolean; projectId?: string; id: string; title: string; kind: 'direct'|'group'; agentIds: string[]; mode: 'demo'|'live'; createdAt: string; updatedAt: string; messages: AgentRoomMessage[]; taskIds: string[]; activeTaskId?: string; demo?: boolean }
export interface AgentRoomTaskResult { room: AgentRoom; task: Task }
export type ChatImportPlatform = 'wechat'|'wecom'|'qq'|'feishu'|'dingtalk'|'slack'|'teams'|'telegram'|'discord'|'signal'|'line'|'messenger'|'imessage'|'instagram'|'whatsapp'|'email'|'sms'|'generic';
export interface ChatImportPreview { previewId: string; platform: ChatImportPlatform; filename: string; sha256: string; accountId: string; counts: { people: number; conversations: number; messages: number; newPeople: number; newConversations: number; newMessages: number; duplicates: number }; warnings: string[]; conversations: Array<{ externalId: string; title: string; kind: 'direct'|'group'; participants: string[]; messageCount: number; messages: Array<{sender: string; content: string; time: string}> }>; expiresAt: string }
export interface ChatImportResult { importId: string; sourceId: string; conversationIds: string[]; added: { people: number; conversations: number; messages: number }; duplicates: number; alreadyImported: boolean }
export interface RuntimeCapabilities { executionNode: 'current-computer'; adapters: Array<{id: 'local-demo'|'codex-app-server'; available: boolean; version?: string; modelExecution: boolean; description: string}>; provider: {provider: ProviderSettings['provider']; model: string; api: ProviderSettings['api']; configured: boolean; textConnectionTest: ProviderSettings['lastTest'] | null; toolCompatibility: 'not_verified'; multimodalCompatibility: 'not_verified'}; features: Record<string, boolean>; limitations: string[]; openJarvis: {integration: 'design-reference'; commit: string; codeReused: false; installed: false} }
export interface TaskTrace { taskId: string; roomId?: string; mode: 'demo'|'live'; status: TaskStatus; events: TaskEvent[]; attempts: Array<{startedAt: string; endedAt: string|null; outcome: string; runtime: {adapter: string; executionNode: string; model?: string|null; provider?: string; api?: string}|null; wallClockMs: number}>; measurements: {wallClockMs: number; includesApprovalWait: true; agentRunCount: number; approvalRequestCount: number; artifactCount: number; inputTokens: null; outputTokens: null; costUsd: null; energyJoules: null; quality: 'not_assessed'}; notes: string[] }
export type TaskStatus = 'queued'|'running'|'needs_input'|'awaiting_approval'|'completed'|'failed'|'cancelled'|'interrupted';
export interface TaskReaction { value: 'up'|'down'; reason?: 'not_helpful'|'inaccurate'|'instructions'|'personal_context'|'other'; comment?: string; updatedAt: string }
export interface TaskMessage { reaction?: TaskReaction; contextEventIds?: Partial<Record<'context'|'evidence'|'personal_context',string>>; attachmentIds?: string[]; recipientIds?: string[]; replyToMessageId?: string; id: string; role: 'user'|'assistant'|'system'; content: string; createdAt: string; agentId?: string }
export interface TaskEvent { id: string; type: string; label: string; detail?: string; createdAt: string; agentId?: string }
export interface Approval { id: string; title: string; description: string; status: 'pending'|'approved'|'rejected'; details?: string }
export interface Project { id: string; name: string; kind: 'local'|'remote'; path?: string; url?: string; description: string; archived: boolean; createdAt: string; updatedAt: string; execution: {status: 'ready'|'unavailable'; reason?: string} }
export interface Task { forkedFrom?: {taskId: string; messageId: string}; revisionTaskIds?: string[]; team?: TeamConfiguration; teamRuns?: TeamRun[]; approvalMode?: ApprovalMode | null; resolvedApprovalMode?: ApprovalMode; contextUsage?: TaskContextUsage; remoteExecution?: {runId:string;computerId:string;computerName:string;status:RemoteRun['status'];dispatch:RemoteRun['dispatch'];observation:RemoteRun['observation'];cursor:number;fileCount:number;cancelRequested:boolean}; contextRequest?: ContextRequest; digitalTwinEnabled?: boolean; connectorIds?: string[]; archived?: boolean; projectId?: string; interaction?: 'chat'|'task'; connectionId?: string; id: string; title: string; prompt: string; agentIds: string[]; contextFactIds: string[]; mode: 'live'|'demo'; status: TaskStatus; createdAt: string; updatedAt: string; messages: TaskMessage[]; events: TaskEvent[]; artifactIds: string[]; approvals: Approval[]; error?: string; threadId?: string; roomId?: string }
export interface ArtifactVersion { version: number; content: string; encoding?: 'data-url'; size?: number; mime?: string; createdAt: string; author: string }
export interface Artifact { classification?: 'artifact'|'reply_snapshot'; origin?: { kind: 'workspace'|'demo'|'user'|'legacy_reply'; messageId?: string; sha256?: string; eventIds?: string[]; classifiedAt?: string }; reviewStatus?: 'pending'|'ready'; id: string; taskId: string; name: string; type: 'markdown'|'text'|'html'|'code'; content: string; encoding?: 'data-url'; size?: number; mime?: string; version: number; versions: ArtifactVersion[]; updatedAt: string }
export interface Automation { id: string; title: string; prompt: string; enabled: boolean; trigger: 'daily'|'interval'|'source_import'; time?: string; intervalMinutes?: number; agentIds: string[]; mode: 'live'|'demo'; nextRunAt?: string; lastRunAt?: string; lastTaskId?: string }
export interface ProviderSettings { provider: 'moonshot'|'deepseek'|'openai'|'openrouter'|'anthropic'|'gemini'|'qwen'|'glm'|'doubao'|'minimax'|'custom'; model: string; baseUrl: string; api: 'responses'|'chat_completions'|'messages'; appTitle?: string; hasKey: boolean; keyHint?: string; reasoningEffort: 'low'|'medium'|'high'|'max'; lastTest?: { ok: boolean; at: string; message: string } }
export interface ModelConnection extends ProviderSettings { id: string; name: string; createdAt: string; updatedAt: string }
export interface ModelConnectionList { connections: ModelConnection[]; defaultConnectionId: string }
export interface Computer { id: string; name: string; platform: string; status: 'online'|'offline'; workspace: string; codexAvailable: boolean; codexVersion?: string }
export interface Profile { avatarImage?: string; exampleTaskIds?: string[]; demoLocale?: 'zh-CN'|'en'; nationality?: string; name: string; englishName?: string; description: string; demo: boolean; selfPersonId?: string }
export interface Bootstrap { executionSettings?: ExecutionSettings; executionPolicy?: 'showcase'|'personal'; connectors?: Connector[]; attachments?: Attachment[]; defaultAgentAvatarStyle?: AvatarStyle; dailyActivities?: DailyActivity[]; projects: Project[]; version: string; profile: Profile; sources: Source[]; facts: Fact[]; people: Person[]; relationships: Relationship[]; events: LifeEvent[]; conversations: Conversation[]; goals: Goal[]; goalLists?: GoalList[]; agents: AgentProfile[]; agentRooms: AgentRoom[]; tasks: Task[]; artifacts: Artifact[]; automations: Automation[]; settings: ProviderSettings; modelConnections: ModelConnection[]; defaultConnectionId: string; computer: Computer }
export interface CreateTask { contextRequest?: ContextRequest; digitalTwinEnabled?: boolean; connectorIds?: string[]; attachmentIds?: string[]; projectId?: string; connectionId?: string; prompt: string; title?: string; agentIds?: string[]; contextFactIds?: string[]; mode: 'live'|'demo' }

/** A user-selected approval policy; resolved once for each running attempt. */
export type ApprovalMode = 'ask' | 'auto' | 'full';
export interface ExecutionSettings { approvalMode: ApprovalMode }
/** Only measurements reported by the runtime; null means unavailable. */
export interface TaskContextUsage { agentId?: string; model?: string; threadId?: string; usedTokens: number | null; contextWindow: number | null; inputTokens: number | null; outputTokens: number | null; totalTokens: number | null; updatedAt: string; source: 'runtime' }

export interface TaskRevisionResult { task: Task; room?: AgentRoom; reused: boolean; startError?: {code: string; message: string} }
