// Reproduce notices from the locally installed production dependencies. No network or user data access.
import { readFileSync, readdirSync, existsSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
if (args.length > 1 || (args.length && args[0] !== '--website')) throw new Error('Usage: node scripts/license-notices.mjs [--website]');
const website = args[0] === '--website';
const packageRoot = website ? path.join(root, 'website') : root;
const read = file => readFileSync(path.join(packageRoot, file), 'utf8');
const lock = JSON.parse(read('package-lock.json'));
const sections = [`Installed ${website ? 'website' : 'runtime'} production-dependency license snapshot\n\nGenerated by scripts/license-notices.mjs${website ? ' --website' : ''} from ${website ? 'website/' : ''}package-lock.json and installed packages.\nOptional packages depend on the installation platform. Package artwork and code can have different terms.\n`];
let count = 0;
for (const [relative, entry] of Object.entries(lock.packages).sort(([a], [b]) => a.localeCompare(b))) {
  if (!relative || entry.dev || !existsSync(path.join(packageRoot, relative, 'package.json'))) continue;
  if (!relative.startsWith('node_modules/') || relative.split('/').includes('..')) throw new Error('Invalid dependency path');
  const manifest = JSON.parse(read(`${relative}/package.json`));
  const files = readdirSync(path.join(packageRoot, relative)).filter(name => /^(license|licence|copying|notice)([.\-]|$)/i.test(name) && statSync(path.join(packageRoot, relative, name)).isFile()).sort();
  const license = manifest.license || manifest.licenses?.map(item => item.type).join(', ') || entry.license || 'See upstream notice';
  const repository = typeof manifest.repository === 'string' ? manifest.repository : manifest.repository?.url;
  sections.push(`\n${'='.repeat(72)}\n${manifest.name}@${manifest.version}\nLicense metadata: ${license}\nSource: ${repository || manifest.homepage || ''}\n`);
  if (files.length) for (const file of files) sections.push(`\n--- ${file} ---\n${read(`${relative}/${file}`)}\n`);
  else {
    const override = `docs/licenses/${manifest.name.replaceAll('/', '_')}.txt`;
    if (existsSync(path.join(root, override))) sections.push(readFileSync(path.join(root, override), 'utf8'));
    else {
      const readme = readdirSync(path.join(packageRoot, relative)).find(name => /^readme/i.test(name) && statSync(path.join(packageRoot, relative, name)).isFile());
      const content = readme ? read(`${relative}/${readme}`) : '';
      const at = content.search(/^(?:#+\s*)?License\s*$/im);
      sections.push(at >= 0 ? content.slice(at) : `No separate license file in this platform package. Refer to the parent project's retained notice and upstream terms (${license}).\n`);
    }
  }
  count++;
}
writeFileSync(path.join(root, `docs/licenses/${website ? 'website' : 'runtime'}-dependencies.txt`), sections.join('\n'));
console.log(`Recorded notices for ${count} installed ${website ? 'website' : 'runtime'} production packages.`);
