import { useCallback, useEffect, useRef, useState } from 'react';
import { Button } from '@openai/apps-sdk-ui/components/Button';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Textarea } from '@openai/apps-sdk-ui/components/Textarea';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Checkbox } from '@openai/apps-sdk-ui/components/Checkbox';
import { Plus, Edit, Reload, ArrowLeft, ChevronDown } from '@openai/apps-sdk-ui/components/Icon';
import type { Bootstrap } from '../../shared/contracts';
import type { ImConnection } from '../../shared/im';
import type { AgentResource, AgentResourceInput, AgentResourceKind, AgentResourceAction, AgentResourcePolicy, AgentResourceDecision, AgentResourceState } from '../../shared/agent-resources';
import { api, write, messageOf } from '../api';
import { ErrorNotice, Field } from '../components';
import { t, getLocale } from '../i18n';
import './agent-resources.css';

const resourceActions: Record<AgentResourceKind, AgentResourceAction[]> = { phone: ['read', 'draft', 'send', 'call'], email: ['read', 'draft', 'send'], payment: ['read', 'draft', 'pay'], im: ['read', 'draft', 'send'] };
const kinds = (): { value: AgentResourceKind; label: string }[] => [{ value: 'phone', label: t('手机号', 'Phone number') }, { value: 'email', label: t('邮箱', 'Email') }, { value: 'payment', label: t('付款账号', 'Payment account') }, { value: 'im', label: t('通信账号', 'Messaging account') }];
function actionLabel(action: AgentResourceAction, kind: AgentResourceKind) { return ({ read: kind === 'payment' ? t('查询余额', 'Check balance') : t('读取内容', 'Read content'), draft: kind === 'payment' ? t('准备付款草稿', 'Prepare payment draft') : t('准备草稿', 'Prepare drafts'), send: t('对外发送', 'Send messages'), call: t('拨打电话', 'Make calls'), pay: t('付款', 'Pay') })[action]; }
function stateLabel(state: AgentResourceState) { return ({ pending: t('待接通', 'Not connected'), ready: t('检查通过', 'Verified by tool'), simulated: t('模拟检查', 'Simulated check'), unavailable: t('暂不可用', 'Unavailable'), error: t('检查失败', 'Check failed'), disabled: t('已停用', 'Disabled') })[state]; }
function defaultPolicy(): AgentResourcePolicy { return { read: 'allow', draft: 'allow', send: 'deny', call: 'deny', pay: 'deny', allowedTargets: [] }; }
function timestamp(value: string) { return new Date(value).toLocaleString(getLocale(), { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); }

function ResourceForm({ resource, agentId, connections, busy, onSave, onCancel }: { resource?: AgentResource; agentId: string; connections: ImConnection[]; busy: boolean; onSave: (value: AgentResourceInput) => Promise<void>; onCancel: () => void }) {
  const [draft, setDraft] = useState<AgentResourceInput>(() => resource ? { agentId, kind: resource.kind, name: resource.name, identifier: resource.identifier, provider: resource.provider, adapter: resource.adapter, command: resource.command, connectionId: resource.connectionId, policy: resource.policy, enabled: resource.enabled, revision: resource.revision } : { agentId, kind: 'phone', name: '', identifier: '', provider: '', adapter: 'unconnected', policy: defaultPolicy(), enabled: true });
  const [targets, setTargets] = useState(resource?.policy.allowedTargets.join('\n') || '');
  const [currency, setCurrency] = useState(resource?.policy.budget?.currency || 'CNY');
  const [limit, setLimit] = useState(resource?.policy.budget?.perPaymentLimit || '');
  const update = <K extends keyof AgentResourceInput>(key: K, value: AgentResourceInput[K]) => setDraft(current => ({ ...current, [key]: value }));
  const policy = (key: AgentResourceAction, value: 'allow' | 'deny' | 'confirm') => setDraft(current => ({ ...current, policy: { ...current.policy, [key]: value } }));
  const connection = connections.find(item => item.id === draft.connectionId);
  const sourceOptions = [{ value: 'unconnected', label: t('稍后接通', 'Connect later') }, { value: 'local-cli', label: t('本机资源工具', 'Local resource tool') }, ...(draft.kind === 'im' ? [{ value: 'im-connection', label: t('已有通信连接', 'Existing messaging connection') }] : [])];
  const identifierLabel = draft.kind === 'phone' ? t('手机号', 'Phone number') : draft.kind === 'email' ? t('邮箱地址', 'Email address') : draft.kind === 'payment' ? t('服务商中的账号别名', 'Account alias at provider') : t('工具中的账号标识', 'Account ID in the tool');
  return <form className="agent-resource-form" onSubmit={event => {
    event.preventDefault();
    const permissions = { ...draft.policy, allowedTargets: targets.split('\n').map(value => value.trim()).filter(Boolean) };
    if (draft.kind === 'payment' && limit.trim()) permissions.budget = { currency: currency.trim().toUpperCase(), perPaymentLimit: limit.trim() }; else delete permissions.budget;
    void onSave({ ...draft, policy: permissions });
  }}>
    <div className="agent-resource-form-title"><Button type="button" size="sm" color="secondary" variant="ghost" uniform aria-label={t('返回资源列表', 'Back to resources')} disabled={busy} onClick={onCancel}><ArrowLeft /></Button><h4>{resource ? t('编辑资源绑定', 'Edit resource binding') : t('添加资源', 'Add a resource')}</h4></div>
    <fieldset disabled={busy}>
      <div className="agent-resource-pair"><Field label={t('资源类型', 'Resource type')}><Select value={draft.kind} options={kinds()} onChange={option => { setDraft(current => ({ ...current, kind: option.value, identifier: '', provider: '', adapter: 'unconnected', command: undefined, connectionId: undefined, policy: defaultPolicy() })); setTargets(''); setLimit(''); }} /></Field><Field label={t('名称', 'Name')}><Input aria-label={t('资源名称', 'Resource name')} required maxLength={100} placeholder={t('例如：工作邮箱', 'For example: Work email')} value={draft.name} onChange={event => update('name', event.target.value)} /></Field></div>
      <Field label={t('接入方式', 'Connection method')}><Select value={draft.adapter} options={sourceOptions} onChange={option => setDraft(current => ({ ...current, adapter: option.value as AgentResourceInput['adapter'], command: undefined, connectionId: undefined, ...(option.value === 'im-connection' ? { provider: '', identifier: '' } : {}) }))} /></Field>
      {draft.adapter === 'im-connection' ? <>
        {connections.length ? <Field label={t('选择已有连接', 'Choose an existing connection')}><Select value={draft.connectionId || ''} options={connections.map(item => ({ value: item.id, label: `${item.name} (${item.channel})` }))} placeholder={t('选择通信连接', 'Choose a connection')} onChange={option => { const item = connections.find(value => value.id === option.value)!; setDraft(current => ({ ...current, connectionId: item.id, identifier: item.accountId, provider: item.channel })); }} /></Field> : <p className="agent-resource-hint">{t('还没有通信连接。请先到聊天记录中连接本机通信工具。', 'No messaging connections yet. Connect a local messaging tool from Chat history first.')}</p>}
        {connection && <div className="agent-resource-connection"><strong>{connection.accountId}</strong><span className="agent-resource-inline-meta"><span>{connection.channel}</span><span>{connection.target}</span></span><small>{t('绑定后沿用此账号、会话和实际检查结果。', 'This binding uses the account, conversation, and its real check result.')}</small></div>}
      </> : <div className="agent-resource-pair"><Field label={identifierLabel}><Input aria-label={identifierLabel} required type={draft.kind === 'email' ? 'email' : 'text'} maxLength={200} placeholder={draft.kind === 'phone' ? '+8613800000000' : draft.kind === 'email' ? 'name@example.com' : draft.kind === 'payment' ? t('例如：工作预算账户', 'For example: Work budget account') : 'account-alias'} value={draft.identifier} onChange={event => update('identifier', event.target.value)} /></Field><Field label={t('服务商', 'Provider')}><Input aria-label={t('资源服务商', 'Resource provider')} required maxLength={100} placeholder={draft.kind === 'email' ? 'Gmail' : draft.kind === 'payment' ? 'Stripe' : t('账号所属服务商', 'Account provider')} value={draft.provider} onChange={event => update('provider', event.target.value)} /></Field></div>}
      {draft.adapter === 'local-cli' && <Field label={t('本机工具路径', 'Local executable path')} hint={t('登录凭据由原工具保管。检查只读取账号与能力。', 'Credentials stay in the original tool. Checks only read account capabilities.')}><Input aria-label={t('资源工具路径', 'Resource executable path')} required maxLength={1000} placeholder="/absolute/path/to/resource-tool" value={draft.command || ''} onChange={event => update('command', event.target.value)} /></Field>}
      {draft.kind === 'payment' && <p className="agent-resource-hint">{t('只填写服务商中的账号别名。卡号、验证码和密钥留在原工具。', 'Use a provider account alias. Keep card numbers, verification codes, and keys in the original tool.')}</p>}
      <div className="agent-resource-policy"><h4>{t('授权范围', 'Permission scope')}</h4><div className="agent-resource-checks"><Checkbox checked={draft.policy.read === 'allow'} onCheckedChange={value => policy('read', value ? 'allow' : 'deny')} label={actionLabel('read', draft.kind)} /><Checkbox checked={draft.policy.draft === 'allow'} onCheckedChange={value => policy('draft', value ? 'allow' : 'deny')} label={actionLabel('draft', draft.kind)} /></div>
        {resourceActions[draft.kind].filter(action => ['send', 'call', 'pay'].includes(action)).map(action => <div className="agent-resource-permission" key={action}><span>{actionLabel(action, draft.kind)}</span><Select value={draft.policy[action]} options={[{ value: 'deny', label: t('不允许', 'Not allowed') }, { value: 'confirm', label: t('每次由我确认', 'Ask me each time') }]} onChange={option => policy(action, option.value as 'deny' | 'confirm')} /></div>)}
        {draft.kind === 'payment' && <div className="agent-resource-pair"><Field label={t('币种', 'Currency')}><Input aria-label={t('预算币种', 'Budget currency')} maxLength={3} required={draft.policy.pay === 'confirm'} value={currency} onChange={event => setCurrency(event.target.value.toUpperCase())} placeholder="CNY" /></Field><Field label={t('单笔付款上限', 'Per-payment limit')}><Input aria-label={t('单笔付款上限', 'Per-payment limit')} inputMode="decimal" required={draft.policy.pay === 'confirm'} placeholder="100.00" value={limit} onChange={event => setLimit(event.target.value)} /></Field></div>}
        <Field label={t('限定对象（可选）', 'Allowed recipients (optional)')} hint={t('每行填写一个准确标识；留空时仍逐次确认。', 'One exact recipient ID per line. Empty still requires confirmation for each action.')}><Textarea aria-label={t('资源授权对象', 'Allowed resource recipients')} rows={2} maxLength={10000} placeholder={draft.kind === 'email' ? 'teammate@example.com' : t('号码、收件人或商家标识', 'Phone, recipient, or merchant ID')} value={targets} onChange={event => setTargets(event.target.value)} /></Field>
      </div>
    </fieldset>
    {draft.adapter === 'local-cli' && <details className="agent-resource-protocol"><summary>{t('接入工具说明', 'Tool integration details')}<ChevronDown /></summary><p>{t('工具需实现 secondu.resources.v1 协议，通过标准输入接收检查请求并返回 JSON。路径直接执行，不拼接命令；账号与能力必须与请求匹配。', 'Implement secondu.resources.v1: read the probe request from stdin and return JSON. The executable runs directly; account and capabilities must match the request.')}</p><pre>{`{"protocol":"secondu.resources.v1","action":"probe","requestId":"…","resourceId":"…","agentId":"…","kind":"${draft.kind}","identifier":"…","provider":"…","connected":true,"capabilities":["read","draft"]}`}</pre><p>{t('原样回传请求中的身份字段。模拟工具须另带 "simulated": true；原始输出和凭据不会写入资源记录。检查有效期为 15 分钟。', 'Echo the identity fields from the request. Simulators must include "simulated": true. Raw output and credentials are not stored in the resource. Checks expire after 15 minutes.')}</p></details>}
    <div className="agent-resource-actions"><Button type="button" color="secondary" variant="ghost" disabled={busy} onClick={onCancel}>{t('取消', 'Cancel')}</Button><Button type="submit" color="primary" loading={busy} disabled={busy || !draft.name.trim() || !draft.identifier.trim() || !draft.provider.trim() || (draft.adapter === 'im-connection' && !draft.connectionId) || (draft.adapter === 'local-cli' && !draft.command?.trim())}>{t('保存绑定', 'Save binding')}</Button></div>
  </form>;
}

function PermissionCheck({ resource, busy, onCheck }: { resource: AgentResource; busy: boolean; onCheck: (body: { action: AgentResourceAction; target?: string; amount?: string; currency?: string }) => Promise<AgentResourceDecision | undefined> }) {
  const [action, setAction] = useState<AgentResourceAction>(resource.kind === 'payment' ? 'pay' : 'send');
  const [target, setTarget] = useState(resource.connectionTarget || ''), [amount, setAmount] = useState('');
  const [result, setResult] = useState<AgentResourceDecision>();
  const outbound = ['send', 'call', 'pay'].includes(action);
  return <details className="agent-resource-rule-check"><summary>{t('检查授权规则', 'Check permission rules')}<ChevronDown /></summary><div><Field label={t('操作', 'Action')}><Select value={action} options={resourceActions[resource.kind].map(value => ({ value, label: actionLabel(value, resource.kind) }))} onChange={option => { setAction(option.value); setResult(undefined); }} /></Field>{outbound && <Field label={t('操作对象', 'Recipient')}><Input aria-label={t('待检查的操作对象', 'Recipient to check')} value={target} placeholder={t('填写准确标识', 'Enter an exact ID')} onChange={event => { setTarget(event.target.value); setResult(undefined); }} /></Field>}{action === 'pay' && <Field label={t(`金额（${resource.policy.budget?.currency || 'CNY'}）`, `Amount (${resource.policy.budget?.currency || 'CNY'})`)}><Input aria-label={t('待检查的付款金额', 'Payment amount to check')} inputMode="decimal" value={amount} onChange={event => { setAmount(event.target.value); setResult(undefined); }} /></Field>}<Button size="sm" color="secondary" variant="outline" disabled={busy || (outbound && !target.trim()) || (action === 'pay' && !amount.trim())} onClick={async () => { setResult(await onCheck({ action, ...(outbound ? { target: target.trim() } : {}), ...(action === 'pay' ? { amount: amount.trim(), currency: resource.policy.budget?.currency || 'CNY' } : {}) })); }}>{t('仅检查规则', 'Check rules only')}</Button>{result && <p role="status" className="agent-resource-check-result" data-decision={result.decision}>{result.message}</p>}</div></details>;
}

export function AgentResources({ data, agentId, isSelf, onRefresh }: { data: Bootstrap; agentId: string; isSelf: boolean; onRefresh: () => Promise<void> }) {
  const subject = isSelf ? 'hither' : agentId;
  const ownerName = isSelf ? data.profile.name : data.agents.find(item => item.id === agentId)?.name || t('这个 Agent', 'This agent');
  const [resources, setResources] = useState<AgentResource[]>([]), [connections, setConnections] = useState<ImConnection[]>([]);
  const [editing, setEditing] = useState<AgentResource | 'new'>(), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const panel = useRef<HTMLElement>(null);
  const editingKey = editing === 'new' ? 'new' : editing?.id;
  useEffect(() => { panel.current?.scrollTo({ top: 0 }); }, [editingKey]);
  const load = useCallback(async () => { const [items, links] = await Promise.all([api<AgentResource[]>(`/agent-resources?agentId=${encodeURIComponent(subject)}`), api<ImConnection[]>('/im-connections')]); return { items, links }; }, [subject]);
  useEffect(() => { let cancelled = false; setLoading(true); setEditing(undefined); setResources([]); setError(''); setNotice(''); load().then(({ items, links }) => { if (!cancelled) { setResources(items); setConnections(links); } }).catch(reason => { if (!cancelled) setError(messageOf(reason)); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [load]);
  async function perform<T,>(operation: () => Promise<T>): Promise<T | undefined> { setBusy(true); setError(''); setNotice(''); try { return await operation(); } catch (reason) { setError(messageOf(reason)); } finally { setBusy(false); } }
  function replace(resource: AgentResource) { setResources(current => current.some(item => item.id === resource.id) ? current.map(item => item.id === resource.id ? resource : item) : [...current, resource]); }
  async function save(value: AgentResourceInput) { await perform(async () => { const existing = editing && editing !== 'new' ? editing : undefined; replace(await write<AgentResource>(existing ? `/agent-resources/${existing.id}` : '/agent-resources', value, existing ? 'PUT' : 'POST')); setEditing(undefined); setNotice(t('已保存', 'Saved')); try { await onRefresh(); } catch { setNotice(t('已保存，请刷新查看。', 'Saved. Refresh to view the update.')); } }); }
  return <section className="agent-resources" ref={panel} aria-label={t('身份与权限', 'Identity and permissions')}>
    <header className="agent-resources-heading"><div><h3>{t('身份与权限', 'Identity and permissions')}</h3><p>{t(`为${ownerName}绑定可使用的账号，并限定每项操作。`, `Bind accounts for ${ownerName} and set their permissions.`)}</p></div>{!editing && <Button size="sm" color="secondary" variant="outline" disabled={busy || loading} onClick={() => { setEditing('new'); setError(''); setNotice(''); }}><Plus />{t('添加资源', 'Add resource')}</Button>}</header>
    {loading ? <p role="status" className="agent-resource-hint">{t('正在读取资源…', 'Loading resources…')}</p> : editing ? <ResourceForm key={editing === 'new' ? `new-${subject}` : `${editing.id}-${editing.revision}`} resource={editing === 'new' ? undefined : editing} agentId={subject} connections={connections} busy={busy} onSave={save} onCancel={() => { setEditing(undefined); setError(''); }} /> : <>
      {!resources.length && !error && <div className="agent-resources-empty"><strong>{t('还没有绑定资源', 'No resources bound yet')}</strong><p>{t('可以添加手机号、邮箱、付款账号，或选用已有通信连接。', 'Add a phone, email, payment account, or an existing messaging connection.')}</p></div>}
      <div className="agent-resource-list">{resources.map(resource => <article className="agent-resource-card" key={`${resource.id}-${resource.revision}`}>
        <header><div><span className="agent-resource-kind"><span>{kinds().find(item => item.value === resource.kind)?.label}</span><span>{resource.provider}</span></span><h4>{resource.name}</h4><p className="agent-resource-identifier">{resource.identifier}</p></div><span className={`agent-resource-state is-${resource.status}`}>{resource.status === 'pending' && resource.adapter !== 'unconnected' ? t('待检查', 'Not checked') : stateLabel(resource.status)}</span></header>
        <p className="agent-resource-status">{resource.statusMessage}</p>{resource.checkedAt && <small className="agent-resource-checked">{t('上次检查 ', 'Last checked ')}{timestamp(resource.checkedAt)}</small>}
        {!!resource.capabilities.length && <p className="agent-resource-capabilities">{t('工具报告：', 'Tool reports: ')}{resource.capabilities.map(action => actionLabel(action, resource.kind)).join(t('、', ', '))}</p>}
        <div className="agent-resource-summary">{resourceActions[resource.kind].map(action => <span key={action}>{actionLabel(action, resource.kind)}<strong>{resource.policy[action] === 'deny' ? t('不允许', 'Not allowed') : resource.policy[action] === 'confirm' ? t('每次确认', 'Ask each time') : t('允许', 'Allowed')}</strong></span>)}{resource.policy.budget && <span>{t('单笔上限', 'Per-payment limit')}<strong>{resource.policy.budget.currency} {resource.policy.budget.perPaymentLimit}</strong></span>}</div>
        {resource.policy.allowedTargets.length > 0 && <p className="agent-resource-targets">{t('限定对象：', 'Allowed recipients: ')}{resource.policy.allowedTargets.join(t('、', ', '))}</p>}
        <footer><div><Button size="sm" color="secondary" variant="ghost" disabled={busy} onClick={() => { setEditing(resource); setError(''); setNotice(''); }}><Edit />{t('编辑', 'Edit')}</Button><Button size="sm" color="secondary" variant="ghost" disabled={busy} onClick={() => void perform(async () => { replace(await write<AgentResource>(`/agent-resources/${resource.id}/enabled`, { revision: resource.revision, enabled: !resource.enabled })); })}>{resource.enabled ? t('停用绑定', 'Disable binding') : t('启用绑定', 'Enable binding')}</Button></div><Button size="sm" color="secondary" variant="outline" disabled={busy || !resource.enabled || resource.adapter === 'unconnected'} title={resource.adapter === 'unconnected' ? t('先编辑并选择接入方式', 'Choose a connection method first') : undefined} onClick={() => void perform(async () => { replace(await write<AgentResource>(`/agent-resources/${resource.id}/probe`)); })}><Reload />{t('检查账号', 'Check account')}</Button></footer>
        <PermissionCheck resource={resource} busy={busy} onCheck={body => perform(() => write<AgentResourceDecision>(`/agent-resources/${resource.id}/check-permission`, { ...body, agentId: subject }))} />
      </article>)}</div>
    </>}
    {notice && <p role="status" className="agent-resource-notice">{notice}</p>}<ErrorNotice error={error} />
    {!editing && <p className="agent-resources-footnote">{t('账号由原工具保管。这里管理绑定、检查能力与授权规则；发送、拨号和付款仍需逐次确认。', 'Accounts stay in their original tools. Manage bindings, capability checks, and permissions here. Sending, calling, and paying require confirmation each time.')}</p>}
  </section>;
}
