import { useEffect, useRef, useState } from 'react';
import { Button, CopyButton } from '@openai/apps-sdk-ui/components/Button';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Textarea } from '@openai/apps-sdk-ui/components/Textarea';
import { Checkbox } from '@openai/apps-sdk-ui/components/Checkbox';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Badge } from '@openai/apps-sdk-ui/components/Badge';
import { ArrowRight, Download, Plus } from '@openai/apps-sdk-ui/components/Icon';
import QRCode from 'qrcode';
import type { AgentProfile, Bootstrap } from '../../shared/contracts';
import type { Delegation, DelegationAccess, DelegationDraft, DelegationList, DelegationPurpose } from '../../shared/delegation-types';
import { delegationPurposes } from '../../shared/delegation.mjs';
import { api, write, messageOf } from '../api';
import { t } from '../i18n';
import { Dialog, ErrorNotice, Field, when } from '../components';
import { ConnectionSelect } from '../models/ConnectionSelect';
import { compactSelectProps } from '../compactSelect';
import { AgentAvatar } from './AgentIdentity';
import './agent-sharing.css';

const purposeIds=Object.keys(delegationPurposes) as DelegationPurpose[];
const purposeName=(purpose:DelegationPurpose)=>t(delegationPurposes[purpose].zh,delegationPurposes[purpose].en);
const dateInput=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'':new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const futureDate=()=>new Date(Date.now()+7*86400000).toISOString();
const taskState=(state:string)=>({TASK_STATE_AUTH_REQUIRED:t('待你审批','Needs your approval'),TASK_STATE_SUBMITTED:t('已接收','Received'),TASK_STATE_WORKING:t('处理中','Working'),TASK_STATE_COMPLETED:t('已完成','Completed'),TASK_STATE_FAILED:t('未完成','Failed'),TASK_STATE_CANCELED:t('已取消','Canceled'),TASK_STATE_REJECTED:t('未批准','Declined')}[state]||state);
function initialDraft(agent:AgentProfile,data:Bootstrap):DelegationDraft{return {name:agent.name,description:agent.role,instructions:'',approvedContext:'',serviceRules:t('仅提供此范围内的文本建议；信息不足时明确说明，不代表本人承诺或执行。','Provide text advice only within this scope. State what is missing. Do not make commitments or act on my behalf.'),purposes:['consultation'],approvalPolicy:'every_call',connectionId:agent.connectionId||data.defaultConnectionId||'',expiresAt:futureDate(),maxCalls:20,maxInputChars:4000,maxOutputTokens:1500};}

export function AgentSharingDialog({agent,data,onClose}:{agent:AgentProfile;data:Bootstrap;onClose:()=>void}) {
  const [records,setRecords]=useState<DelegationList>();const [selectedId,setSelectedId]=useState('');const [draft,setDraft]=useState<DelegationDraft>(()=>initialDraft(agent,data));
  const [tab,setTab]=useState<'scope'|'access'|'requests'>('scope');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [contextApproved,setContextApproved]=useState(false);const [rulesApproved,setRulesApproved]=useState(false);const [automaticApproved,setAutomaticApproved]=useState(false);
  const [recipient,setRecipient]=useState('');const [grantCalls,setGrantCalls]=useState(5);const [grantExpires,setGrantExpires]=useState(futureDate);const [grantPurposes,setGrantPurposes]=useState<DelegationPurpose[]>(['consultation']);const [allowCalls,setAllowCalls]=useState(true);const [access,setAccess]=useState<DelegationAccess>();const [qr,setQR]=useState('');
  const mounted=useRef(true),listSequence=useRef(0);
  const selected=records?.delegations.find(item=>item.id===selectedId);const owned=records?.delegations.filter(item=>item.originAgentId===agent.id)||[];
  const readOnly=data.executionPolicy==='showcase'||records?.readOnly;const published=selected?.status==='published'&&!!selected.snapshot&&Date.parse(selected.snapshot.expiresAt)>Date.now();
  const pending=selected?.calls.filter(call=>call.task.status.state==='TASK_STATE_AUTH_REQUIRED').length||0;
  const connection=(records?.connections||data.modelConnections).find(item=>item.id===draft.connectionId);
  async function reload(signal?:AbortSignal){const sequence=++listSequence.current,result=await api<DelegationList>('/delegations',{signal});if(mounted.current&&sequence===listSequence.current)setRecords(result);return result;}
  function choose(share?:Delegation){setSelectedId(share?.id||'');setDraft(share?structuredClone(share.draft):initialDraft(agent,data));setAccess(undefined);setQR('');setContextApproved(false);setRulesApproved(false);setAutomaticApproved(false);setError('');setNotice('');setTab('scope');if(share?.snapshot){setGrantPurposes([...share.snapshot.purposes]);setGrantExpires(share.snapshot.expiresAt);setGrantCalls(Math.min(5,share.snapshot.maxCalls));}}
  useEffect(()=>{mounted.current=true;let alive=true;const sequence=++listSequence.current;api<DelegationList>('/delegations').then(result=>{if(!alive||sequence!==listSequence.current)return;setRecords(result);const first=result.delegations.find(item=>item.originAgentId===agent.id);if(first)choose(first);}).catch(err=>{if(alive)setError(messageOf(err));});return()=>{alive=false;mounted.current=false;listSequence.current++;};},[agent.id]);
  useEffect(()=>{
    if(tab!=='requests')return;
    let disposed=false,inFlight=false;const controller=new AbortController();
    async function refreshVisible(){
      if(disposed||inFlight||document.hidden)return;
      inFlight=true;
      try{await reload(controller.signal);}catch(err){if(!disposed&&!controller.signal.aborted)setError(messageOf(err));}finally{inFlight=false;}
    }
    void refreshVisible();
    const timer=setInterval(()=>void refreshVisible(),5000),visible=()=>{if(!document.hidden)void refreshVisible();};
    document.addEventListener('visibilitychange',visible);window.addEventListener('focus',visible);
    return()=>{disposed=true;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);window.removeEventListener('focus',visible);};
  },[tab,agent.id]);
  useEffect(()=>{let alive=true;if(access)void QRCode.toDataURL(access.url,{width:280,margin:2}).then(value=>{if(alive)setQR(value);}).catch(err=>setError(messageOf(err)));return()=>{alive=false;};},[access]);
  function update<K extends keyof DelegationDraft>(key:K,value:DelegationDraft[K]){setDraft(current=>({...current,[key]:value}));setContextApproved(false);setRulesApproved(false);setAutomaticApproved(false);setNotice('');}
  function togglePurpose(value:DelegationPurpose,checked:boolean){update('purposes',checked?[...draft.purposes,value]:draft.purposes.filter(p=>p!==value));}
  async function action(run:()=>Promise<void>){if(busy||readOnly)return;setBusy(true);setError('');setNotice('');try{await run();}catch(err){setError(messageOf(err));}finally{setBusy(false);}}
  async function save(){const value=await write<Delegation>(selectedId?`/delegations/${selectedId}`:'/delegations',{...draft,originAgentId:agent.id,...(selected?{expectedRevision:selected.draftRevision}:{})},selectedId?'PUT':'POST');setSelectedId(value.id);await reload();return value;}
  async function publish(){const saved=await save();await write(`/delegations/${saved.id}/publish`,{expectedRevision:saved.draftRevision,contextApproved,rulesApproved,automaticApproved});const result=await reload(),current=result.delegations.find(item=>item.id===saved.id)!;setGrantPurposes([...current.snapshot!.purposes]);setGrantExpires(current.snapshot!.expiresAt);setGrantCalls(Math.min(5,current.snapshot!.maxCalls));setAccess(undefined);setQR('');setTab('access');setNotice(t('能力已在本机发布。为接收者创建一份授权即可使用。','Published on this device. Create a recipient grant to use it.'));}
  const complete=!!draft.name.trim()&&!!draft.description.trim()&&!!draft.instructions.trim()&&!!draft.serviceRules.trim()&&draft.purposes.length>0&&!!draft.connectionId;
  return <Dialog title={t('分享受限分身','Share a limited delegate')} className="ag-sharing-dialog" onClose={()=>{if(!busy)onClose();}}>
    <div className="ag-sharing-top"><div className="ag-sharing-person"><AgentAvatar agent={agent} size={40}/><div><strong>{agent.name}</strong><p>{t('将一项能力和你允许使用的背景分享出去。','Share a capability and the context you authorize.')}</p></div></div><Badge variant="outline" color="secondary" size="sm">{t('本机可用','Local access')}</Badge></div>
    {readOnly?<div className="ag-sharing-readonly"><h3>{t('在自己的空间配置分享','Configure sharing in your own space')}</h3><p>{t('示例空间只供查看。切换到自己的空间，连接模型后，可以发布能力、创建接收者授权并处理请求。','The example space is read only. Switch to your own space and connect a model to publish capabilities, grant access and review requests.')}</p></div>:<>
      {owned.length>0&&<div className="ag-sharing-picker"><Select {...compactSelectProps} value={selectedId||'new'} options={[...owned.map(item=>({value:item.id,label:item.draft.name})),{value:'new',label:t('新建一项能力','New capability')}]} onChange={item=>choose(owned.find(value=>value.id===item.value))} disabled={busy}/><Button size="sm" color="secondary" variant="ghost" disabled={busy} onClick={()=>choose()}><Plus/>{t('新建','New')}</Button></div>}
      <nav className="ag-sharing-tabs" aria-label={t('能力分享设置','Sharing settings')}>{([{id:'scope',label:t('能力与边界','Scope')},{id:'access',label:t('接收者授权','Access')},{id:'requests',label:t(`请求${pending?`（${pending}）`:''}`,`Requests${pending?` (${pending})`:''}`)}] as const).map(item=><button key={item.id} type="button" aria-pressed={tab===item.id} onClick={()=>{setTab(item.id);setError('');}}>{item.label}</button>)}</nav>
      <div className="ag-sharing-content">
      {tab==='scope'&&<div className="ag-sharing-form">
        {published&&<p className="ag-sharing-hint">{t(`当前授权使用已发布版本 ${selected!.version}。修改保存为草稿后，需再次发布才会生效。`,`Current grants use published version ${selected!.version}. Draft changes take effect after you publish again.`)}</p>}
        <div className="ag-sharing-pair"><Field label={t('能力名字','Capability name')}><Input value={draft.name} onChange={e=>update('name',e.target.value)} maxLength={80} disabled={busy}/></Field><Field label={t('使用的模型','Model')}><ConnectionSelect value={draft.connectionId} includeInherit={false} connections={records?.connections||data.modelConnections} onChange={value=>update('connectionId',value)} disabled={busy}/></Field></div>
        {!connection?.hasKey&&<p className="ag-sharing-hint">{t('发布前需在设置中完成这条模型连接。','Complete this model connection in Settings before publishing.')}</p>}
        <Field label={t('向接收者介绍这项能力','Introduction for recipients')}><Input value={draft.description} onChange={e=>update('description',e.target.value)} maxLength={500} placeholder={t('例如：帮产品团队评审早期原型','For example: review early product prototypes')} disabled={busy}/></Field>
        <Field label={t('这份分身具体做什么','Instructions for this delegate')} hint={t('只填写你准备分享的能力范围。','Describe only the capability you intend to share.')}><Textarea value={draft.instructions} onChange={e=>update('instructions',e.target.value)} maxLength={6000} rows={3} disabled={busy} placeholder={t('例如：检查用户流程，指出信息不足之处，给出可验证的改进建议。','For example: examine user flows, identify missing information and suggest testable improvements.')}/></Field>
        <Field label={t('允许它使用的脱敏上下文','Approved, redacted context')} hint={t('可填经验、方法、偏好或案例摘要。只使用本页明确填写的内容；请移除身份细节和敏感信息。','Add experience, methods, preferences or case summaries. Only the content explicitly entered on this page is used; remove identity details and sensitive information.')}><Textarea value={draft.approvedContext} onChange={e=>update('approvedContext',e.target.value)} maxLength={12000} rows={4} disabled={busy} placeholder={t('逐项写明你允许接收者调用时使用的内容。','Write the context that recipients may use when calling this delegate.')}/></Field>
        <fieldset className="ag-sharing-purposes"><legend>{t('允许的服务用途','Allowed purposes')}</legend>{purposeIds.map(p=><Checkbox key={p} label={purposeName(p)} checked={draft.purposes.includes(p)} onCheckedChange={checked=>togglePurpose(p,checked)} disabled={busy}/>)}</fieldset>
        <p className="ag-sharing-hint">{t('匹配与交易当前只生成建议或意向文本；联系、付款与履约由本人处理。','Matching and transaction requests currently produce suggestions or inquiry text. The owner handles outreach, payments and fulfillment.')}</p>
        <Field label={t('服务规则与不处理的事项','Service rules and exclusions')}><Textarea value={draft.serviceRules} onChange={e=>update('serviceRules',e.target.value)} rows={3} maxLength={3000} disabled={busy}/></Field>
        <div className="ag-sharing-pair"><Field label={t('调用方式','Call approval')}><Select {...compactSelectProps} value={draft.approvalPolicy} options={[{value:'every_call',label:t('每次由我审批','Approve every call')},{value:'automatic',label:t('按已发布范围自动回答','Reply automatically within scope')}]} onChange={item=>update('approvalPolicy',item.value as DelegationDraft['approvalPolicy'])} disabled={busy}/></Field><Field label={t('能力有效期','Capability expires')}><Input type="datetime-local" value={dateInput(draft.expiresAt)} onChange={e=>{if(e.target.value)update('expiresAt',new Date(e.target.value).toISOString());}} disabled={busy}/></Field></div>
        <div className="ag-sharing-limits"><Field label={t('总调用上限','Total call limit')}><Input type="number" min={1} max={1000} value={String(draft.maxCalls)} onChange={e=>update('maxCalls',Number(e.target.value))} disabled={busy}/></Field><Field label={t('每次输入字数','Input character limit')}><Input type="number" min={100} max={12000} value={String(draft.maxInputChars)} onChange={e=>update('maxInputChars',Number(e.target.value))} disabled={busy}/></Field><Field label={t('输出 token 上限','Output token limit')}><Input type="number" min={128} max={4096} value={String(draft.maxOutputTokens)} onChange={e=>update('maxOutputTokens',Number(e.target.value))} disabled={busy}/></Field></div>
        <div className="ag-sharing-approval"><Checkbox checked={contextApproved} onCheckedChange={setContextApproved} label={t('我已核对以上内容，允许此分身在上述用途内使用这些脱敏背景。','I reviewed this content and authorize this delegate to use the redacted context for these purposes.')} disabled={busy}/><Checkbox checked={rulesApproved} onCheckedChange={setRulesApproved} label={t('我同意这些调用规则；重新发布将撤销旧链接和未完成请求。','I approve these call rules. Republishing revokes previous links and unfinished requests.')} disabled={busy}/>{draft.approvalPolicy==='automatic'&&<Checkbox checked={automaticApproved} onCheckedChange={setAutomaticApproved} label={t('我允许在有效期与次数范围内直接调用所选模型。','I authorize direct calls to the selected model within the expiry and call limits.')} disabled={busy}/>}</div>
        <div className="ag-sharing-actions"><Button color="secondary" variant="outline" disabled={!complete||busy} onClick={()=>void action(async()=>{await save();setNotice(t('草稿已保存。','Draft saved.'));})}>{t('保存草稿','Save draft')}</Button><Button color="primary" disabled={!complete||!contextApproved||!rulesApproved||(draft.approvalPolicy==='automatic'&&!automaticApproved)||busy||!connection?.hasKey} loading={busy} onClick={()=>void action(publish)}>{published?t('更新发布','Publish update'):t('发布到本机','Publish locally')}<ArrowRight/></Button></div>
      </div>}
      {tab==='access'&&<div className="ag-sharing-access">
        {!published?<div className="ag-sharing-empty"><h3>{t('先发布一项能力','Publish a capability first')}</h3><p>{t('设置能力、脱敏上下文和调用规则后，为接收者创建独立授权。','Define the capability, redacted context and call rules, then create separate access grants for recipients.')}</p><Button color="secondary" variant="outline" onClick={()=>setTab('scope')}>{t('配置能力','Configure capability')}</Button></div>:<>
          <p className="ag-sharing-hint">{t(`已发布版本 ${selected!.version}。链接仅在运行 SecondU 的这台设备上有效；持有链接者可使用其中授权。`,`Published version ${selected!.version}. Links work only on this device. Anyone holding a link can use its grant.`)}</p>
          <Field label={t('接收者备注','Recipient label')}><Input value={recipient} onChange={e=>setRecipient(e.target.value)} maxLength={100} placeholder={t('例如：原型评审合作方','For example: Prototype review partner')} disabled={busy}/></Field>
          <fieldset className="ag-sharing-purposes"><legend>{t('本接收者可用的用途','Recipient’s allowed purposes')}</legend>{selected!.snapshot!.purposes.map(p=><Checkbox key={p} label={purposeName(p)} checked={grantPurposes.includes(p)} onCheckedChange={checked=>setGrantPurposes(checked?[...grantPurposes,p]:grantPurposes.filter(value=>value!==p))} disabled={busy}/>)}</fieldset>
          <div className="ag-sharing-pair"><Field label={t('调用次数','Call allowance')}><Input type="number" min={1} max={selected!.snapshot!.maxCalls} value={String(grantCalls)} onChange={e=>setGrantCalls(Number(e.target.value))} disabled={busy}/></Field><Field label={t('授权有效期','Access expires')}><Input type="datetime-local" value={dateInput(grantExpires)} onChange={e=>{if(e.target.value)setGrantExpires(new Date(e.target.value).toISOString());}} disabled={busy}/></Field></div>
          <Checkbox checked={allowCalls} onCheckedChange={setAllowCalls} label={t('允许提交调用请求（关闭后仅能查看能力）','Allow call requests (otherwise view only)')} disabled={busy}/>
          <Button color="primary" disabled={busy||!recipient.trim()||!grantPurposes.length} loading={busy} onClick={()=>void action(async()=>{const result=await write<DelegationAccess>(`/delegations/${selectedId}/grants`,{label:recipient,purposes:grantPurposes,maxCalls:grantCalls,expiresAt:grantExpires,allowCalls});setAccess(result);await reload();})}>{t('生成授权链接','Create access link')}</Button>
          {access&&<div className="ag-sharing-generated"><div>{qr&&<img src={qr} alt={t('受限分身授权二维码','Limited delegate access QR code')}/>}</div><div><strong>{t('这份授权已就绪','Access is ready')}</strong><p>{t('完整链接只在这里显示一次。关闭后可重新创建；原授权仍可撤销。','The complete link is shown only in this session. You can create another later and revoke the old grant.')}</p><div className="ag-sharing-link-actions"><CopyButton copyValue={access.url} color="secondary" variant="outline" size="sm">{t('复制链接','Copy link')}</CopyButton><a href={access.url} target="_blank" rel="noopener noreferrer">{t('打开接收页','Open recipient page')}<ArrowRight/></a>{qr&&<a href={qr} download={`${draft.name}-access.png`}><Download/>{t('下载二维码','Download QR')}</a>}</div><details><summary>{t('用于 Agent 连接','For agent connections')}</summary><p><span className="inline-metadata"><span>A2A 1.0</span><span>JSON-RPC</span><span>text/plain</span></span></p><p>{access.rpcUrl}</p><CopyButton copyValue={access.token} color="secondary" variant="ghost" size="sm">{t('复制访问令牌','Copy access token')}</CopyButton><CopyButton copyValue={access.cardUrl} color="secondary" variant="ghost" size="sm">{t('复制名片地址','Copy agent card URL')}</CopyButton></details></div></div>}
        </>}
        {!!selected?.grants.length&&<section className="ag-sharing-grants"><h3>{t('已发放的授权','Issued grants')}</h3>{[...selected.grants].reverse().map(grant=><div key={grant.id}><div><strong>{grant.label}</strong><p>{grant.revokedAt?t('已撤销','Revoked'):Date.parse(grant.expiresAt)<=Date.now()?t('已过期','Expired'):t(`已用 ${grant.usedCalls} / ${grant.maxCalls} 次`,`Used ${grant.usedCalls} / ${grant.maxCalls} calls`)}{t('，有效至 ', ', valid until ')} {when(grant.expiresAt)}</p></div>{!grant.revokedAt&&<Button size="sm" color="secondary" variant="ghost" disabled={busy} onClick={()=>void action(async()=>{await write(`/delegations/${selectedId}/grants/${grant.id}/revoke`,{});if(access?.grant.id===grant.id){setAccess(undefined);setQR('');}await reload();})}>{t('撤销','Revoke')}</Button>}</div>)}</section>}
        {published&&<div className="ag-sharing-revoke"><p>{t('撤销这项能力会同时停止未完成请求，使所有链接失效。','Revoking this capability stops unfinished requests and invalidates every link.')}</p><Button color="secondary" variant="outline" disabled={busy} onClick={()=>void action(async()=>{await write(`/delegations/${selectedId}/revoke`,{});setAccess(undefined);setQR('');await reload();setNotice(t('能力及全部授权已撤销。','Capability and all access grants revoked.'));})}>{t('撤销整项能力','Revoke capability')}</Button></div>}
      </div>}
      {tab==='requests'&&<div className="ag-sharing-requests"><div className="ag-sharing-request-heading"><p>{t('请求、审批与结果只保存在本机。','Requests, decisions and results stay on this device.')}</p><Button color="secondary" variant="ghost" size="sm" onClick={()=>void reload().catch(err=>setError(messageOf(err)))}>{t('刷新','Refresh')}</Button></div>{!selected?.calls.length?<div className="ag-sharing-empty"><h3>{t('还没有收到请求','No requests yet')}</h3><p>{t('接收者通过授权链接提交请求后，会在这里显示。','Requests appear here when recipients use their access link.')}</p></div>:[...selected.calls].reverse().map(call=><article key={call.id} className="ag-sharing-call"><div className="ag-sharing-call-meta"><strong>{selected.grants.find(g=>g.id===call.grantId)?.label||t('接收者','Recipient')}</strong><span className="inline-metadata"><span>{purposeName(call.purpose)}</span><span>v{call.version}</span><span>{taskState(call.task.status.state)}</span></span><small>{when(call.createdAt)}</small></div><p className="ag-sharing-call-input">{call.input}</p>{call.task.artifacts?.length?<div className="ag-sharing-call-result">{call.task.artifacts.flatMap(item=>item.parts.map(part=>part.text)).join('\n')}</div>:<p className="ag-sharing-hint">{call.task.status.message?.parts.map(part=>part.text).join('\n')}</p>}{call.task.status.state==='TASK_STATE_AUTH_REQUIRED'&&<div className="ag-sharing-call-actions"><Button color="secondary" variant="outline" size="sm" disabled={busy} onClick={()=>void action(async()=>{await write(`/delegations/${selectedId}/calls/${call.id}/reject`,{});await reload();})}>{t('不批准','Decline')}</Button><Button color="primary" size="sm" disabled={busy} onClick={()=>void action(async()=>{await write(`/delegations/${selectedId}/calls/${call.id}/approve`,{});await reload();})}>{t('批准这次调用','Approve this call')}</Button></div>}</article>)}</div>}
      </div>
    </>}
    <div className="ag-sharing-status"><ErrorNotice error={error||records?.service.error||''}/>{notice&&<p role="status">{notice}</p>}</div>
  </Dialog>;
}
