import { useEffect, useState } from 'react';
import type { AgentProfile } from '../../shared/contracts';
import { Button } from '@openai/apps-sdk-ui/components/Button';
import { Badge } from '@openai/apps-sdk-ui/components/Badge';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Textarea } from '@openai/apps-sdk-ui/components/Textarea';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Checkbox } from '@openai/apps-sdk-ui/components/Checkbox';
import { ArrowLeft, ArrowRight, CheckCircle, CreditCard, Mail, Phone, Terminal } from '@openai/apps-sdk-ui/components/Icon';
import QRCode from 'qrcode';
import { Dialog, Field } from '../components';
import { t, getLocale } from '../i18n';
import './resources-demo.css';

type View = 'overview'|'computer'|'email'|'phone'|'wallet'|'dining';
type Step = 'edit'|'review'|'receipt';
type Intent = 'order'|'queue'|'menu';
type Receipt = { id:string; at:string; title:string; detail:string; amount?:number };
type Session = { budget:string; communication:'review'|'prepare'; note:string; savedNote:string; emailTo:string; subject:string; body:string; phonePurpose:string; quantities:number[]; people:string; intent:Intent; receipts:Receipt[] };
const sessions = new Map<string,Session>();
const money = (cents:number) => new Intl.NumberFormat(getLocale(),{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(cents/100);
const localId = (id:string) => {let hash=0;for(const c of id)hash=(hash*31+c.charCodeAt(0))>>>0;return hash.toString(36).padStart(6,'0').slice(-6);};
const menu = () => [{name:t('菌菇鸡肉饭','Chicken and mushroom rice'),price:3800},{name:t('香煎豆腐饭','Pan-seared tofu rice'),price:3200},{name:t('时蔬清汤','Vegetable soup'),price:1800},{name:t('冷泡乌龙','Cold-brew oolong'),price:800}];
const initialSession = ():Session => ({budget:'80',communication:'review',note:t('# 用餐安排\n\n两位用餐，优先安静的位置。所有内容均为虚构演示。','# Dining plan\n\nTable for two, with a quiet seat if available. All details are fictional.'),savedNote:'',emailTo:'host@example.com',subject:t('确认两位用餐安排','Confirm a table for two'),body:t('你好，想咨询两位用餐的安排。如果需要等待，请先告诉我预计时间。\n\n这是一封演示草稿。','Hello, I would like to ask about a table for two. Please let me know the estimated wait.\n\nThis is a demonstration draft.'),phonePurpose:t('询问两位用餐的等位时间与是否有安静座位。','Ask about the wait for two people and whether a quiet table is available.'),quantities:[1,1,0,0],people:'2',intent:'order',receipts:[]});

export function AgentResourcesDemo({agent,onClose}:{agent:AgentProfile;onClose:()=>void}) {
  const scope=`${new URLSearchParams(location.search).get('space')||'main'}:${agent.id}`;
  return <Dialog title={t(`${agent.name}的工具与账户`,`${agent.name}'s tools and accounts`)} onClose={onClose} className="agent-resources-dialog"><Resources key={scope} agent={agent} scope={scope}/></Dialog>;
}

function Resources({agent,scope}:{agent:AgentProfile;scope:string}) {
  const [state,setState]=useState<Session>(()=>sessions.get(scope)||initialSession());
  const [view,setView]=useState<View>('overview');const [step,setStep]=useState<Step>('edit');
  const [diningStep,setDiningStep]=useState<'scan'|'arrange'|'menu'|'review'|'receipt'>('scan');
  const [qr,setQr]=useState('');const [preview,setPreview]=useState('');const [approvedExtra,setApprovedExtra]=useState(false);
  const [receipt,setReceipt]=useState<Receipt>();const [command,setCommand]=useState('list');const [commandResult,setCommandResult]=useState('');const [saved,setSaved]=useState(false);
  useEffect(()=>{sessions.set(scope,state);},[scope,state]);
  useEffect(()=>{let live=true;QRCode.toDataURL('hither-demo://restaurant/qinghe',{width:112,margin:1,color:{dark:'#202020',light:'#ffffff'}}).then(value=>{if(live)setQr(value);}).catch(()=>{});return()=>{live=false;};},[]);
  function patch(value:Partial<Session>){setState(current=>({...current,...value}));setSaved(false);}
  function navigate(next:View){setView(next);setStep('edit');if(next==='dining')setDiningStep('scan');setReceipt(undefined);setPreview('');setApprovedExtra(false);}
  const handle=localId(agent.id);const address=`assistant-${handle}@example.com`;
  const phone=`+1 202 555 01${(parseInt(handle,36)%100).toString().padStart(2,'0')}`;
  const amount=state.intent==='order'?menu().reduce((total,item,i)=>total+item.price*state.quantities[i],0):0;
  const budget=Number(state.budget);const validBudget=state.budget.trim()!==''&&Number.isFinite(budget)&&budget>=0&&budget<=10000;
  const over=validBudget&&amount>Math.round(budget*100);
  const fingerprint=(type:View)=>JSON.stringify(type==='dining'?{people:state.people,intent:state.intent,quantities:state.quantities,budget:state.budget}:type==='email'?{to:state.emailTo,subject:state.subject,body:state.body,scope:state.communication}:{purpose:state.phonePurpose,scope:state.communication});
  const stale=!!preview&&preview!==fingerprint(view);
  function review(){setPreview(fingerprint(view));setApprovedExtra(false);setStep('review');}
  function approve(title:string,detail:string,cost?:number){
    if(stale)return;
    const next={id:`DEV-${handle}-${state.receipts.length+1}`,at:new Date().toISOString(),title,detail,amount:cost};
    setReceipt(next);setState(current=>({...current,receipts:[next,...current.receipts]}));
    if(view==='dining')setDiningStep('receipt');else setStep('receipt');
  }
  const entries=[{id:'computer' as const,label:t('电脑','Computer'),icon:Terminal,detail:`workspace-${handle}`},{id:'email' as const,label:t('邮箱','Email'),icon:Mail,detail:address},{id:'phone' as const,label:t('电话','Phone'),icon:Phone,detail:phone},{id:'wallet' as const,label:t('钱包与权限','Wallet and permissions'),icon:CreditCard,detail:t('本次预算与通信范围','Budget and communication scope')}];
  const receiptView=receipt&&<section className="resource-receipt" aria-live="polite"><CheckCircle/><h3>{t('演示回执','Demo receipt')}</h3><p>{receipt.title}</p><dl><div><dt>{t('编号','Reference')}</dt><dd>{receipt.id}</dd></div><div><dt>{t('处理助理','Assistant')}</dt><dd>{agent.name}</dd></div>{receipt.amount!==undefined&&<div><dt>{t('演示金额','Demo amount')}</dt><dd>{money(receipt.amount)}</dd></div>}<div><dt>{t('生成时间','Created')}</dt><dd>{new Date(receipt.at).toLocaleTimeString(getLocale(),{hour:'2-digit',minute:'2-digit'})}</dd></div></dl><p className="resource-preserve">{receipt.detail}</p><p className="resource-muted">{t('未请求商家、付款、发信或拨号。','No merchant request, payment, email, or call was made.')}</p><Button size="sm" color="secondary" variant="outline" onClick={()=>{setReceipt(undefined);setPreview('');setStep('edit');if(view==='dining')setDiningStep('arrange');}}>{t('返回修改','Revise details')}</Button></section>;
  return <div className="agent-resources-demo">
    <div className="resource-demo-strip"><Badge size="sm" color="secondary">Dev</Badge><span>{t('虚构资源与流程，刷新页面或关闭应用后重置。','Fictional resources and workflows. Reloading or closing the app resets edits.')}</span></div>
    <div className="resource-shell"><nav className="resource-nav" aria-label={t('工具与账户','Tools and accounts')}><Button color="secondary" variant={view==='overview'?'soft':'ghost'} size="sm" onClick={()=>navigate('overview')}>{t('资源概览','Overview')}</Button>{entries.map(item=><Button key={item.id} color="secondary" variant={view===item.id?'soft':'ghost'} size="sm" onClick={()=>navigate(item.id)}><item.icon/>{item.label}</Button>)}<span className="resource-nav-rule"/><Button color="secondary" variant={view==='dining'?'soft':'ghost'} size="sm" onClick={()=>navigate('dining')}>{t('餐厅扫码','Restaurant QR')}<Badge size="sm" color="secondary">Dev</Badge></Button></nav>
    <main className="resource-main">
      {view==='overview'&&<><h3>{t('属于这位助理的资源','Resources for this assistant')}</h3><p className="resource-muted">{t('每位助理使用独立的示例配置。可以查看工具，或体验一次完整的用餐安排。','Each assistant has separate example settings. Explore a resource or try a complete dining workflow.')}</p><div className="resource-overview-list">{entries.map(item=><button key={item.id} type="button" onClick={()=>navigate(item.id)}><span className="resource-icon"><item.icon/></span><span><strong>{item.label}</strong><small>{item.detail}</small></span><Badge size="sm" color="secondary">{t('示例','Example')}</Badge><ArrowRight/></button>)}</div><div className="resource-scenario"><h4>{t('从餐厅二维码到确认订单','From restaurant QR to an order review')}</h4><p>{t('识别商家、选人数、查看菜单和预算，最后由你确认。','Identify the restaurant, choose your party and menu, check the budget, then review the action.')}</p><Button size="md" color="primary" onClick={()=>{navigate('dining');setDiningStep('scan');}}>{t('体验用餐流程','Try the dining workflow')}<ArrowRight/></Button></div>{!!state.receipts.length&&<div className="resource-recent"><h4>{t('本次演示记录','Demo activity in this session')}</h4>{state.receipts.slice(0,5).map(item=><p key={item.id}><span>{item.title}</span><small>{item.id}</small></p>)}</div>}</>}
      {view==='wallet'&&<><h3>{t('预算与审批范围','Budget and approval scope')}</h3><p className="resource-muted">{t('示例钱包没有余额、卡号或支付能力。','This example wallet has no funds, card details, or payment capability.')}</p><div className="resource-kv"><span>{t('示例钱包','Example wallet')}</span><strong>wallet-{handle}</strong></div><div className="resource-form"><Field label={t('单次用餐预算（人民币）','Budget per meal (CNY)')} hint={t('0 至 10,000。超额时需要本次单独确认。','0 to 10,000. An over-budget order needs separate confirmation.')}><Input type="number" min={0} max={10000} step="1" size="md" value={state.budget} onChange={event=>patch({budget:event.target.value})}/></Field>{!validBudget&&<p className="resource-error" role="alert">{t('请填写 0 至 10,000 之间的预算。','Enter a budget between 0 and 10,000.')}</p>}<Field label={t('通信范围','Communication scope')}><Select value={state.communication} options={[{value:'review',label:t('预览并逐次确认','Review each action')},{value:'prepare',label:t('只准备草稿和通话提纲','Prepare drafts and call notes only')}]} onChange={option=>patch({communication:option.value as Session['communication']})} size="md" align="start" listWidth={250} listMinWidth={220} listMaxWidth={280}/></Field><p className="resource-policy">{t('预算内的演示订单仍需要确认。范围不会授权任何真实外部操作。','Demo orders within budget still need approval. These settings authorize no real external action.')}</p><Button size="md" color="primary" disabled={!validBudget} onClick={()=>setSaved(true)}>{t('保留本次设置','Keep session settings')}</Button>{saved&&<p role="status" className="resource-muted">{t('已保留到本次会话，其他助理不受影响。','Kept for this session. Other assistants are unchanged.')}</p>}</div></>}
      {view==='computer'&&<><h3>{t('示例电脑','Example computer')}</h3><p className="resource-muted">{t('这是可编辑的前端工作区示例，没有连接本机终端或云电脑。','An editable frontend workspace example, without a host terminal or cloud computer.')}</p><div className="resource-kv"><span>{t('工作区','Workspace')}</span><strong>workspace-{handle}</strong></div><div className="resource-form"><Field label="dining-plan.md"><Textarea size="md" rows={5} value={state.note} onChange={event=>patch({note:event.target.value})}/></Field><div className="resource-actions"><Button size="sm" color="primary" onClick={()=>{patch({savedNote:state.note});setSaved(true);}}>{t('保存示例文件','Save example file')}</Button>{saved&&<span role="status">{t('示例文件已保留','Example file kept')}</span>}</div><Field label={t('终端流程预览','Terminal workflow preview')}><Select value={command} options={[{value:'list',label:t('列出示例文件','List example files')},{value:'read',label:t('阅读已保存的示例文件','Read the saved example file')}]} onChange={option=>setCommand(option.value)} size="md" align="start" listWidth={230} listMinWidth={210} listMaxWidth={260}/></Field><Button size="sm" color="secondary" variant="outline" onClick={()=>setCommandResult(command==='list'?'dining-plan.md':state.savedNote||t('请先保存示例文件。','Save the example file first.'))}>{t('显示演示结果','Show demo output')}</Button>{commandResult&&<pre className="resource-terminal">{commandResult}</pre>}</div></>}
      {view==='email'&&<><h3>{t('邮件草稿','Email draft')}</h3><p className="resource-muted">{t('示例发件人：','Example sender: ')}{address}</p>{step==='receipt'?receiptView:step==='edit'?<div className="resource-form"><Field label={t('示例收件人','Example recipient')} hint={t('使用 example.com 地址体验，不会发送。','Use an example.com address. Nothing will be sent.')}><Input size="md" type="email" value={state.emailTo} onChange={event=>patch({emailTo:event.target.value})}/></Field><Field label={t('主题','Subject')}><Input size="md" value={state.subject} onChange={event=>patch({subject:event.target.value})}/></Field><Field label={t('正文','Message')}><Textarea size="md" rows={6} value={state.body} onChange={event=>patch({body:event.target.value})}/></Field><Button size="md" color="primary" disabled={!/^[^\s@]+@example\.com$/i.test(state.emailTo.trim())||!state.subject.trim()||!state.body.trim()} onClick={review}>{t('预览邮件','Review email')}</Button></div>:<div className="resource-form"><div className="resource-document"><small>{state.emailTo}</small><h4>{state.subject}</h4><p>{state.body}</p></div><CommunicationApproval scope={state.communication} onPolicy={()=>navigate('wallet')}/><div className="resource-actions"><Button size="sm" color="secondary" variant="ghost" onClick={()=>setStep('edit')}>{t('返回编辑','Back to editing')}</Button><Button size="sm" color="primary" disabled={state.communication==='prepare'||stale} onClick={()=>approve(t('邮件演示已确认','Email demonstration approved'),t(`已预览发给 ${state.emailTo} 的“${state.subject}”。邮件未发送。`,`Reviewed “${state.subject}” for ${state.emailTo}. No email was sent.`))}>{t('确认并生成演示回执','Approve and create demo receipt')}</Button></div></div>}</>}
      {view==='phone'&&<><h3>{t('准备通话','Prepare a call')}</h3><p className="resource-muted">{t(`助理示例号码：${phone}。示例被叫：+1 202 555 0147，不会拨号。`,`Assistant example number: ${phone}. Example recipient: +1 202 555 0147. No call will be made.`)}</p>{step==='receipt'?receiptView:step==='edit'?<div className="resource-form"><Field label={t('这通电话想确认什么','What would you like to ask?')}><Textarea size="md" rows={5} value={state.phonePurpose} onChange={event=>patch({phonePurpose:event.target.value})}/></Field><Button size="md" color="primary" disabled={!state.phonePurpose.trim()} onClick={review}>{t('查看通话提纲','Review call notes')}</Button></div>:<div className="resource-form"><div className="resource-document"><h4>{t('通话提纲','Call notes')}</h4><p>{t(`你好，我是 ${agent.name} 的示例电话助理。`,`Hello, I am the example calling assistant for ${agent.name}.`)}</p><p>{state.phonePurpose}</p><p>{t('确认对方答复，再交给主人决定。','Confirm the response and return it to the owner for a decision.')}</p></div><CommunicationApproval scope={state.communication} onPolicy={()=>navigate('wallet')}/><div className="resource-actions"><Button size="sm" color="secondary" variant="ghost" onClick={()=>setStep('edit')}>{t('返回修订','Revise notes')}</Button><Button size="sm" color="primary" disabled={state.communication==='prepare'||stale} onClick={()=>approve(t('通话演示已确认','Call demonstration approved'),t('已审阅通话提纲，没有拨号，也没有虚构对方的回复。','Call notes were reviewed. No call was made and no recipient response was invented.'))}>{t('确认通话演示','Approve call demo')}</Button></div></div>}</>}
      {view==='dining'&&<><div className="resource-heading"><h3>{t('餐厅扫码','Restaurant QR')}</h3><span className="resource-step">{({scan:t('识别','Identify'),arrange:t('安排','Plan'),menu:t('菜单','Menu'),review:t('确认','Review'),receipt:t('回执','Receipt')})[diningStep]}</span></div>
        {diningStep==='scan'&&<div className="resource-scan">{qr&&<img src={qr} alt={t('仅供本地演示的餐厅二维码','Restaurant QR for local demonstration only')} width={112} height={112}/>}<h4>{t('青禾小馆','Qinghe Kitchen')}</h4><p>{t('虚构商家二维码，点按读取示例内容。不会打开摄像头或访问商家。','A fictional restaurant code. Read the sample without opening a camera or contacting a merchant.')}</p><Button color="primary" size="md" onClick={()=>setDiningStep('arrange')}>{t('读取示例二维码','Read example QR')}</Button></div>}
        {diningStep==='arrange'&&<div className="resource-form"><div className="resource-merchant"><CheckCircle/><span><strong>{t('已识别青禾小馆','Qinghe Kitchen identified')}</strong><small>{t('虚构餐厅，提供菜单、点餐与排队演示','Fictional restaurant with menu, ordering, and queue demonstrations')}</small></span></div><Field label={t('用餐人数','Party size')}><Select size="md" value={state.people} options={['1','2','3','4','5','6'].map(value=>({value,label:t(`${value} 位`,`${value} ${value==='1'?'person':'people'}`)}))} onChange={option=>patch({people:option.value})} align="start" listWidth={180} listMinWidth={160} listMaxWidth={200}/></Field><fieldset className="resource-intents"><legend>{t('想先做什么','What would you like to do?')}</legend>{([{value:'order',label:t('选菜点餐','Choose a meal')},{value:'queue',label:t('加入等位','Join the queue')},{value:'menu',label:t('只看菜单','View the menu')}] as const).map(option=><Button key={option.value} size="sm" color="secondary" variant={state.intent===option.value?'soft':'outline'} aria-pressed={state.intent===option.value} onClick={()=>patch({intent:option.value})}>{option.label}</Button>)}</fieldset><Button color="primary" size="md" onClick={()=>setDiningStep('menu')}>{t('继续','Continue')}<ArrowRight/></Button></div>}
        {diningStep==='menu'&&<div className="resource-form"><Button size="sm" color="secondary" variant="ghost" onClick={()=>setDiningStep('arrange')}><ArrowLeft/>{t('人数与安排','Party and plan')}</Button>{state.intent==='queue'?<div className="resource-document"><h4>{t('等位预览','Queue preview')}</h4><p>{t(`${state.people} 位，示例等待约 15 分钟。此时长不是商家实时信息。`,`${state.people} guests, an example wait of about 15 minutes. This is not live restaurant data.`)}</p><p>{t('取号演示不收费。确认后生成演示排队回执。','The queue demo has no charge. Review it to create a demo queue receipt.')}</p></div>:<div className="resource-menu">{menu().map((item,i)=><div key={i}><span><strong>{item.name}</strong><small>{money(item.price)}</small></span>{state.intent==='order'?<div className="resource-quantity"><Button size="sm" uniform color="secondary" variant="outline" aria-label={t(`减少${item.name}`,`Remove one ${item.name}`)} disabled={!state.quantities[i]} onClick={()=>patch({quantities:state.quantities.map((value,index)=>index===i?value-1:value)})}>−</Button><output aria-label={t(`${item.name}份数`,`${item.name} quantity`)}>{state.quantities[i]}</output><Button size="sm" uniform color="secondary" variant="outline" aria-label={t(`增加${item.name}`,`Add one ${item.name}`)} disabled={state.quantities[i]>=9} onClick={()=>patch({quantities:state.quantities.map((value,index)=>index===i?value+1:value)})}>+</Button></div>:<span className="resource-muted">{t('示例价格','Example price')}</span>}</div>)}</div>}{state.intent==='order'&&<div className="resource-budget-line"><span>{t('预计金额','Estimated total')} <strong>{money(amount)}</strong></span><span>{validBudget?t(`预算 ¥${state.budget}`,`Budget ¥${state.budget}`):t('预算需修正','Fix budget')}</span><Badge color={over||!validBudget?'warning':'secondary'} size="sm">{!validBudget?t('预算无效','Invalid budget'):over?t('超过预算','Over budget'):t('预算内','Within budget')}</Badge></div>}<Button size="md" color="primary" disabled={state.intent==='order'&&(!amount||!validBudget)} onClick={()=>{setPreview(fingerprint('dining'));setApprovedExtra(false);setDiningStep('review');}}>{t('预览本次安排','Review this plan')}</Button></div>}
        {diningStep==='review'&&<div className="resource-form"><div className="resource-document"><h4>{t('请确认这一次安排','Review this specific plan')}</h4><p>{t(`青禾小馆，${state.people} 位。`,`Qinghe Kitchen, ${state.people} guests.`)}</p>{state.intent==='order'?<>{menu().map((item,i)=>state.quantities[i]>0&&<p key={i}>{item.name} × {state.quantities[i]} <strong>{money(item.price*state.quantities[i])}</strong></p>)}<p className="resource-total">{t('总计','Total')} <strong>{money(amount)}</strong></p></>:<p>{state.intent==='queue'?t('请求一个演示等位号码，不点餐、不付款。','Request a demo queue number, without ordering or paying.'):t('保存这份示例菜单，不创建订单。','Keep this example menu without creating an order.')}</p>}</div><ol className="resource-team"><li><span>{t('餐厅助理','Restaurant assistant')}</span>{t('提供示例菜单与等位信息','Provides the example menu and queue details')}</li><li><span>{agent.name}</span>{t('整理人数、菜品与本次目标','Organizes the party, selections, and current intent')}</li><li><span>{t('结算助理','Budget assistant')}</span>{t('核对金额与审批范围','Checks the amount and approval scope')}</li></ol>{over&&<Checkbox checked={approvedExtra} onCheckedChange={setApprovedExtra} label={t(`本次允许超出预算，演示金额 ${money(amount)}。`,`Allow this demo to exceed the budget at ${money(amount)}.`)}/>}<p className="resource-muted">{t('确认只会产生演示回执，不会联系商家或扣款。','Approval only creates a demo receipt. It will not contact the restaurant or charge you.')}</p>{stale&&<p role="alert" className="resource-error">{t('安排已变更，请返回重新预览。','The plan changed. Go back and review it again.')}</p>}<div className="resource-actions"><Button size="sm" color="secondary" variant="ghost" onClick={()=>setDiningStep('menu')}>{t('返回改选','Revise selection')}</Button><Button size="sm" color="primary" disabled={stale||(state.intent==='order'&&(!validBudget||(over&&!approvedExtra)))} onClick={()=>approve(state.intent==='order'?t('用餐演示订单已确认','Demo dining order approved'):state.intent==='queue'?t('演示等位号码 A012','Demo queue number A012'):t('示例菜单已保留','Example menu kept'),t('餐厅、主助理与结算角色已完成这次演示分工。没有发生外部操作。','The restaurant, personal assistant, and budget roles completed this demo workflow. No external action occurred.'),amount)}>{t('批准并生成演示回执','Approve and create demo receipt')}</Button></div></div>}
        {diningStep==='receipt'&&receiptView}
      </>}
    </main></div>
  </div>;
}

function CommunicationApproval({scope,onPolicy}:{scope:Session['communication'];onPolicy:()=>void}) {
  return <div className="resource-policy"><p>{scope==='prepare'?t('当前仅允许准备草稿与提纲。可以返回修订，或调整演示审批范围。','Your current scope allows drafts and notes only. Revise them or change the demo approval scope.'):t('请核对收件对象与准确内容。确认只生成演示回执。','Review the recipient and exact content. Approval creates a demo receipt only.')}</p><Button size="sm" color="secondary" variant="ghost" onClick={onPolicy}>{t('调整审批范围','Change approval scope')}</Button></div>;
}
