import { useEffect, useRef, useState, type ReactNode } from 'react';
import type { AgentProfile, Bootstrap } from '../../shared/contracts';
import { Button } from '@openai/apps-sdk-ui/components/Button';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Search, Chat, ArrowLeft, ArrowRight } from '@openai/apps-sdk-ui/components/Icon';
import { t, getLocale } from '../i18n';
import { AgentAvatar, AgentBadgeStage } from './AgentIdentity';
import { BulkAvatarStyle } from './BulkAvatarStyle';
import { selfAgent, isSelfAgent } from './agentProfiles';
import { filterSavedAgents, savedAgentDomain } from './agentDirectoryData';
import { EXPERT_CATEGORIES, expertText } from './expertTemplates';
import { ExpertDomainPicker } from './ExpertDomainPicker';

export function SavedAgentBrowser({data,navigation,onOpen,onTrial,onRefresh}:{data:Bootstrap;navigation:ReactNode;onOpen:(agent:AgentProfile)=>void;onTrial:(agent:AgentProfile)=>void;onRefresh:()=>Promise<void>}) {
 const [query,setQuery]=useState(''),[domain,setDomain]=useState('all'),[sort,setSort]=useState('recent'),[selectedId,setSelectedId]=useState('hither'),[face,setFace]=useState<'identity'|'role'|'history'>('identity');
 const roster=useRef<HTMLDivElement>(null),stage=useRef<HTMLElement>(null);
 const own=selfAgent(data),filtered=filterSavedAgents(data.agents,data.tasks,query,domain,sort),visible=[own,...filtered];
 const selected=visible.find(agent=>agent.id===selectedId)||(query||domain!=='all'?filtered[0]:own)||own,index=visible.findIndex(agent=>agent.id===selected.id);
 const domains=[...new Set(data.agents.map(savedAgentDomain))],selectedDomain=EXPERT_CATEGORIES.find(group=>group.id===savedAgentDomain(selected));
 function resetSelection(){setSelectedId('');roster.current?.scrollTo({top:0});}
 function choose(id:string,focus=false){setSelectedId(id);setFace('identity');if(focus)requestAnimationFrame(()=>roster.current?.querySelector<HTMLButtonElement>(`[data-saved-agent-id="${id}"]`)?.focus());}
 function step(offset:number){const next=visible[index+offset];if(next){choose(next.id);requestAnimationFrame(()=>roster.current?.querySelector(`[data-saved-agent-id="${next.id}"]`)?.scrollIntoView({block:'nearest'}));}}
 function flip(next:'identity'|'role'|'history'){setFace(next);requestAnimationFrame(()=>stage.current?.querySelector<HTMLButtonElement>(next==='identity'?'.ag-pass-face-front footer button':'.ag-pass-face-back header button')?.focus());}
 useEffect(()=>setFace('identity'),[selected.id]);
 return <div className="expert-library-shell saved-agent-browser"><div className="ag-directory-toolbar expert-directory-toolbar">{navigation}<ExpertDomainPicker value={domain} available={domains} includeCustom={domains.includes('custom')} onChange={value=>{setDomain(value);resetSelection();}}/><Input variant="soft" size="md" startAdornment={<Search/>} placeholder={t('搜索名字或职责','Search name or role')} aria-label={t('搜索我的 Agents','Search my agents')} value={query} onChange={event=>{setQuery(event.target.value);resetSelection();}}/><Select size="sm" aria-label={t('Agent 排序','Sort agents')} value={sort} onChange={option=>setSort(option.value)} options={[{value:'recent',label:t('最近使用','Recent activity')},{value:'created',label:t('最近添加','Recently added')},{value:'name',label:t('按名称','Name')} ]}/><BulkAvatarStyle agents={data.agents} defaultStyle={data.defaultAgentAvatarStyle} onRefresh={onRefresh}/></div>
  <div className="expert-browser expert-badge-browser"><section className="expert-choice-panel" aria-label={t('我的 Agent 目录','My agent catalogue')}><div className="expert-choice-list" role="listbox" aria-label={t('选择我的 Agent','Choose my agent')} ref={roster}>{visible.map((agent,itemIndex)=><button type="button" className={`expert-choice ${isSelfAgent(agent)?'saved-self-choice':''}`} role="option" aria-selected={selected.id===agent.id} tabIndex={selected.id===agent.id?0:-1} data-saved-agent-id={agent.id} key={agent.id} onClick={()=>choose(agent.id)} onKeyDown={event=>{const next=event.key==='ArrowDown'?itemIndex+1:event.key==='ArrowUp'?itemIndex-1:event.key==='Home'?0:event.key==='End'?visible.length-1:-1;if(next>=0&&next<visible.length){event.preventDefault();choose(visible[next].id,true);}}}><AgentAvatar agent={agent} size={31}/><span className="expert-choice-copy"><strong>{agent.name}</strong><span>{agent.role}</span></span>{isSelfAgent(agent)&&<span className="expert-choice-index">{t('分身','You')}</span>}</button>)}{!filtered.length&&<div className="expert-empty"><h3>{query||domain!=='all'?t('没有匹配的 Agent','No matching agents'):t('添加你的第一位专家','Add your first expert')}</h3>{(query||domain!=='all')&&<Button size="sm" color="secondary" variant="ghost" onClick={()=>{setQuery('');setDomain('all');setSelectedId('hither');}}>{t('清除筛选','Clear filters')}</Button>}</div>}</div></section>
  <section className="expert-showcase" aria-label={t('我的 Agent 工牌预览','My agent badge preview')} ref={stage}><header className="expert-showcase-header"><span>{isSelfAgent(selected)?t('你的数字分身','Your digital twin'):selectedDomain?expertText(selectedDomain.label,getLocale()):t('自定义','Custom')}</span><span>{String(index+1).padStart(2,'0')} / {String(visible.length).padStart(2,'0')}</span></header><div className="expert-showcase-stage"><AgentBadgeStage agent={selected} face={face} onFaceChange={flip}/></div><div className="expert-showcase-action saved-agent-actions"><Button color="primary" size="md" onClick={()=>onTrial(selected)}><Chat/>{t('开始对话','Start a chat')}</Button><Button color="secondary" variant="ghost" size="md" onClick={()=>onOpen(selected)}>{t('工牌与设置','Badge and settings')}<ArrowRight/></Button></div><footer className="expert-showcase-switcher"><Button color="secondary" variant="ghost" uniform size="sm" aria-label={t('上一位 Agent','Previous agent')} disabled={index<=0} onClick={()=>step(-1)}><ArrowLeft/></Button><div className="expert-neighbor-strip">{visible.slice(Math.max(0,index-1),Math.min(visible.length,Math.max(0,index-1)+3)).map(agent=><button key={agent.id} type="button" className={agent.id===selected.id?'is-selected':''} aria-label={t(`切换到${agent.name}`,`Switch to ${agent.name}`)} aria-pressed={agent.id===selected.id} onClick={()=>choose(agent.id)}><AgentAvatar agent={agent} size={28}/><span>{agent.name}</span></button>)}</div><Button color="secondary" variant="ghost" uniform size="sm" aria-label={t('下一位 Agent','Next agent')} disabled={index>=visible.length-1} onClick={()=>step(1)}><ArrowRight/></Button></footer></section></div>
 </div>;
}
