import { t } from './i18n';
import { useUnsavedChanges } from './useUnsavedChanges';
import { compactSelectProps } from './compactSelect';
import { useRef } from 'react';
import { WelcomeLettering } from './WelcomeLettering';
import { UserAvatar } from './UserAvatar';
import { useArtwork } from './artwork';
import { Button } from '@openai/apps-sdk-ui/components/Button';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Slider } from '@openai/apps-sdk-ui/components/Slider';
import { Switch } from '@openai/apps-sdk-ui/components/Switch';
import { Check, Sun, Moon, MoonSunSystem, ArrowRotateCw, FileUpload }  from '@openai/apps-sdk-ui/components/Icon';
import { defaultAppearance, type Appearance, type AppearanceStatus } from './appearance';
import type { Theme } from './SettingsWorkspace';
export function AppearanceSettings({theme,onTheme,value,onChange,status}:{theme:Theme;onTheme:(theme:Theme)=>void;value:Appearance;status:AppearanceStatus;onChange:(update:Partial<Appearance>)=>void}) {
  const artwork=useArtwork();const fileInput=useRef<HTMLInputElement>(null);
  useUnsavedChanges({ unsaved: status.pendingChanges, busy: artwork.busy || status.saving });
  return <>
    <header className="settings-panel-heading"><h2 id="settings-appearance-title">{t("外观", "Appearance")}</h2><p>{t("让这个空间更像你。更改会自动保存在这台电脑。", "Make this space feel like you. Changes save automatically on this computer.")}</p></header>
    <div className="appearance-block"><h3>{t("界面模式", "Color mode")}</h3><div className="theme-options">{([{id:'system',label:t("跟随系统", "System"),Icon:MoonSunSystem},{id:'light',label:t("月之亮面", "Light side of the moon"),Icon:Sun},{id:'dark',label:t("月之暗面", "Dark side of the moon"),Icon:Moon}] as const).map(({id,label,Icon})=><button key={id} className={`theme-option ${theme===id?'selected':''}`} aria-pressed={theme===id} onClick={()=>onTheme(id)}><div className={`theme-mini theme-mini-${id}`} aria-hidden="true"><aside><i/><i/><i/></aside><section><i/><i/><div/><span/></section></div><span><Icon />{label}{theme===id&&<Check />}</span></button>)}</div></div>
    <div className="appearance-block"><h3>{t("空间氛围", "Atmosphere")}</h3><div className="atmosphere-options">{([{id:'plain',label:t("纯净", "Clean")},{id:'pencil',label:t("纸上花园", "Paper garden")},{id:'tidal',label:t("潮汐之间", "Between tides")},{id:'night',label:t("月下远行", "Moonlit journey")}] as const).map(item=><button key={item.id} className={`atmosphere-option ${value.atmosphere===item.id?'selected':''}`} aria-pressed={value.atmosphere===item.id} onClick={()=>onChange({atmosphere:item.id})}><div className={`atmosphere-preview atmosphere-${item.id}`}><WelcomeLettering preview /></div><span>{item.label}{value.atmosphere===item.id&&<Check />}</span></button>)}</div><div className="custom-artwork-row">{artwork.url&&<button className={`custom-artwork-preview ${value.atmosphere==='custom'?'selected':''}`} aria-label={t("使用自己的图片", "Use your own image")} aria-pressed={value.atmosphere==='custom'} onClick={()=>onChange({atmosphere:'custom'})}><img src={artwork.url} alt={t("你上传的背景预览", "Preview of your uploaded background")}/>{value.atmosphere==='custom'&&<Check/>}</button>}<div><h3>{t("自己的图片", "Your own image")}</h3><p>{t("仅保存在当前电脑，支持 PNG、JPEG、WebP、AVIF，最大 8 MB。", "Stored only on this computer. PNG, JPEG, WebP, or AVIF, up to 8 MB.")}</p></div><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,image/avif" aria-label={t("上传本地背景图片", "Upload a local background image")} hidden onChange={async event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(file&&await artwork.save(file))onChange({atmosphere:'custom'});}}/><Button color="secondary" variant="outline" size="sm" loading={artwork.busy} onClick={()=>fileInput.current?.click()}><FileUpload/>{artwork.url?t("替换图片", "Replace image"):t("上传图片", "Upload image")}</Button></div>{artwork.error&&<p role="alert" className="artwork-error">{artwork.error}</p>}<p className="settings-action-hint">{t("插画只出现在欢迎页与局部背景，阅读和工作区域保持清晰。", "Illustrations appear on the welcome page and selected backgrounds, keeping work areas clear.")}</p></div>
    <div className="preferences-group">
      <div className="preference-line"><div><h3>{t("装饰素材", "Decorative artwork")}</h3><p>{t("在页面标题旁显示小幅插画", "Show small illustrations beside page headings")}</p></div><Switch className="settings-personal-switch" label={t("装饰素材", "Decorative artwork")} checked={value.decorativeArtwork} onCheckedChange={decorativeArtwork=>onChange({decorativeArtwork})}/></div>
      <div className="preference-line"><div><h3>{t("强调色", "Accent color")}</h3><p>{t("用于选中、聚焦与当前状态", "For selection, focus, and active states")}</p></div><div className="accent-options">{([{id:'graphite',label:t("石墨", "Graphite"),color:'#595b64'},{id:'blue',label:t("湖蓝", "Lake blue"),color:'#347bf5'},{id:'violet',label:t("鸢尾", "Iris"),color:'#8164cb'},{id:'green',label:t("苔绿", "Moss"),color:'#56826b'}] as const).map(item=><button key={item.id} title={item.label} aria-label={item.label} aria-pressed={value.accent===item.id} className={value.accent===item.id?'selected':''} style={{background:item.color}} onClick={()=>onChange({accent:item.id})}>{value.accent===item.id&&<Check />}</button>)}</div></div>
      <div className="preference-line slider-preference"><div><h3>{t("面板不透明度", "Panel opacity")}</h3><p>{t("侧栏、输入框与浮层的材质浓度", "Opacity of sidebars, composers, and overlays")}</p></div><Slider label={t("面板不透明度", "Panel opacity")} value={value.opacity} min={70} max={100} step={1} unit="%" resetValue={96} onChange={opacity=>onChange({opacity})}/></div>
      <div className="preference-line slider-preference"><div><h3>{t("界面字号", "Text size")}</h3><p>{t("调整正文、导航与辅助信息", "Adjust text, navigation, and supporting details")}</p></div><Slider label={t("界面字号", "Text size")} value={value.fontSize} min={12} max={18} step={1} unit="px" resetValue={14} onChange={fontSize=>onChange({fontSize})}/></div>
      <div className="preference-line"><div><h3><label htmlFor="settings-motion">{t("减少动态效果", "Reduce motion")}</label></h3><p>{t("关闭装饰动画与平滑滚动", "Reduce decorative animation and smooth scrolling")}</p></div><Select {...compactSelectProps} id="settings-motion" value={value.motion} onChange={option=>onChange({motion:option.value as Appearance['motion']})} options={[{value:'system',label:t("跟随系统", "System")},{value:'reduced',label:t("开启", "On")}]}/></div>
    </div>
    <div className="appearance-live-sample"><UserAvatar size={36}/><div><strong>{t("一个属于你的工作空间", "A workspace of your own")}</strong><p>{t("先看清重要的事，再一起推进。", "See what matters, then move it forward together.")}</p></div><span className="appearance-saved" role="status">{status.error?t("保存未完成", "Not saved"):status.saving?t("正在保存", "Saving"):<><Check />{t("已保存", "Saved")}</>}</span></div>
    {status.error&&<p role="alert" className="artwork-error">{status.error}</p>}
    <Button color="secondary" variant="ghost" size="sm" className="appearance-reset" onClick={()=>{onTheme('system');onChange({...defaultAppearance,language:value.language,sendKey:value.sendKey});}}><ArrowRotateCw />{t("恢复默认外观", "Reset appearance")}</Button>
  </>;
}
