import { useState } from 'react';
import type { Automation, Bootstrap, Task } from '../shared/contracts';
import { Button } from '@openai/apps-sdk-ui/components/Button';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Textarea } from '@openai/apps-sdk-ui/components/Textarea';
import { Select } from '@openai/apps-sdk-ui/components/Select';
import { Switch } from '@openai/apps-sdk-ui/components/Switch';
import { Checkbox } from '@openai/apps-sdk-ui/components/Checkbox';
import { Badge } from '@openai/apps-sdk-ui/components/Badge';
import { Plus, Play, Edit, Clock } from '@openai/apps-sdk-ui/components/Icon';
import { Dialog, Empty, ErrorNotice, Field, PageHeading, when } from './components';
import { write, messageOf } from './api';

function AutomationForm({ initial, data, onRefresh, onClose }: { initial?: Automation; data: Bootstrap; onRefresh: () => Promise<void>; onClose: () => void }) {
  const [draft, setDraft] = useState({ title: initial?.title || '', prompt: initial?.prompt || '', trigger: initial?.trigger || 'daily', time: initial?.time || '09:00', intervalMinutes: initial?.intervalMinutes || 60, enabled: initial?.enabled ?? true, mode: initial?.mode || 'demo', agentIds: initial?.agentIds || [] });
  const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  async function save() { setBusy(true); setError(''); try { await write<Automation>(initial ? `/automations/${initial.id}` : '/automations', draft, initial ? 'PUT' : 'POST'); await onRefresh(); onClose(); } catch(e) { setError(messageOf(e)); } finally { setBusy(false); } }
  return <Dialog title={initial ? '编辑自动化' : '新的自动化'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); void save(); }}><Field label="名称"><Input aria-label="自动化名称" value={draft.title} onChange={event => setDraft({...draft,title:event.target.value})} placeholder="例如：每周项目准备" required /></Field><Field label="要做什么"><Textarea aria-label="自动化任务要求" value={draft.prompt} onChange={event => setDraft({...draft,prompt:event.target.value})} placeholder="说明你希望收到什么，以及需要注意的事。" rows={4} required /></Field><Field label="什么时候开始"><Select value={draft.trigger} onChange={option => setDraft({...draft,trigger:option.value as Automation['trigger']})} options={[{value:'daily',label:'每天固定时间'},{value:'interval',label:'间隔一段时间'},{value:'source_import',label:'导入新资料后'}]} /></Field>{draft.trigger === 'daily' && <Field label="本机时间"><Input aria-label="每天运行时间" type="time" value={draft.time} onChange={event => setDraft({...draft,time:event.target.value})} required /></Field>}{draft.trigger === 'interval' && <Field label="间隔分钟数"><Input aria-label="自动化间隔分钟" type="number" min={1} value={String(draft.intervalMinutes)} onChange={event => setDraft({...draft,intervalMinutes:Number(event.target.value)})} required /></Field>}<Field label="执行方式"><Select value={draft.mode} onChange={option => setDraft({...draft,mode:option.value as Automation['mode']})} options={[{value:'demo',label:'本地流程演示'},{value:'live',label:'我的模型'}]} /></Field>{data.agents.length > 0 && <Field label="参与角色"><div className="agent-check-list">{data.agents.map(agent => <Checkbox key={agent.id} label={agent.name} checked={draft.agentIds.includes(agent.id)} onCheckedChange={checked => setDraft({...draft,agentIds:checked ? [...draft.agentIds,agent.id] : draft.agentIds.filter(id=>id!==agent.id)})} />)}</div></Field>}<Switch label="保存后启用" checked={draft.enabled} onCheckedChange={enabled=>setDraft({...draft,enabled})} /><p className="field-hint">只有这台电脑和本机服务在线时才会运行。需要确认的操作仍会停下来等你。</p><ErrorNotice error={error} /><div className="dialog-actions"><Button type="button" color="secondary" variant="ghost" onClick={onClose}>取消</Button><Button type="submit" color="primary" loading={busy} disabled={busy || !draft.title.trim() || !draft.prompt.trim()}>保存自动化</Button></div></form></Dialog>;
}

export function AutomationWorkspace({ data, onRefresh, onTask }: { data: Bootstrap; onRefresh: () => Promise<void>; onTask: (id:string)=>void }) {
  const [editing,setEditing] = useState<Automation|null|undefined>(undefined); const [busy,setBusy] = useState(''); const [error,setError] = useState('');
  async function toggle(item: Automation, enabled:boolean) { setBusy(item.id);setError('');try { await write(`/automations/${item.id}`,{...item,enabled},'PUT');await onRefresh(); } catch(e) { setError(messageOf(e)); } finally {setBusy('');} }
  async function run(item: Automation) { setBusy(item.id);setError('');try { const task = await write<Task>(`/automations/${item.id}/run`);await onRefresh();onTask(task.id); } catch(e) { setError(messageOf(e)); } finally {setBusy('');} }
  return <div className="page-content"><PageHeading title="自动化" description="把需要反复照看的事，交给固定的安排。" action={<Button color="primary" onClick={()=>setEditing(null)}><Plus />新建自动化</Button>} /><ErrorNotice error={error} />{data.automations.length ? <div className="automation-list">{data.automations.map(item=><section className="automation-row" key={item.id}><div className="automation-title"><Clock /><div><h2>{item.title}</h2><p>{item.trigger==='daily' ? `每天 ${item.time}` : item.trigger==='interval' ? `每 ${item.intervalMinutes} 分钟` : '导入新资料后'} · {item.mode==='demo' ? '本地演示' : '我的模型'}</p></div><Switch label={item.enabled ? '已启用' : '已暂停'} checked={item.enabled} disabled={busy===item.id} onCheckedChange={enabled=>toggle(item,enabled)} /></div><p className="automation-prompt">{item.prompt}</p><div className="row spread wrap"><small className="secondary">{item.lastRunAt ? `上次：${when(item.lastRunAt)}` : '尚未运行'}{item.enabled && item.nextRunAt ? ` · 下次：${when(item.nextRunAt)}` : ''}</small><div className="row"><Button color="secondary" variant="ghost" size="sm" onClick={()=>setEditing(item)}><Edit />编辑</Button><Button color="secondary" variant="outline" size="sm" loading={busy===item.id} disabled={!!busy} onClick={()=>run(item)}><Play />运行一次</Button></div></div>{item.lastTaskId && <Button color="secondary" variant="ghost" size="sm" onClick={()=>onTask(item.lastTaskId!)}>查看上次任务</Button>}</section>)}</div> : <Empty title="先从一件小事开始" description="例如每天整理当前目标，或在资料导入后提醒你检查新的认识。" action={<Button color="secondary" variant="outline" onClick={()=>setEditing(null)}>创建第一项自动化</Button>} />}<p className="page-footnote">自动化仅在当前电脑在线时运行。执行方式和每次结果都可以单独检查。</p>{editing !== undefined && <AutomationForm initial={editing || undefined} data={data} onRefresh={onRefresh} onClose={()=>setEditing(undefined)} />}</div>;
}
