import { useEffect, useRef, useState } from 'react';
import type { Bootstrap, Project } from '../shared/contracts';
import { Button, ButtonLink } from '@openai/apps-sdk-ui/components/Button';
import { Input } from '@openai/apps-sdk-ui/components/Input';
import { Textarea } from '@openai/apps-sdk-ui/components/Textarea';
import { Menu } from '@openai/apps-sdk-ui/components/Menu';
import { Folder, Plus, ArrowRight, ArrowLeft, Chat, Document, Edit, Archive, ChevronDown, DotsHorizontalMoreMenu } from '@openai/apps-sdk-ui/components/Icon';
import { Dialog, Field, ErrorNotice, Empty, when } from './components';
import { api, write, messageOf, APIError } from './api';
import { t } from './i18n';
import { SpotIllustration } from './SpotIllustration';
import './projects.css';

export function ProjectPicker({data,value,onChange,disabled=false}:{data:Pick<Bootstrap,'projects'>;value?:string;onChange:(id:string|undefined)=>void;disabled?:boolean}){
  const projects=(data.projects||[]).filter(project=>!project.archived||project.id===value);
  const selected=projects.find(project=>project.id===value);
  const label=selected?.name||t('选择项目','Choose project');
  return <Menu><Menu.Trigger><Button type="button" color="secondary" variant="ghost" size="sm" pill={false} className="project-picker" disabled={disabled} aria-label={t(`所属项目：${label}`,`Project: ${label}`)}><Folder/><span>{label}</span><ChevronDown/></Button></Menu.Trigger><Menu.Content side="top" align="start" minWidth={210} maxHeight={320}><Menu.RadioGroup value={value||'none'} onChange={next=>onChange(next==='none'?undefined:next)}><Menu.RadioItem className="project-picker-option" value="none"><span className="project-picker-option-copy"><Folder/><span>{t('不关联项目','No project')}</span></span></Menu.RadioItem>{projects.map(project=><Menu.RadioItem className="project-picker-option" key={project.id} value={project.id}><span className="project-picker-option-copy"><Folder/><span>{project.name}{project.archived?t('（已归档）',' (archived)'):''}</span></span></Menu.RadioItem>)}</Menu.RadioGroup></Menu.Content></Menu>;
}
export function ProjectEditor({project,onClose,onSaved}:{project?:Project;onClose:()=>void;onSaved:(p:Project)=>Promise<void>}){
  const [savedId,setSavedId]=useState(project?.id);const [name,setName]=useState(project?.name||'');const [kind,setKind]=useState<'local'|'remote'>(project?.kind||'local');const [location,setLocation]=useState(project?.path||project?.url||'');const [description,setDescription]=useState(project?.description||'');const [saving,setSaving]=useState(false);const [choosing,setChoosing]=useState(false);const [manual,setManual]=useState(false);const [noteOpen,setNoteOpen]=useState(!!project?.description);const [error,setError]=useState('');
  const nameInput=useRef<HTMLInputElement>(null);const busy=saving||choosing;
  useEffect(()=>{const frame=requestAnimationFrame(()=>nameInput.current?.focus());return()=>cancelAnimationFrame(frame);},[]);
  async function chooseFolder(){
    if(busy)return;setChoosing(true);setError('');
    try {const selected=window.hitherDesktop?await window.hitherDesktop.chooseDirectory():(await write<{path:string|null}>('/projects/choose-directory')).path;
      if(selected){setLocation(selected);setName(current=>current.trim()?current:selected.replace(/[\\/]+$/,'').split(/[\\/]/).at(-1)||'');setManual(false);}
    }catch(err){setManual(true);const code=err instanceof APIError?err.code:undefined;setError(code==='directory_picker_unavailable'?t('系统选择器暂不可用，可在下方输入文件夹路径。','The system picker is unavailable. Enter a folder path below.'):code==='directory_picker_timeout'?t('选择已超时，请重新打开。','Selection timed out. Open the picker again.'):code==='directory_picker_busy'?t('已有选择窗口，请先完成或取消。','Finish or cancel the existing picker first.'):t('无法打开文件夹选择器，请重试或输入路径。','Could not open the folder picker. Try again or enter the path.'));}
    finally{setChoosing(false);}
  }
  function changeKind(next:'local'|'remote'){if(kind===next)return;setKind(next);setLocation('');setError('');setManual(false);}
  return <Dialog title={project?t('项目设置','Project settings'):t('创建项目','Create project')} className="project-editor" onClose={()=>{if(!busy)onClose();}}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setSaving(true);setError('');try{const saved=await write<Project>(savedId?`/projects/${savedId}`:'/projects',{name:name.trim(),kind,...(kind==='local'?{path:location.trim()}:{url:location.trim()}),description},savedId?'PUT':'POST');setSavedId(saved.id);await onSaved(saved);}catch(err){setError(messageOf(err));}finally{setSaving(false);}}}><fieldset disabled={busy} className="project-editor-fields">
    <div className={!project?'spot-field-heading':undefined}><Field label={t('项目名称','Project name')}><Input ref={nameInput} startAdornment={<Folder/>} size="xl" value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder={t('给这段工作起个名字','Name this work')}/></Field>{!project&&<SpotIllustration scene="archive"/>}</div>
    <section className="project-source-section" aria-label={t('源文件夹','Source folder')}><h3>{t('源文件夹','Source folder')}</h3><div className={`project-source-card ${location?'has-location':''}`}>
      {!project?<Menu><Menu.Trigger><Button type="button" className="project-source-kind" color="secondary" variant="ghost" disabled={busy}>{kind==='local'?t('在此电脑上添加文件夹','Add a folder on this computer'):t('保存远程项目链接','Save a remote project link')}{kind==='remote'&&<span className="project-dev-label">Dev</span>}<ChevronDown/></Button></Menu.Trigger><Menu.Content align="center" minWidth={220}><Menu.Item onSelect={()=>changeKind('local')}><Folder/>{t('此电脑','This computer')}</Menu.Item><Menu.Item onSelect={()=>changeKind('remote')}><span>{t('远程项目','Remote project')} <span className="project-dev-label">Dev</span></span></Menu.Item></Menu.Content></Menu>:<span className="project-source-label">{kind==='local'?t('此电脑','This computer'):t('远程项目链接','Remote project link')}</span>}
      {kind==='local'?<>{location&&<div className="project-selected-folder"><Folder/><div><strong>{location.replace(/[\\/]+$/,'').split(/[\\/]/).at(-1)||location}</strong><span>{location}</span></div></div>}{!project&&<Button type="button" color="secondary" variant="soft" className="project-add-folder" loading={choosing} onClick={()=>void chooseFolder()}><Plus/>{choosing?t('正在选择','Choosing'):location?t('更换文件夹','Change folder'):t('添加','Add')}</Button>}</>:<div className="project-remote-input"><Input aria-label={t('远程项目链接','Remote project link')} value={location} onChange={e=>setLocation(e.target.value)} placeholder="https://github.com/owner/project" readOnly={!!project}/><p>{t('仅保存链接，远程执行仍在开发中。','Links only. Remote execution is in development.')}</p></div>}
    </div>{kind==='local'&&<p className="project-source-hint">{t('文件保留在原位置，项目任务在此文件夹内执行。','Files stay in place. Project tasks run in this folder.')}</p>}{kind==='local'&&!project&&<details className="project-manual-path" open={manual} onToggle={event=>setManual(event.currentTarget.open)}><summary>{t('手动输入路径','Enter a path manually')}</summary><Input aria-label={t('文件夹绝对路径','Absolute folder path')} value={location} onChange={e=>setLocation(e.target.value)} placeholder={t('粘贴本机文件夹的完整路径','Paste the full local folder path')}/></details>}</section>
    <details className="project-optional-note" open={noteOpen} onToggle={event=>setNoteOpen(event.currentTarget.open)}><summary>{t('添加备注（可选）','Add a note (optional)')}</summary><Textarea aria-label={t('项目备注','Project note')} value={description} onChange={e=>setDescription(e.target.value)} rows={2} maxLength={2000} placeholder={t('目标、约束或文件夹用途','Goals, constraints, or the purpose of this folder')}/></details>
    <ErrorNotice error={error}/><footer><Button type="button" color="secondary" variant="ghost" onClick={onClose}>{t('取消','Cancel')}</Button><Button color="primary" type="submit" loading={saving} disabled={busy||!name.trim()||!location.trim()}>{project?t('保存','Save'):t('创建项目','Create project')}</Button></footer></fieldset>
  </form></Dialog>;
}
export function ProjectWorkspace({data,id,onRefresh,onChat}:{data:Bootstrap;id?:string;onRefresh:()=>Promise<void>;onChat:(id:string)=>void}){
  const [editing,setEditing]=useState<Project|'new'>();const [tab,setTab]=useState<'chats'|'files'>('chats');const [archived,setArchived]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const project=(data.projects||[]).find(p=>p.id===id);const projects=(data.projects||[]).filter(p=>p.archived===archived);
  const tasks=data.tasks.filter(task=>task.projectId===id);const rooms=(data.agentRooms||[]).filter(room=>room.projectId===id);const roomTasks=new Set(rooms.flatMap(room=>room.taskIds));
  const chats=[...rooms.map(room=>({id:room.id,title:room.title,date:room.updatedAt,href:`#agents/${room.id}`})),...tasks.filter(task=>!roomTasks.has(task.id)).map(task=>({id:task.id,title:task.title,date:task.updatedAt,href:`#task/${task.id}`}))].sort((a,b)=>b.date.localeCompare(a.date));
  const taskIds=new Set(tasks.map(task=>task.id));const artifacts=data.artifacts.filter(a=>taskIds.has(a.taskId)&&a.classification!=='reply_snapshot');
  return <section className="project-workspace"><ErrorNotice error={error}/>{!id?<><header className="project-page-heading"><div><h1>{t('项目','Projects')}</h1><p>{t('把文件、对话和需要持续推进的工作放在一起。','Keep files, conversations, and ongoing work together.')}</p></div><Button color="primary" onClick={()=>setEditing('new')}><Plus/>{t('新建项目','New project')}</Button></header><div className="project-tabs"><button aria-pressed={!archived} onClick={()=>setArchived(false)}>{t('正在进行','Active')}</button><button aria-pressed={archived} onClick={()=>setArchived(true)}>{t('已归档','Archived')}</button></div>{projects.length?<div className="project-list">{projects.map(p=><a href={`#projects/${p.id}`} key={p.id}><span className="project-folder"><Folder/></span><div><strong>{p.name}</strong><span>{p.description||p.path||p.url}</span></div><small>{p.kind==='local'?t('本地','Local'):t('远端链接','Remote link')}</small><ArrowRight/></a>)}</div>:<div className="project-empty"><img src="/art/paper-notebook.png" alt=""/><h2>{archived?t('没有已归档项目','No archived projects'):t('从一个文件夹开始','Start with a folder')}</h2><p>{archived?t('归档的项目仍保留对话和文件。','Archived projects keep their chats and files.'):t('关联已有文件夹，让后续工作沿用同一个项目。','Link an existing folder to keep future work in one project.')}</p>{!archived&&<Button color="secondary" variant="outline" onClick={()=>setEditing('new')}><Plus/>{t('添加项目','Add project')}</Button>}</div>}</>:project?<>
    <div className="project-topline"><a className="project-back" href="#projects"><ArrowLeft/>{t('所有项目','All projects')}</a><Menu><Menu.Trigger><Button color="secondary" variant="ghost" uniform aria-label={t('项目选项','Project options')} disabled={busy}><DotsHorizontalMoreMenu/></Button></Menu.Trigger><Menu.Content align="end" minWidth={164}><Menu.Item onSelect={()=>setEditing(project)}><Edit/>{t('项目设置','Project settings')}</Menu.Item><Menu.Item onSelect={()=>{setBusy(true);setError('');void write(`/projects/${project.id}`,{archived:!project.archived},'PUT').then(onRefresh).catch(err=>setError(messageOf(err))).finally(()=>setBusy(false));}}><Archive/>{project.archived?t('恢复项目','Restore project'):t('归档项目','Archive project')}</Menu.Item></Menu.Content></Menu></div>
    <header className="project-page-heading project-detail-heading"><div><h1><Folder/>{project.name}</h1>{project.description&&<p className="project-description">{project.description}</p>}<details className="project-location"><summary>{project.kind==='local'?t('本地文件夹','Local folder'):t('远程项目','Remote project')}<ChevronDown/></summary><p>{project.path||project.url}</p></details></div>{project.archived&&<span className="project-archived-label">{t('已归档','Archived')}</span>}</header>
    {project.execution.status!=='ready'&&<p className="project-runtime-note">{project.kind==='remote'?t('连接执行环境后即可在此开始任务。','Connect a runtime to start a task here.'):project.execution.reason}{project.url&&/^https?:\/\//.test(project.url)&&<a href={project.url} target="_blank" rel="noreferrer">{t('打开链接','Open link')} ↗</a>}</p>}
    <div className="project-toolbar"><div className="project-tabs"><button aria-pressed={tab==='chats'} onClick={()=>setTab('chats')}>{t('对话','Chats')}{chats.length>0&&<span>{chats.length}</span>}</button><button aria-pressed={tab==='files'} onClick={()=>setTab('files')}>{t('文件','Files')}</button></div>{!project.archived&&(chats.length>0||tab==='files')&&<Button color="secondary" variant="ghost" size="sm" disabled={project.execution.status!=='ready'} onClick={()=>onChat(project.id)}><Plus/>{t('新对话','New chat')}</Button>}</div>
    {tab==='chats'?(chats.length?<div className="project-content-list">{chats.map(chat=><a href={chat.href} key={chat.id}><Chat/><strong>{chat.title}</strong><time>{when(chat.date)}</time><ArrowRight/></a>)}</div>:<div className="project-chat-empty"><SpotIllustration scene="conversation"/><h2>{project.archived?t('这里还没有对话','No conversations yet'):t('开始这个项目的第一段对话','Start a conversation for this project')}</h2><p>{t('围绕项目提问、整理思路，或继续处理文件。','Ask about this project, work through ideas, or make progress on its files.')}</p>{!project.archived&&<Button color="primary" disabled={project.execution.status!=='ready'} onClick={()=>onChat(project.id)}><Plus/>{t('开始对话','Start a conversation')}</Button>}</div> ):<><ProjectFiles key={project.id} project={project}/><h2 className="project-files-heading">{t('任务成果','Task files')}</h2>{artifacts.length?<div className="project-content-list">{artifacts.map(a=><a href={`#artifacts/${a.id}`} key={a.id}><Document/><strong>{a.name}</strong><time>{when(a.updatedAt)}</time><ArrowRight/></a>)}</div>:<p className="project-files-empty">{t('对话中生成和修改的文件会收在这里。','Files created or updated in your conversations will appear here.')}</p>}</>}
  </>:<Empty title={t('找不到这个项目','Project not found')}/>}
    {editing&&<ProjectEditor project={editing==='new'?undefined:editing} onClose={()=>setEditing(undefined)} onSaved={async saved=>{await onRefresh();setEditing(undefined);location.hash=`projects/${saved.id}`;}}/>}
  </section>;
}

function ProjectFiles({project}:{project:Project}){
  const [path,setPath]=useState('');const [result,setResult]=useState<{entries:Array<{name:string;path:string;kind:'directory'|'file';size?:number}>;truncated:boolean}>();const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  useEffect(()=>{if(project.kind!=='local')return;let current=true;setLoading(true);setError('');void api<{entries:Array<{name:string;path:string;kind:'directory'|'file';size?:number}>;truncated:boolean}>(`/projects/${project.id}/files?path=${encodeURIComponent(path)}`).then(value=>{if(current)setResult(value);}).catch(err=>{if(current){setResult(undefined);setError(messageOf(err));}}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[project.id,project.execution.status,path]);
  if(project.kind!=='local')return null;
  return <section className="project-files"><div className="project-files-heading"><h2>{t('项目文件夹','Project folder')}</h2><span>{path||project.name}</span>{path&&<button onClick={()=>setPath(path.split('/').slice(0,-1).join('/'))}><ArrowLeft/>{t('上一级','Parent folder')}</button>}</div><ErrorNotice error={error}/>{loading?<p>{t('正在读取','Loading')}</p>:result?.entries.length?<div className="project-file-entries">{result.entries.map(entry=>entry.kind==='directory'?<button key={entry.path} onClick={()=>setPath(entry.path)}><Folder/><span>{entry.name}</span><ArrowRight/></button>:<div key={entry.path}><Document/><span>{entry.name}</span><small>{entry.size!==undefined?(entry.size<1024?`${entry.size} B`:`${Math.round(entry.size/1024)} KB`):''}</small></div>)}</div>:!error&&<p>{t('这个文件夹暂时为空。','This folder is empty.')}</p>}{result?.truncated&&<p>{t('仅显示前 200 项，请进入具体文件夹查看。','Showing the first 200 entries. Open a subfolder to browse further.')}</p>}</section>;
}
